// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_cmd_heat_camera.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cmd.HeatCamera;

@kotlin.jvm.JvmName("-initializefocusIn")
public inline fun focusIn(block: com.cmd.HeatCamera.FocusInKt.Dsl.() -> kotlin.Unit): com.cmd.HeatCamera.FocusIn =
  com.cmd.HeatCamera.FocusInKt.Dsl._create(com.cmd.HeatCamera.FocusIn.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `cmd.HeatCamera.FocusIn`
 */
public object FocusInKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cmd.HeatCamera.FocusIn.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cmd.HeatCamera.FocusIn.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cmd.HeatCamera.FocusIn = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cmd.HeatCamera.FocusIn.copy(block: `com.cmd.HeatCamera`.FocusInKt.Dsl.() -> kotlin.Unit): com.cmd.HeatCamera.FocusIn =
  `com.cmd.HeatCamera`.FocusInKt.Dsl._create(this.toBuilder()).apply { block() }._build()

