// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_cmd_heat_camera.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cmd.HeatCamera;

@kotlin.jvm.JvmName("-initializefocusStepPlus")
public inline fun focusStepPlus(block: com.cmd.HeatCamera.FocusStepPlusKt.Dsl.() -> kotlin.Unit): com.cmd.HeatCamera.FocusStepPlus =
  com.cmd.HeatCamera.FocusStepPlusKt.Dsl._create(com.cmd.HeatCamera.FocusStepPlus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `cmd.HeatCamera.FocusStepPlus`
 */
public object FocusStepPlusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cmd.HeatCamera.FocusStepPlus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cmd.HeatCamera.FocusStepPlus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cmd.HeatCamera.FocusStepPlus = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cmd.HeatCamera.FocusStepPlus.copy(block: `com.cmd.HeatCamera`.FocusStepPlusKt.Dsl.() -> kotlin.Unit): com.cmd.HeatCamera.FocusStepPlus =
  `com.cmd.HeatCamera`.FocusStepPlusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

