syntax = "proto3";

option go_package = "git-codecommit.eu-central-1.amazonaws.com/v1/repos/jettison/jonp/ui";

package ui;

message Screen {
  optional WidgetNode root = 1;
}

message WidgetNode {
  WidgetType type = 1;
  int32 x = 2;
  int32 y = 3;
  string text = 4;
  map<string, string> bindings = 5;
  EventBinding event = 6;
  Layout layout = 7;
  repeated WidgetNode children = 8;
  repeated StyleGroup style_groups = 9;
}

enum WidgetType {
  WIDGET_OBJ = 0;
  WIDGET_BUTTON = 1;
  WIDGET_LABEL = 2;
  WIDGET_SLIDER = 3;
  WIDGET_IMAGE = 4;
}

message EventBinding {
  string event_name = 1;
  uint32 command_type = 2;
  double float_value = 3;
  int32 int_value = 4;
}

message Layout {
  LayoutFlow flow = 1;
}

enum LayoutFlow {
  LAYOUT_NONE = 0;
  LAYOUT_FLEX_ROW = 1;
  LAYOUT_FLEX_COLUMN = 2;
}

message StyleGroup {
  uint32 state_selector = 1;
  repeated ResolvedStyle variants = 2;
}

message ResolvedStyle {
  repeated StyleProperty properties = 1;
}

message StyleProperty {
  StylePropertyType type = 1;
  oneof value {
    uint32 uint_value = 2;
    int32 int_value = 3;
    Color color_value = 4;
    string string_value = 5;
    ShadowBundle shadow_value = 6;
  }
}

enum StylePropertyType {
  PROP_BG_COLOR = 0;
  PROP_BG_OPA = 1;
  PROP_TEXT_COLOR = 2;
  PROP_TEXT_FONT = 3;
  PROP_BORDER_COLOR = 4;
  PROP_BORDER_WIDTH = 5;
  PROP_RADIUS = 6;
  PROP_PAD_ALL = 7;
  PROP_PAD_GAP = 8;
  PROP_WIDTH = 9;
  PROP_HEIGHT = 10;
  PROP_SHADOW = 11;
  PROP_PAD_HOR = 12;
  PROP_PAD_VER = 13;
  PROP_MARGIN_ALL = 14;
  PROP_BORDER_OPA = 15;
}

message Color {
  uint32 r = 1;
  uint32 g = 2;
  uint32 b = 3;
}

message ShadowBundle {
  uint32 width = 1;
  int32 offset_x = 2;
  int32 offset_y = 3;
  uint32 spread = 4;
  uint32 opa = 5;
}
