// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: jon_shared_data_camera_day.proto

package ser;


@SuppressWarnings("all")
public class JonSharedDataCameraDayValidator {
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		
		if (clazz.equals(ser.JonSharedDataCameraDay.JonGuiDataCameraDay.class)) return new JonGuiDataCameraDayValidator();
		return null;
	}


/**
	 * Validates {@code JonGuiDataCameraDay} protobuf objects.
	 */
	public static class JonGuiDataCameraDayValidator implements io.envoyproxy.pgv.ValidatorImpl<ser.JonSharedDataCameraDay.JonGuiDataCameraDay> {
		
	
		
	
		
	
		
	
		
	
		
	
		
	
		
	
		
	
		
	
		
	
	
	

	public void assertValid(ser.JonSharedDataCameraDay.JonGuiDataCameraDay proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for FocusPos

	// no validation rules for ZoomPos

	// no validation rules for IrisPos

	// no validation rules for InfraredFilter

	// no validation rules for ZoomTablePos

	// no validation rules for ZoomTablePosMax

	// no validation rules for FxMode

	// no validation rules for AutoFocus

	// no validation rules for AutoIris

	// no validation rules for DigitalZoomLevel

	// no validation rules for ClaheLevel

	
	
	}
}
}

