// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: jon_shared_cmd_lira.proto

package lira

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Root struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Root_RefineTarget
	Cmd           isRoot_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Root) Reset() {
	*x = Root{}
	mi := &file_jon_shared_cmd_lira_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Root) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Root) ProtoMessage() {}

func (x *Root) ProtoReflect() protoreflect.Message {
	mi := &file_jon_shared_cmd_lira_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Root.ProtoReflect.Descriptor instead.
func (*Root) Descriptor() ([]byte, []int) {
	return file_jon_shared_cmd_lira_proto_rawDescGZIP(), []int{0}
}

func (x *Root) GetCmd() isRoot_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Root) GetRefineTarget() *RefineTarget {
	if x != nil {
		if x, ok := x.Cmd.(*Root_RefineTarget); ok {
			return x.RefineTarget
		}
	}
	return nil
}

type isRoot_Cmd interface {
	isRoot_Cmd()
}

type Root_RefineTarget struct {
	RefineTarget *RefineTarget `protobuf:"bytes,1,opt,name=refine_target,json=refineTarget,proto3,oneof"`
}

func (*Root_RefineTarget) isRoot_Cmd() {}

type RefineTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *JonGuiDataLiraTarget  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineTarget) Reset() {
	*x = RefineTarget{}
	mi := &file_jon_shared_cmd_lira_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineTarget) ProtoMessage() {}

func (x *RefineTarget) ProtoReflect() protoreflect.Message {
	mi := &file_jon_shared_cmd_lira_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineTarget.ProtoReflect.Descriptor instead.
func (*RefineTarget) Descriptor() ([]byte, []int) {
	return file_jon_shared_cmd_lira_proto_rawDescGZIP(), []int{1}
}

func (x *RefineTarget) GetTarget() *JonGuiDataLiraTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

type JonGuiDataLiraTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TargetLongitude float64                `protobuf:"fixed64,2,opt,name=target_longitude,json=targetLongitude,proto3" json:"target_longitude,omitempty"`
	TargetLatitude  float64                `protobuf:"fixed64,3,opt,name=target_latitude,json=targetLatitude,proto3" json:"target_latitude,omitempty"`
	TargetAltitude  float64                `protobuf:"fixed64,4,opt,name=target_altitude,json=targetAltitude,proto3" json:"target_altitude,omitempty"`
	TargetAzimuth   float64                `protobuf:"fixed64,5,opt,name=target_azimuth,json=targetAzimuth,proto3" json:"target_azimuth,omitempty"`
	TargetElevation float64                `protobuf:"fixed64,6,opt,name=target_elevation,json=targetElevation,proto3" json:"target_elevation,omitempty"`
	Distance        float64                `protobuf:"fixed64,7,opt,name=distance,proto3" json:"distance,omitempty"`
	// UUID as four fixed32 values (128 bits total)
	UuidPart1     int32 `protobuf:"varint,8,opt,name=uuid_part1,json=uuidPart1,proto3" json:"uuid_part1,omitempty"`
	UuidPart2     int32 `protobuf:"varint,9,opt,name=uuid_part2,json=uuidPart2,proto3" json:"uuid_part2,omitempty"`
	UuidPart3     int32 `protobuf:"varint,10,opt,name=uuid_part3,json=uuidPart3,proto3" json:"uuid_part3,omitempty"`
	UuidPart4     int32 `protobuf:"varint,11,opt,name=uuid_part4,json=uuidPart4,proto3" json:"uuid_part4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JonGuiDataLiraTarget) Reset() {
	*x = JonGuiDataLiraTarget{}
	mi := &file_jon_shared_cmd_lira_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JonGuiDataLiraTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JonGuiDataLiraTarget) ProtoMessage() {}

func (x *JonGuiDataLiraTarget) ProtoReflect() protoreflect.Message {
	mi := &file_jon_shared_cmd_lira_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JonGuiDataLiraTarget.ProtoReflect.Descriptor instead.
func (*JonGuiDataLiraTarget) Descriptor() ([]byte, []int) {
	return file_jon_shared_cmd_lira_proto_rawDescGZIP(), []int{2}
}

func (x *JonGuiDataLiraTarget) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetTargetLongitude() float64 {
	if x != nil {
		return x.TargetLongitude
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetTargetLatitude() float64 {
	if x != nil {
		return x.TargetLatitude
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetTargetAltitude() float64 {
	if x != nil {
		return x.TargetAltitude
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetTargetAzimuth() float64 {
	if x != nil {
		return x.TargetAzimuth
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetTargetElevation() float64 {
	if x != nil {
		return x.TargetElevation
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetUuidPart1() int32 {
	if x != nil {
		return x.UuidPart1
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetUuidPart2() int32 {
	if x != nil {
		return x.UuidPart2
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetUuidPart3() int32 {
	if x != nil {
		return x.UuidPart3
	}
	return 0
}

func (x *JonGuiDataLiraTarget) GetUuidPart4() int32 {
	if x != nil {
		return x.UuidPart4
	}
	return 0
}

var File_jon_shared_cmd_lira_proto protoreflect.FileDescriptor

const file_jon_shared_cmd_lira_proto_rawDesc = "" +
	"\n" +
	"\x19jon_shared_cmd_lira.proto\x12\bcmd.Lira\x1a\x1bbuf/validate/validate.proto\"T\n" +
	"\x04Root\x12>\n" +
	"\rrefine_target\x18\x01 \x01(\v2\x17.cmd.Lira.Refine_targetH\x00R\frefineTargetB\f\n" +
	"\x03cmd\x12\x05\xbaH\x02\b\x01\"G\n" +
	"\rRefine_target\x126\n" +
	"\x06target\x18\x01 \x01(\v2\x1e.cmd.Lira.JonGuiDataLiraTargetR\x06target\"\xb1\x04\n" +
	"\x14JonGuiDataLiraTarget\x12%\n" +
	"\ttimestamp\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\ttimestamp\x12B\n" +
	"\x10target_longitude\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x0ftargetLongitude\x12@\n" +
	"\x0ftarget_latitude\x18\x03 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x0etargetLatitude\x12@\n" +
	"\x0ftarget_altitude\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00j\xf8@)\x00\x00\x00\x00\x00\xe0z\xc0R\x0etargetAltitude\x12>\n" +
	"\x0etarget_azimuth\x18\x05 \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80v@)\x00\x00\x00\x00\x00\x00\x00\x00R\rtargetAzimuth\x12B\n" +
	"\x10target_elevation\x18\x06 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x0ftargetElevation\x12*\n" +
	"\bdistance\x18\a \x01(\x01B\x0e\xbaH\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\bdistance\x12\x1d\n" +
	"\n" +
	"uuid_part1\x18\b \x01(\x05R\tuuidPart1\x12\x1d\n" +
	"\n" +
	"uuid_part2\x18\t \x01(\x05R\tuuidPart2\x12\x1d\n" +
	"\n" +
	"uuid_part3\x18\n" +
	" \x01(\x05R\tuuidPart3\x12\x1d\n" +
	"\n" +
	"uuid_part4\x18\v \x01(\x05R\tuuidPart4B\xb1\x01\n" +
	"\fcom.cmd.LiraB\x15JonSharedCmdLiraProtoP\x01ZIgit-codecommit.eu-central-1.amazonaws.com/v1/repos/jettison/jonp/cmd/lira\xa2\x02\x03CLX\xaa\x02\bCmd.Lira\xca\x02\bCmd\\Lira\xe2\x02\x14Cmd\\Lira\\GPBMetadata\xea\x02\tCmd::Lirab\x06proto3"

var (
	file_jon_shared_cmd_lira_proto_rawDescOnce sync.Once
	file_jon_shared_cmd_lira_proto_rawDescData []byte
)

func file_jon_shared_cmd_lira_proto_rawDescGZIP() []byte {
	file_jon_shared_cmd_lira_proto_rawDescOnce.Do(func() {
		file_jon_shared_cmd_lira_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jon_shared_cmd_lira_proto_rawDesc), len(file_jon_shared_cmd_lira_proto_rawDesc)))
	})
	return file_jon_shared_cmd_lira_proto_rawDescData
}

var file_jon_shared_cmd_lira_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jon_shared_cmd_lira_proto_goTypes = []any{
	(*Root)(nil),                 // 0: cmd.Lira.Root
	(*RefineTarget)(nil),         // 1: cmd.Lira.Refine_target
	(*JonGuiDataLiraTarget)(nil), // 2: cmd.Lira.JonGuiDataLiraTarget
}
var file_jon_shared_cmd_lira_proto_depIdxs = []int32{
	1, // 0: cmd.Lira.Root.refine_target:type_name -> cmd.Lira.Refine_target
	2, // 1: cmd.Lira.Refine_target.target:type_name -> cmd.Lira.JonGuiDataLiraTarget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jon_shared_cmd_lira_proto_init() }
func file_jon_shared_cmd_lira_proto_init() {
	if File_jon_shared_cmd_lira_proto != nil {
		return
	}
	file_jon_shared_cmd_lira_proto_msgTypes[0].OneofWrappers = []any{
		(*Root_RefineTarget)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jon_shared_cmd_lira_proto_rawDesc), len(file_jon_shared_cmd_lira_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jon_shared_cmd_lira_proto_goTypes,
		DependencyIndexes: file_jon_shared_cmd_lira_proto_depIdxs,
		MessageInfos:      file_jon_shared_cmd_lira_proto_msgTypes,
	}.Build()
	File_jon_shared_cmd_lira_proto = out.File
	file_jon_shared_cmd_lira_proto_goTypes = nil
	file_jon_shared_cmd_lira_proto_depIdxs = nil
}
