// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: jon_shared_data_time.proto

package time

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on JonGuiDataTime with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JonGuiDataTime) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JonGuiDataTime with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JonGuiDataTimeMultiError,
// or nil if none found.
func (m *JonGuiDataTime) ValidateAll() error {
	return m.validate(true)
}

func (m *JonGuiDataTime) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Timestamp

	// no validation rules for ManualTimestamp

	// no validation rules for ZoneId

	// no validation rules for UseManualTime

	if len(errors) > 0 {
		return JonGuiDataTimeMultiError(errors)
	}

	return nil
}

// JonGuiDataTimeMultiError is an error wrapping multiple validation errors
// returned by JonGuiDataTime.ValidateAll() if the designated constraints
// aren't met.
type JonGuiDataTimeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JonGuiDataTimeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JonGuiDataTimeMultiError) AllErrors() []error { return m }

// JonGuiDataTimeValidationError is the validation error returned by
// JonGuiDataTime.Validate if the designated constraints aren't met.
type JonGuiDataTimeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JonGuiDataTimeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JonGuiDataTimeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JonGuiDataTimeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JonGuiDataTimeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JonGuiDataTimeValidationError) ErrorName() string { return "JonGuiDataTimeValidationError" }

// Error satisfies the builtin error interface
func (e JonGuiDataTimeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJonGuiDataTime.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JonGuiDataTimeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JonGuiDataTimeValidationError{}
