// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opaque/detection_common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ser;

@kotlin.jvm.JvmName("-initializedetectionConfig")
public inline fun detectionConfig(block: ser.DetectionConfigKt.Dsl.() -> kotlin.Unit): ser.DetectionCommon.DetectionConfig =
  ser.DetectionConfigKt.Dsl._create(ser.DetectionCommon.DetectionConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * Inference configuration used for this result.
 * ```
 *
 * Protobuf type `ser.DetectionConfig`
 */
public object DetectionConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ser.DetectionCommon.DetectionConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ser.DetectionCommon.DetectionConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ser.DetectionCommon.DetectionConfig = _builder.build()

    /**
     * ```
     * Confidence threshold used for filtering [0.0, 1.0]
     * ```
     *
     * `float confidence_threshold = 1 [(.buf.validate.field) = { ... }`
     */
    public var confidenceThreshold: kotlin.Float
      @JvmName("getConfidenceThreshold")
      get() = _builder.confidenceThreshold
      @JvmName("setConfidenceThreshold")
      set(value) {
        _builder.confidenceThreshold = value
      }
    /**
     * ```
     * Confidence threshold used for filtering [0.0, 1.0]
     * ```
     *
     * `float confidence_threshold = 1 [(.buf.validate.field) = { ... }`
     */
    public fun clearConfidenceThreshold() {
      _builder.clearConfidenceThreshold()
    }

    /**
     * ```
     * NMS IoU threshold used for suppression [0.0, 1.0]
     * ```
     *
     * `float nms_iou_threshold = 2 [(.buf.validate.field) = { ... }`
     */
    public var nmsIouThreshold: kotlin.Float
      @JvmName("getNmsIouThreshold")
      get() = _builder.nmsIouThreshold
      @JvmName("setNmsIouThreshold")
      set(value) {
        _builder.nmsIouThreshold = value
      }
    /**
     * ```
     * NMS IoU threshold used for suppression [0.0, 1.0]
     * ```
     *
     * `float nms_iou_threshold = 2 [(.buf.validate.field) = { ... }`
     */
    public fun clearNmsIouThreshold() {
      _builder.clearNmsIouThreshold()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ser.DetectionCommon.DetectionConfig.copy(block: `ser`.DetectionConfigKt.Dsl.() -> kotlin.Unit): ser.DetectionCommon.DetectionConfig =
  `ser`.DetectionConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

