// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_data_rec_osd.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ser;

@kotlin.jvm.JvmName("-initializejonGuiDataRecOsd")
public inline fun jonGuiDataRecOsd(block: ser.JonGuiDataRecOsdKt.Dsl.() -> kotlin.Unit): ser.JonSharedDataRecOsd.JonGuiDataRecOsd =
  ser.JonGuiDataRecOsdKt.Dsl._create(ser.JonSharedDataRecOsd.JonGuiDataRecOsd.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ser.JonGuiDataRecOsd`
 */
public object JonGuiDataRecOsdKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ser.JonSharedDataRecOsd.JonGuiDataRecOsd.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ser.JonSharedDataRecOsd.JonGuiDataRecOsd.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ser.JonSharedDataRecOsd.JonGuiDataRecOsd = _builder.build()

    /**
     * `.ser.JonGuiDataRecOsdScreen screen = 1 [(.buf.validate.field) = { ... }`
     */
    public var screen: ser.JonSharedDataTypes.JonGuiDataRecOsdScreen
      @JvmName("getScreen")
      get() = _builder.screen
      @JvmName("setScreen")
      set(value) {
        _builder.screen = value
      }
    public var screenValue: kotlin.Int
      @JvmName("getScreenValue")
      get() = _builder.screenValue
      @JvmName("setScreenValue")
      set(value) {
        _builder.screenValue = value
      }
    /**
     * `.ser.JonGuiDataRecOsdScreen screen = 1 [(.buf.validate.field) = { ... }`
     */
    public fun clearScreen() {
      _builder.clearScreen()
    }

    /**
     * `bool heat_osd_enabled = 2;`
     */
    public var heatOsdEnabled: kotlin.Boolean
      @JvmName("getHeatOsdEnabled")
      get() = _builder.heatOsdEnabled
      @JvmName("setHeatOsdEnabled")
      set(value) {
        _builder.heatOsdEnabled = value
      }
    /**
     * `bool heat_osd_enabled = 2;`
     */
    public fun clearHeatOsdEnabled() {
      _builder.clearHeatOsdEnabled()
    }

    /**
     * `bool day_osd_enabled = 3;`
     */
    public var dayOsdEnabled: kotlin.Boolean
      @JvmName("getDayOsdEnabled")
      get() = _builder.dayOsdEnabled
      @JvmName("setDayOsdEnabled")
      set(value) {
        _builder.dayOsdEnabled = value
      }
    /**
     * `bool day_osd_enabled = 3;`
     */
    public fun clearDayOsdEnabled() {
      _builder.clearDayOsdEnabled()
    }

    /**
     * `int32 heat_crosshair_offset_horizontal = 4;`
     */
    public var heatCrosshairOffsetHorizontal: kotlin.Int
      @JvmName("getHeatCrosshairOffsetHorizontal")
      get() = _builder.heatCrosshairOffsetHorizontal
      @JvmName("setHeatCrosshairOffsetHorizontal")
      set(value) {
        _builder.heatCrosshairOffsetHorizontal = value
      }
    /**
     * `int32 heat_crosshair_offset_horizontal = 4;`
     */
    public fun clearHeatCrosshairOffsetHorizontal() {
      _builder.clearHeatCrosshairOffsetHorizontal()
    }

    /**
     * `int32 heat_crosshair_offset_vertical = 5;`
     */
    public var heatCrosshairOffsetVertical: kotlin.Int
      @JvmName("getHeatCrosshairOffsetVertical")
      get() = _builder.heatCrosshairOffsetVertical
      @JvmName("setHeatCrosshairOffsetVertical")
      set(value) {
        _builder.heatCrosshairOffsetVertical = value
      }
    /**
     * `int32 heat_crosshair_offset_vertical = 5;`
     */
    public fun clearHeatCrosshairOffsetVertical() {
      _builder.clearHeatCrosshairOffsetVertical()
    }

    /**
     * `int32 day_crosshair_offset_horizontal = 6;`
     */
    public var dayCrosshairOffsetHorizontal: kotlin.Int
      @JvmName("getDayCrosshairOffsetHorizontal")
      get() = _builder.dayCrosshairOffsetHorizontal
      @JvmName("setDayCrosshairOffsetHorizontal")
      set(value) {
        _builder.dayCrosshairOffsetHorizontal = value
      }
    /**
     * `int32 day_crosshair_offset_horizontal = 6;`
     */
    public fun clearDayCrosshairOffsetHorizontal() {
      _builder.clearDayCrosshairOffsetHorizontal()
    }

    /**
     * `int32 day_crosshair_offset_vertical = 7;`
     */
    public var dayCrosshairOffsetVertical: kotlin.Int
      @JvmName("getDayCrosshairOffsetVertical")
      get() = _builder.dayCrosshairOffsetVertical
      @JvmName("setDayCrosshairOffsetVertical")
      set(value) {
        _builder.dayCrosshairOffsetVertical = value
      }
    /**
     * `int32 day_crosshair_offset_vertical = 7;`
     */
    public fun clearDayCrosshairOffsetVertical() {
      _builder.clearDayCrosshairOffsetVertical()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ser.JonSharedDataRecOsd.JonGuiDataRecOsd.copy(block: `ser`.JonGuiDataRecOsdKt.Dsl.() -> kotlin.Unit): ser.JonSharedDataRecOsd.JonGuiDataRecOsd =
  `ser`.JonGuiDataRecOsdKt.Dsl._create(this.toBuilder()).apply { block() }._build()

