// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: jon_shared_data_compass.proto

package compass

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JonGuiDataCompass struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Azimuth             float64                `protobuf:"fixed64,1,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	Elevation           float64                `protobuf:"fixed64,2,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Bank                float64                `protobuf:"fixed64,3,opt,name=bank,proto3" json:"bank,omitempty"`
	OffsetAzimuth       float64                `protobuf:"fixed64,4,opt,name=offsetAzimuth,proto3" json:"offsetAzimuth,omitempty"`
	OffsetElevation     float64                `protobuf:"fixed64,5,opt,name=offsetElevation,proto3" json:"offsetElevation,omitempty"`
	MagneticDeclination float64                `protobuf:"fixed64,6,opt,name=magneticDeclination,proto3" json:"magneticDeclination,omitempty"`
	Calibrating         bool                   `protobuf:"varint,7,opt,name=calibrating,proto3" json:"calibrating,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JonGuiDataCompass) Reset() {
	*x = JonGuiDataCompass{}
	mi := &file_jon_shared_data_compass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JonGuiDataCompass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JonGuiDataCompass) ProtoMessage() {}

func (x *JonGuiDataCompass) ProtoReflect() protoreflect.Message {
	mi := &file_jon_shared_data_compass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JonGuiDataCompass.ProtoReflect.Descriptor instead.
func (*JonGuiDataCompass) Descriptor() ([]byte, []int) {
	return file_jon_shared_data_compass_proto_rawDescGZIP(), []int{0}
}

func (x *JonGuiDataCompass) GetAzimuth() float64 {
	if x != nil {
		return x.Azimuth
	}
	return 0
}

func (x *JonGuiDataCompass) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *JonGuiDataCompass) GetBank() float64 {
	if x != nil {
		return x.Bank
	}
	return 0
}

func (x *JonGuiDataCompass) GetOffsetAzimuth() float64 {
	if x != nil {
		return x.OffsetAzimuth
	}
	return 0
}

func (x *JonGuiDataCompass) GetOffsetElevation() float64 {
	if x != nil {
		return x.OffsetElevation
	}
	return 0
}

func (x *JonGuiDataCompass) GetMagneticDeclination() float64 {
	if x != nil {
		return x.MagneticDeclination
	}
	return 0
}

func (x *JonGuiDataCompass) GetCalibrating() bool {
	if x != nil {
		return x.Calibrating
	}
	return false
}

var File_jon_shared_data_compass_proto protoreflect.FileDescriptor

const file_jon_shared_data_compass_proto_rawDesc = "" +
	"\n" +
	"\x1djon_shared_data_compass.proto\x12\x03ser\x1a\x1bbuf/validate/validate.proto\"\xc4\x04\n" +
	"\x11JonGuiDataCompass\x12U\n" +
	"\aazimuth\x18\x01 \x01(\x01B;\xbaH8\x126I\x00\x00\x00\x00\x00\x00\x00\x00I\x00\x00\x00\x00\x00\xa0V@I\x00\x00\x00\x00\x00\x80f@I\x00\x00\x00\x00\x00\xe0p@\x11\x00\x00\x00\x00\x00\x80v@)\x00\x00\x00\x00\x00\x00\x00\x00R\aazimuth\x12P\n" +
	"\televation\x18\x02 \x01(\x01B2\xbaH/\x12-I\x00\x00\x00\x00\x00\x80F\xc0I\x00\x00\x00\x00\x00\x00\x00\x00I\x00\x00\x00\x00\x00\x80F@\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\televation\x12F\n" +
	"\x04bank\x18\x03 \x01(\x01B2\xbaH/\x12-I\x00\x00\x00\x00\x00\x80V\xc0I\x00\x00\x00\x00\x00\x00\x00\x00I\x00\x00\x00\x00\x00\x80V@\x11\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x04bank\x12X\n" +
	"\roffsetAzimuth\x18\x04 \x01(\x01B2\xbaH/\x12-I\x00\x00\x00\x00\x00\x80F\xc0I\x00\x00\x00\x00\x00\x00\x00\x00I\x00\x00\x00\x00\x00\x80F@\x11\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\roffsetAzimuth\x12\\\n" +
	"\x0foffsetElevation\x18\x05 \x01(\x01B2\xbaH/\x12-I\x00\x00\x00\x00\x00\x00>\xc0I\x00\x00\x00\x00\x00\x00\x00\x00I\x00\x00\x00\x00\x00\x00>@\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x0foffsetElevation\x12d\n" +
	"\x13magneticDeclination\x18\x06 \x01(\x01B2\xbaH/\x12-I\x00\x00\x00\x00\x00\x00.\xc0I\x00\x00\x00\x00\x00\x00\x00\x00I\x00\x00\x00\x00\x00\x00.@\x11\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x13magneticDeclination\x12 \n" +
	"\vcalibrating\x18\a \x01(\bR\vcalibratingBOZMgit-codecommit.eu-central-1.amazonaws.com/v1/repos/jettison/jonp/data/compassb\x06proto3"

var (
	file_jon_shared_data_compass_proto_rawDescOnce sync.Once
	file_jon_shared_data_compass_proto_rawDescData []byte
)

func file_jon_shared_data_compass_proto_rawDescGZIP() []byte {
	file_jon_shared_data_compass_proto_rawDescOnce.Do(func() {
		file_jon_shared_data_compass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jon_shared_data_compass_proto_rawDesc), len(file_jon_shared_data_compass_proto_rawDesc)))
	})
	return file_jon_shared_data_compass_proto_rawDescData
}

var file_jon_shared_data_compass_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jon_shared_data_compass_proto_goTypes = []any{
	(*JonGuiDataCompass)(nil), // 0: ser.JonGuiDataCompass
}
var file_jon_shared_data_compass_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jon_shared_data_compass_proto_init() }
func file_jon_shared_data_compass_proto_init() {
	if File_jon_shared_data_compass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jon_shared_data_compass_proto_rawDesc), len(file_jon_shared_data_compass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jon_shared_data_compass_proto_goTypes,
		DependencyIndexes: file_jon_shared_data_compass_proto_depIdxs,
		MessageInfos:      file_jon_shared_data_compass_proto_msgTypes,
	}.Build()
	File_jon_shared_data_compass_proto = out.File
	file_jon_shared_data_compass_proto_goTypes = nil
	file_jon_shared_data_compass_proto_depIdxs = nil
}
