#ifndef FONTS_H
#define FONTS_H
/**
 * Custom font declarations for military/tactical theme.
 *
 * B612Mono-Bold: body/data text (aviation-grade monospace)
 * Orbitron-Bold: headings (futuristic display font)
 *
 * Generated by lv_font_conv — see tools/gen_fonts.sh
 */
#include "lvgl.h"
LV_FONT_DECLARE(font_b612mono_bold_12);
LV_FONT_DECLARE(font_b612mono_bold_14);
LV_FONT_DECLARE(font_b612mono_bold_16);
LV_FONT_DECLARE(font_b612mono_bold_18);
LV_FONT_DECLARE(font_b612mono_bold_20);
LV_FONT_DECLARE(font_orbitron_bold_22);
LV_FONT_DECLARE(font_orbitron_bold_28);
LV_FONT_DECLARE(font_orbitron_bold_32);
#endif
/* FONTS_H */
