# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jon_shared_data_drive.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'jon_shared_data_drive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jon_shared_data_types_pb2 as jon__shared__data__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bjon_shared_data_drive.proto\x12\x03ser\x1a\x1bjon_shared_data_types.proto\"\x85\x02\n\x0fJonGuiDataDrive\x12,\n\x07program\x18\x01 \x01(\x0e\x32\x1b.ser.JonGuiDataDriveProgram\x12(\n\x05state\x18\x02 \x01(\x0e\x32\x19.ser.JonGuiDataDriveState\x12\r\n\x05phase\x18\x03 \x01(\x05\x12\x12\n\nerror_code\x18\x04 \x01(\x05\x12\x11\n\tpoi_index\x18\x05 \x01(\x05\x12\x18\n\x10park_in_progress\x18\x06 \x01(\x08\x12\x19\n\x11tables_generation\x18\x07 \x01(\r\x12\x14\n\x0cwasm_version\x18\x08 \x01(\x05\x12\x19\n\x11rejected_commands\x18\t \x01(\rBMZKgit-codecommit.eu-central-1.amazonaws.com/v1/repos/jettison/jonp/data/driveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jon_shared_data_drive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgit-codecommit.eu-central-1.amazonaws.com/v1/repos/jettison/jonp/data/drive'
  _globals['_JONGUIDATADRIVE']._serialized_start=66
  _globals['_JONGUIDATADRIVE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
