/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_UI_UI_UI_AST_PB_H_INCLUDED
#define PB_UI_UI_UI_AST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Subject type — LVGL 9.2 supports INT, STRING, POINTER, COLOR, GROUP.
 We expose INT and STRING; others are renderer-internal. */
typedef enum _ui_SubjectType {
    ui_SubjectType_SUBJECT_INT = 0,
    ui_SubjectType_SUBJECT_STRING = 1
} ui_SubjectType;

typedef enum _ui_WidgetType {
    ui_WidgetType_WIDGET_OBJ = 0,
    ui_WidgetType_WIDGET_BUTTON = 1,
    ui_WidgetType_WIDGET_LABEL = 2,
    ui_WidgetType_WIDGET_SLIDER = 3,
    ui_WidgetType_WIDGET_IMAGE = 4,
    ui_WidgetType_WIDGET_ARC = 5,
    ui_WidgetType_WIDGET_BAR = 6,
    ui_WidgetType_WIDGET_SWITCH = 7,
    ui_WidgetType_WIDGET_CHECKBOX = 8,
    ui_WidgetType_WIDGET_DROPDOWN = 9,
    ui_WidgetType_WIDGET_ROLLER = 10,
    ui_WidgetType_WIDGET_TEXTAREA = 11,
    ui_WidgetType_WIDGET_SPINBOX = 12,
    ui_WidgetType_WIDGET_SPINNER = 13,
    ui_WidgetType_WIDGET_LED = 14,
    ui_WidgetType_WIDGET_LINE = 15,
    ui_WidgetType_WIDGET_SCALE = 16,
    ui_WidgetType_WIDGET_BUTTONMATRIX = 17,
    ui_WidgetType_WIDGET_TABLE = 18
} ui_WidgetType;

/* Which LVGL event code triggers this event binding. */
typedef enum _ui_EventTrigger {
    ui_EventTrigger_TRIGGER_CLICKED = 0, /* LV_EVENT_CLICKED (default) */
    ui_EventTrigger_TRIGGER_VALUE_CHANGED = 1, /* LV_EVENT_VALUE_CHANGED */
    ui_EventTrigger_TRIGGER_LONG_PRESSED = 2 /* LV_EVENT_LONG_PRESSED */
} ui_EventTrigger;

/* Comparison operator for conditional visibility bindings. */
typedef enum _ui_CompareOp {
    ui_CompareOp_COMPARE_EQ = 0, /* show when subject == ref_value (native LVGL bind) */
    ui_CompareOp_COMPARE_NOT_EQ = 1, /* show when subject != ref_value (native LVGL bind) */
    ui_CompareOp_COMPARE_GT = 2, /* show when subject > ref_value  (custom observer) */
    ui_CompareOp_COMPARE_GTE = 3, /* show when subject >= ref_value (custom observer) */
    ui_CompareOp_COMPARE_LT = 4, /* show when subject < ref_value  (custom observer) */
    ui_CompareOp_COMPARE_LTE = 5 /* show when subject <= ref_value (custom observer) */
} ui_CompareOp;

typedef enum _ui_FlexFlow {
    ui_FlexFlow_FLEX_FLOW_NONE = 0,
    ui_FlexFlow_FLEX_FLOW_ROW = 1,
    ui_FlexFlow_FLEX_FLOW_COLUMN = 2,
    ui_FlexFlow_FLEX_FLOW_ROW_WRAP = 3,
    ui_FlexFlow_FLEX_FLOW_ROW_REVERSE = 4,
    ui_FlexFlow_FLEX_FLOW_ROW_WRAP_REVERSE = 5,
    ui_FlexFlow_FLEX_FLOW_COLUMN_WRAP = 6,
    ui_FlexFlow_FLEX_FLOW_COLUMN_REVERSE = 7,
    ui_FlexFlow_FLEX_FLOW_COLUMN_WRAP_REVERSE = 8
} ui_FlexFlow;

typedef enum _ui_FlexAlign {
    ui_FlexAlign_FLEX_ALIGN_START = 0,
    ui_FlexAlign_FLEX_ALIGN_END = 1,
    ui_FlexAlign_FLEX_ALIGN_CENTER = 2,
    ui_FlexAlign_FLEX_ALIGN_SPACE_EVENLY = 3,
    ui_FlexAlign_FLEX_ALIGN_SPACE_AROUND = 4,
    ui_FlexAlign_FLEX_ALIGN_SPACE_BETWEEN = 5
} ui_FlexAlign;

typedef enum _ui_GridAlign {
    ui_GridAlign_GRID_ALIGN_START = 0,
    ui_GridAlign_GRID_ALIGN_CENTER = 1,
    ui_GridAlign_GRID_ALIGN_END = 2,
    ui_GridAlign_GRID_ALIGN_STRETCH = 3,
    ui_GridAlign_GRID_ALIGN_SPACE_EVENLY = 4,
    ui_GridAlign_GRID_ALIGN_SPACE_AROUND = 5,
    ui_GridAlign_GRID_ALIGN_SPACE_BETWEEN = 6
} ui_GridAlign;

typedef enum _ui_TextAlign {
    ui_TextAlign_TEXT_ALIGN_AUTO = 0,
    ui_TextAlign_TEXT_ALIGN_LEFT = 1,
    ui_TextAlign_TEXT_ALIGN_CENTER = 2,
    ui_TextAlign_TEXT_ALIGN_RIGHT = 3
} ui_TextAlign;

typedef enum _ui_TextDecor {
    ui_TextDecor_TEXT_DECOR_NONE = 0,
    ui_TextDecor_TEXT_DECOR_UNDERLINE = 1,
    ui_TextDecor_TEXT_DECOR_STRIKETHROUGH = 2
} ui_TextDecor;

typedef enum _ui_BlendMode {
    ui_BlendMode_BLEND_MODE_NORMAL = 0,
    ui_BlendMode_BLEND_MODE_ADDITIVE = 1,
    ui_BlendMode_BLEND_MODE_SUBTRACTIVE = 2,
    ui_BlendMode_BLEND_MODE_MULTIPLY = 3
} ui_BlendMode;

typedef enum _ui_BaseDir {
    ui_BaseDir_BASE_DIR_LTR = 0,
    ui_BaseDir_BASE_DIR_RTL = 1,
    ui_BaseDir_BASE_DIR_AUTO = 2
} ui_BaseDir;

typedef enum _ui_GradDir {
    ui_GradDir_GRAD_DIR_NONE = 0,
    ui_GradDir_GRAD_DIR_VER = 1,
    ui_GradDir_GRAD_DIR_HOR = 2,
    ui_GradDir_GRAD_DIR_LINEAR = 3,
    ui_GradDir_GRAD_DIR_RADIAL = 4,
    ui_GradDir_GRAD_DIR_CONICAL = 5
} ui_GradDir;

typedef enum _ui_Dir {
    ui_Dir_DIR_NONE = 0,
    ui_Dir_DIR_LEFT = 1,
    ui_Dir_DIR_RIGHT = 2,
    ui_Dir_DIR_HOR = 3,
    ui_Dir_DIR_TOP = 4,
    ui_Dir_DIR_BOTTOM = 8,
    ui_Dir_DIR_VER = 12,
    ui_Dir_DIR_ALL = 15
} ui_Dir;

typedef enum _ui_Align {
    ui_Align_ALIGN_DEFAULT = 0,
    ui_Align_ALIGN_TOP_LEFT = 1,
    ui_Align_ALIGN_TOP_MID = 2,
    ui_Align_ALIGN_TOP_RIGHT = 3,
    ui_Align_ALIGN_BOTTOM_LEFT = 4,
    ui_Align_ALIGN_BOTTOM_MID = 5,
    ui_Align_ALIGN_BOTTOM_RIGHT = 6,
    ui_Align_ALIGN_LEFT_MID = 7,
    ui_Align_ALIGN_RIGHT_MID = 8,
    ui_Align_ALIGN_CENTER = 9,
    ui_Align_ALIGN_OUT_TOP_LEFT = 10,
    ui_Align_ALIGN_OUT_TOP_MID = 11,
    ui_Align_ALIGN_OUT_TOP_RIGHT = 12,
    ui_Align_ALIGN_OUT_BOTTOM_LEFT = 13,
    ui_Align_ALIGN_OUT_BOTTOM_MID = 14,
    ui_Align_ALIGN_OUT_BOTTOM_RIGHT = 15,
    ui_Align_ALIGN_OUT_LEFT_TOP = 16,
    ui_Align_ALIGN_OUT_LEFT_MID = 17,
    ui_Align_ALIGN_OUT_LEFT_BOTTOM = 18,
    ui_Align_ALIGN_OUT_RIGHT_TOP = 19,
    ui_Align_ALIGN_OUT_RIGHT_MID = 20,
    ui_Align_ALIGN_OUT_RIGHT_BOTTOM = 21
} ui_Align;

typedef enum _ui_BorderSide {
    ui_BorderSide_BORDER_SIDE_NONE = 0,
    ui_BorderSide_BORDER_SIDE_BOTTOM = 1,
    ui_BorderSide_BORDER_SIDE_TOP = 2,
    ui_BorderSide_BORDER_SIDE_LEFT = 4,
    ui_BorderSide_BORDER_SIDE_RIGHT = 8,
    ui_BorderSide_BORDER_SIDE_FULL = 15,
    ui_BorderSide_BORDER_SIDE_INTERNAL = 16
} ui_BorderSide;

typedef enum _ui_LabelLongMode {
    ui_LabelLongMode_LABEL_LONG_WRAP = 0,
    ui_LabelLongMode_LABEL_LONG_DOT = 1,
    ui_LabelLongMode_LABEL_LONG_SCROLL = 2,
    ui_LabelLongMode_LABEL_LONG_SCROLL_CIRCULAR = 3,
    ui_LabelLongMode_LABEL_LONG_CLIP = 4
} ui_LabelLongMode;

typedef enum _ui_BarMode {
    ui_BarMode_BAR_MODE_NORMAL = 0,
    ui_BarMode_BAR_MODE_SYMMETRICAL = 1,
    ui_BarMode_BAR_MODE_RANGE = 2
} ui_BarMode;

typedef enum _ui_ArcMode {
    ui_ArcMode_ARC_MODE_NORMAL = 0,
    ui_ArcMode_ARC_MODE_SYMMETRICAL = 1,
    ui_ArcMode_ARC_MODE_REVERSE = 2
} ui_ArcMode;

typedef enum _ui_RollerMode {
    ui_RollerMode_ROLLER_MODE_NORMAL = 0,
    ui_RollerMode_ROLLER_MODE_INFINITE = 1
} ui_RollerMode;

typedef enum _ui_ScaleMode {
    ui_ScaleMode_SCALE_MODE_HORIZONTAL_TOP = 0,
    ui_ScaleMode_SCALE_MODE_HORIZONTAL_BOTTOM = 1,
    ui_ScaleMode_SCALE_MODE_VERTICAL_LEFT = 2,
    ui_ScaleMode_SCALE_MODE_VERTICAL_RIGHT = 4,
    ui_ScaleMode_SCALE_MODE_ROUND_INNER = 8,
    ui_ScaleMode_SCALE_MODE_ROUND_OUTER = 16
} ui_ScaleMode;

typedef enum _ui_StylePropertyType {
    /* Existing 0-15 (backward-compatible wire format) */
    ui_StylePropertyType_PROP_BG_COLOR = 0,
    ui_StylePropertyType_PROP_BG_OPA = 1,
    ui_StylePropertyType_PROP_TEXT_COLOR = 2,
    ui_StylePropertyType_PROP_TEXT_FONT = 3,
    ui_StylePropertyType_PROP_BORDER_COLOR = 4,
    ui_StylePropertyType_PROP_BORDER_WIDTH = 5,
    ui_StylePropertyType_PROP_RADIUS = 6,
    ui_StylePropertyType_PROP_PAD_ALL = 7,
    ui_StylePropertyType_PROP_PAD_GAP = 8,
    ui_StylePropertyType_PROP_WIDTH = 9,
    ui_StylePropertyType_PROP_HEIGHT = 10,
    ui_StylePropertyType_PROP_SHADOW = 11,
    ui_StylePropertyType_PROP_PAD_HOR = 12,
    ui_StylePropertyType_PROP_PAD_VER = 13,
    ui_StylePropertyType_PROP_MARGIN_ALL = 14,
    ui_StylePropertyType_PROP_BORDER_OPA = 15,
    /* Size (16-20) */
    ui_StylePropertyType_PROP_MIN_WIDTH = 16,
    ui_StylePropertyType_PROP_MAX_WIDTH = 17,
    ui_StylePropertyType_PROP_MIN_HEIGHT = 18,
    ui_StylePropertyType_PROP_MAX_HEIGHT = 19,
    ui_StylePropertyType_PROP_LENGTH = 20,
    /* Position (21-23) */
    ui_StylePropertyType_PROP_X = 21,
    ui_StylePropertyType_PROP_Y = 22,
    ui_StylePropertyType_PROP_ALIGN = 23,
    /* Transform (24-34) */
    ui_StylePropertyType_PROP_TRANSFORM_WIDTH = 24,
    ui_StylePropertyType_PROP_TRANSFORM_HEIGHT = 25,
    ui_StylePropertyType_PROP_TRANSLATE_X = 26,
    ui_StylePropertyType_PROP_TRANSLATE_Y = 27,
    ui_StylePropertyType_PROP_SCALE_X = 28,
    ui_StylePropertyType_PROP_SCALE_Y = 29,
    ui_StylePropertyType_PROP_ROTATION = 30,
    ui_StylePropertyType_PROP_PIVOT_X = 31,
    ui_StylePropertyType_PROP_PIVOT_Y = 32,
    ui_StylePropertyType_PROP_SKEW_X = 33,
    ui_StylePropertyType_PROP_SKEW_Y = 34,
    /* Padding individual (35-40) */
    ui_StylePropertyType_PROP_PAD_TOP = 35,
    ui_StylePropertyType_PROP_PAD_BOTTOM = 36,
    ui_StylePropertyType_PROP_PAD_LEFT = 37,
    ui_StylePropertyType_PROP_PAD_RIGHT = 38,
    ui_StylePropertyType_PROP_PAD_ROW = 39,
    ui_StylePropertyType_PROP_PAD_COLUMN = 40,
    /* Margin individual (41-44) */
    ui_StylePropertyType_PROP_MARGIN_TOP = 41,
    ui_StylePropertyType_PROP_MARGIN_BOTTOM = 42,
    ui_StylePropertyType_PROP_MARGIN_LEFT = 43,
    ui_StylePropertyType_PROP_MARGIN_RIGHT = 44,
    /* Background extended (45-55) */
    ui_StylePropertyType_PROP_BG_GRAD_COLOR = 45,
    ui_StylePropertyType_PROP_BG_GRAD_DIR = 46,
    ui_StylePropertyType_PROP_BG_MAIN_STOP = 47,
    ui_StylePropertyType_PROP_BG_GRAD_STOP = 48,
    ui_StylePropertyType_PROP_BG_MAIN_OPA = 49,
    ui_StylePropertyType_PROP_BG_GRAD_OPA = 50,
    ui_StylePropertyType_PROP_BG_IMAGE_SRC = 51,
    ui_StylePropertyType_PROP_BG_IMAGE_OPA = 52,
    ui_StylePropertyType_PROP_BG_IMAGE_RECOLOR = 53,
    ui_StylePropertyType_PROP_BG_IMAGE_RECOLOR_OPA = 54,
    ui_StylePropertyType_PROP_BG_IMAGE_TILED = 55,
    /* Border extended (56-57) */
    ui_StylePropertyType_PROP_BORDER_SIDE = 56,
    ui_StylePropertyType_PROP_BORDER_POST = 57,
    /* Outline (58-61) */
    ui_StylePropertyType_PROP_OUTLINE_WIDTH = 58,
    ui_StylePropertyType_PROP_OUTLINE_COLOR = 59,
    ui_StylePropertyType_PROP_OUTLINE_OPA = 60,
    ui_StylePropertyType_PROP_OUTLINE_PAD = 61,
    /* Shadow individual (62-67) */
    ui_StylePropertyType_PROP_SHADOW_WIDTH = 62,
    ui_StylePropertyType_PROP_SHADOW_OFFSET_X = 63,
    ui_StylePropertyType_PROP_SHADOW_OFFSET_Y = 64,
    ui_StylePropertyType_PROP_SHADOW_SPREAD = 65,
    ui_StylePropertyType_PROP_SHADOW_COLOR = 66,
    ui_StylePropertyType_PROP_SHADOW_OPA = 67,
    /* Image style (68-70) */
    ui_StylePropertyType_PROP_IMAGE_OPA = 68,
    ui_StylePropertyType_PROP_IMAGE_RECOLOR = 69,
    ui_StylePropertyType_PROP_IMAGE_RECOLOR_OPA = 70,
    /* Line style (71-76) */
    ui_StylePropertyType_PROP_LINE_WIDTH = 71,
    ui_StylePropertyType_PROP_LINE_DASH_WIDTH = 72,
    ui_StylePropertyType_PROP_LINE_DASH_GAP = 73,
    ui_StylePropertyType_PROP_LINE_ROUNDED = 74,
    ui_StylePropertyType_PROP_LINE_COLOR = 75,
    ui_StylePropertyType_PROP_LINE_OPA = 76,
    /* Arc style (77-80) */
    ui_StylePropertyType_PROP_ARC_WIDTH = 77,
    ui_StylePropertyType_PROP_ARC_ROUNDED = 78,
    ui_StylePropertyType_PROP_ARC_COLOR = 79,
    ui_StylePropertyType_PROP_ARC_OPA = 80,
    /* Text extended (81-85) */
    ui_StylePropertyType_PROP_TEXT_OPA = 81,
    ui_StylePropertyType_PROP_TEXT_LETTER_SPACE = 82,
    ui_StylePropertyType_PROP_TEXT_LINE_SPACE = 83,
    ui_StylePropertyType_PROP_TEXT_DECOR = 84,
    ui_StylePropertyType_PROP_TEXT_ALIGN = 85,
    /* Misc (86-93) */
    ui_StylePropertyType_PROP_CLIP_CORNER = 86,
    ui_StylePropertyType_PROP_OPA = 87,
    ui_StylePropertyType_PROP_OPA_LAYERED = 88,
    ui_StylePropertyType_PROP_COLOR_FILTER_OPA = 89,
    ui_StylePropertyType_PROP_ANIM_DURATION = 90,
    ui_StylePropertyType_PROP_BLEND_MODE = 91,
    ui_StylePropertyType_PROP_BASE_DIR = 92,
    ui_StylePropertyType_PROP_ROTARY_SENSITIVITY = 93,
    /* Flex (94-98) */
    ui_StylePropertyType_PROP_FLEX_FLOW = 94,
    ui_StylePropertyType_PROP_FLEX_MAIN_PLACE = 95,
    ui_StylePropertyType_PROP_FLEX_CROSS_PLACE = 96,
    ui_StylePropertyType_PROP_FLEX_TRACK_PLACE = 97,
    ui_StylePropertyType_PROP_FLEX_GROW = 98,
    /* Grid cell (99-106) */
    ui_StylePropertyType_PROP_GRID_COLUMN_ALIGN = 99,
    ui_StylePropertyType_PROP_GRID_ROW_ALIGN = 100,
    ui_StylePropertyType_PROP_GRID_CELL_COLUMN_POS = 101,
    ui_StylePropertyType_PROP_GRID_CELL_X_ALIGN = 102,
    ui_StylePropertyType_PROP_GRID_CELL_COLUMN_SPAN = 103,
    ui_StylePropertyType_PROP_GRID_CELL_ROW_POS = 104,
    ui_StylePropertyType_PROP_GRID_CELL_Y_ALIGN = 105,
    ui_StylePropertyType_PROP_GRID_CELL_ROW_SPAN = 106
} ui_StylePropertyType;

/* Struct definitions */
/* Declaration of a reactive subject (lives in Screen, initialized at load time) */
typedef struct _ui_SubjectDeclaration {
    pb_callback_t name; /* unique identifier, e.g. "zoom_level" */
    ui_SubjectType type;
    pb_size_t which_initial;
    union {
        int32_t int_initial; /* default value for INT subjects */
        pb_callback_t string_initial; /* default value for STRING subjects */
    } initial;
} ui_SubjectDeclaration;

/* Host → WASM state update (decoded by controls_update_state) */
typedef struct _ui_StateUpdate {
    pb_callback_t values;
} ui_StateUpdate;

/* A single subject value in a state update */
typedef struct _ui_SubjectValue {
    pb_callback_t name;
    pb_size_t which_value;
    union {
        int32_t int_value;
        pb_callback_t string_value;
    } value;
} ui_SubjectValue;

typedef struct _ui_WidgetNode_BindingsEntry {
    pb_callback_t key;
    pb_callback_t value;
} ui_WidgetNode_BindingsEntry;

typedef struct _ui_WidgetNode_BindFormatsEntry {
    pb_callback_t key;
    pb_callback_t value;
} ui_WidgetNode_BindFormatsEntry;

typedef struct _ui_ObjProps {
    char dummy_field;
} ui_ObjProps;

typedef struct _ui_ButtonProps {
    char dummy_field;
} ui_ButtonProps;

typedef struct _ui_LabelProps {
    ui_LabelLongMode long_mode;
} ui_LabelProps;

typedef struct _ui_SliderProps {
    int32_t min_value;
    int32_t max_value;
    int32_t value;
    ui_BarMode mode;
} ui_SliderProps;

typedef struct _ui_ImageProps {
    pb_callback_t src;
} ui_ImageProps;

typedef struct _ui_ArcProps {
    uint32_t start_angle;
    uint32_t end_angle;
    uint32_t bg_start_angle;
    uint32_t bg_end_angle;
    int32_t rotation;
    ui_ArcMode mode;
    int32_t min_value;
    int32_t max_value;
    int32_t value;
} ui_ArcProps;

typedef struct _ui_BarProps {
    int32_t min_value;
    int32_t max_value;
    int32_t value;
    int32_t start_value;
    ui_BarMode mode;
} ui_BarProps;

typedef struct _ui_SwitchProps {
    bool checked;
} ui_SwitchProps;

typedef struct _ui_CheckboxProps {
    bool checked;
} ui_CheckboxProps;

typedef struct _ui_DropdownProps {
    pb_callback_t options;
    uint32_t selected;
    ui_Dir direction;
} ui_DropdownProps;

typedef struct _ui_RollerProps {
    pb_callback_t options;
    uint32_t selected;
    uint32_t visible_row_count;
    ui_RollerMode mode;
} ui_RollerProps;

typedef struct _ui_TextareaProps {
    pb_callback_t placeholder;
    uint32_t max_length;
    bool one_line;
    bool password_mode;
} ui_TextareaProps;

typedef struct _ui_SpinboxProps {
    int32_t min_value;
    int32_t max_value;
    int32_t value;
    int32_t step;
    uint32_t digit_count;
    uint32_t separator_position;
} ui_SpinboxProps;

typedef struct _ui_SpinnerProps {
    uint32_t spin_time;
    uint32_t arc_length;
} ui_SpinnerProps;

typedef struct _ui_LineProps {
    pb_callback_t points;
    bool y_invert;
} ui_LineProps;

typedef struct _ui_ScaleProps {
    ui_ScaleMode mode;
    uint32_t total_tick_count;
    uint32_t major_tick_every;
    bool label_show;
    int32_t min_value;
    int32_t max_value;
    int32_t rotation;
    uint32_t angle_range;
} ui_ScaleProps;

typedef struct _ui_ButtonMatrixProps {
    pb_callback_t map_str;
    bool one_check;
} ui_ButtonMatrixProps;

typedef struct _ui_TableProps {
    uint32_t row_count;
    uint32_t column_count;
} ui_TableProps;

typedef struct _ui_Point {
    int32_t x;
    int32_t y;
} ui_Point;

typedef struct _ui_EventBinding {
    pb_callback_t name; /* event keyword — IS the command identifier */
    ui_EventTrigger trigger; /* which LVGL event fires this (default: CLICKED) */
    int32_t int_value; /* static int payload */
    bool include_widget_value; /* inject widget's current value as int_value */
    pb_callback_t set_subject; /* local subject to mutate (empty = host event) */
    int32_t set_value; /* value to set on subject */
    bool toggle; /* flip 0↔1 instead of set_value */
    bool notify_host; /* also send to host when mutating subject */
} ui_EventBinding;

/* Conditional visibility — show/hide widget based on subject value comparison. */
typedef struct _ui_VisibilityBinding {
    pb_callback_t subject; /* subject name to observe */
    int32_t ref_value; /* reference value for comparison */
    ui_CompareOp compare; /* comparison operator (default: EQ) */
} ui_VisibilityBinding;

typedef struct _ui_Layout {
    ui_FlexFlow flow;
    ui_FlexAlign main_place;
    ui_FlexAlign cross_place;
    ui_FlexAlign track_place;
} ui_Layout;

/* A group of style variants for one LVGL state selector.
 state_selector encodes LV_PART_MAIN (0x0), LV_PART_MAIN | LV_STATE_PRESSED (0x20), etc. */
typedef struct _ui_StyleGroup {
    uint32_t state_selector;
    pb_callback_t variants; /* exactly 8 entries (composite indices 0-7) */
} ui_StyleGroup;

/* A fully-resolved style: all token refs are resolved to concrete LVGL values. */
typedef struct _ui_ResolvedStyle {
    pb_callback_t properties;
} ui_ResolvedStyle;

typedef struct _ui_Color {
    uint32_t r; /* 0-255 */
    uint32_t g;
    uint32_t b;
} ui_Color;

typedef struct _ui_LedProps {
    bool has_color;
    ui_Color color;
    uint32_t brightness;
} ui_LedProps;

/* A node in the widget tree (recursive). */
typedef struct _ui_WidgetNode {
    ui_WidgetType type;
    /* Position (optional — 0,0 = use layout) */
    int32_t x;
    int32_t y;
    /* Static text (labels, checkbox, textarea, button) */
    pb_callback_t text;
    /* Subject data bindings (key = LVGL property, value = subject name) */
    pb_callback_t bindings;
    /* Event binding (what command to emit on click) */
    bool has_event;
    ui_EventBinding event;
    /* Layout flow */
    bool has_layout;
    ui_Layout layout;
    /* Children */
    pb_callback_t children;
    /* Style groups: default + per-state, each with 8 composite variants.
 Ordered: */
    pb_callback_t style_groups;
    pb_size_t which_widget_props;
    union {
        ui_ObjProps obj_props;
        ui_ButtonProps button_props;
        ui_LabelProps label_props;
        ui_SliderProps slider_props;
        ui_ImageProps image_props;
        ui_ArcProps arc_props;
        ui_BarProps bar_props;
        ui_SwitchProps switch_props;
        ui_CheckboxProps checkbox_props;
        ui_DropdownProps dropdown_props;
        ui_RollerProps roller_props;
        ui_TextareaProps textarea_props;
        ui_SpinboxProps spinbox_props;
        ui_SpinnerProps spinner_props;
        ui_LedProps led_props;
        ui_LineProps line_props;
        ui_ScaleProps scale_props;
        ui_ButtonMatrixProps buttonmatrix_props;
        ui_TableProps table_props;
    } widget_props;
    /* Conditional visibility binding (show/hide based on subject value) */
    bool has_visibility;
    ui_VisibilityBinding visibility;
    /* Format strings for bound text (key = binding key, value = printf format) */
    pb_callback_t bind_formats;
} ui_WidgetNode;

/* A complete UI screen — root message pushed via controls_load_ui(). */
typedef struct _ui_Screen {
    /* `optional` is required so nanopb generates `has_root` for presence
 checking in proto3 (submessage fields do NOT get `has_*` by default). */
    bool has_root;
    ui_WidgetNode root;
    pb_callback_t subjects; /* reactive subject declarations */
} ui_Screen;

typedef struct _ui_ShadowBundle {
    uint32_t width;
    int32_t offset_x;
    int32_t offset_y;
    uint32_t spread;
    uint32_t opa;
} ui_ShadowBundle;

/* A single LVGL style property with its resolved value. */
typedef struct _ui_StyleProperty {
    ui_StylePropertyType type;
    pb_size_t which_value;
    union {
        uint32_t uint_value; /* pixels, opacity, enum values */
        int32_t int_value; /* signed values (width, height, padding, coords) */
        ui_Color color_value; /* resolved RGB */
        pb_callback_t string_value; /* font C symbol name, image source path */
        ui_ShadowBundle shadow_value;
    } value;
} ui_StyleProperty;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ui_SubjectType_MIN ui_SubjectType_SUBJECT_INT
#define _ui_SubjectType_MAX ui_SubjectType_SUBJECT_STRING
#define _ui_SubjectType_ARRAYSIZE ((ui_SubjectType)(ui_SubjectType_SUBJECT_STRING+1))

#define _ui_WidgetType_MIN ui_WidgetType_WIDGET_OBJ
#define _ui_WidgetType_MAX ui_WidgetType_WIDGET_TABLE
#define _ui_WidgetType_ARRAYSIZE ((ui_WidgetType)(ui_WidgetType_WIDGET_TABLE+1))

#define _ui_EventTrigger_MIN ui_EventTrigger_TRIGGER_CLICKED
#define _ui_EventTrigger_MAX ui_EventTrigger_TRIGGER_LONG_PRESSED
#define _ui_EventTrigger_ARRAYSIZE ((ui_EventTrigger)(ui_EventTrigger_TRIGGER_LONG_PRESSED+1))

#define _ui_CompareOp_MIN ui_CompareOp_COMPARE_EQ
#define _ui_CompareOp_MAX ui_CompareOp_COMPARE_LTE
#define _ui_CompareOp_ARRAYSIZE ((ui_CompareOp)(ui_CompareOp_COMPARE_LTE+1))

#define _ui_FlexFlow_MIN ui_FlexFlow_FLEX_FLOW_NONE
#define _ui_FlexFlow_MAX ui_FlexFlow_FLEX_FLOW_COLUMN_WRAP_REVERSE
#define _ui_FlexFlow_ARRAYSIZE ((ui_FlexFlow)(ui_FlexFlow_FLEX_FLOW_COLUMN_WRAP_REVERSE+1))

#define _ui_FlexAlign_MIN ui_FlexAlign_FLEX_ALIGN_START
#define _ui_FlexAlign_MAX ui_FlexAlign_FLEX_ALIGN_SPACE_BETWEEN
#define _ui_FlexAlign_ARRAYSIZE ((ui_FlexAlign)(ui_FlexAlign_FLEX_ALIGN_SPACE_BETWEEN+1))

#define _ui_GridAlign_MIN ui_GridAlign_GRID_ALIGN_START
#define _ui_GridAlign_MAX ui_GridAlign_GRID_ALIGN_SPACE_BETWEEN
#define _ui_GridAlign_ARRAYSIZE ((ui_GridAlign)(ui_GridAlign_GRID_ALIGN_SPACE_BETWEEN+1))

#define _ui_TextAlign_MIN ui_TextAlign_TEXT_ALIGN_AUTO
#define _ui_TextAlign_MAX ui_TextAlign_TEXT_ALIGN_RIGHT
#define _ui_TextAlign_ARRAYSIZE ((ui_TextAlign)(ui_TextAlign_TEXT_ALIGN_RIGHT+1))

#define _ui_TextDecor_MIN ui_TextDecor_TEXT_DECOR_NONE
#define _ui_TextDecor_MAX ui_TextDecor_TEXT_DECOR_STRIKETHROUGH
#define _ui_TextDecor_ARRAYSIZE ((ui_TextDecor)(ui_TextDecor_TEXT_DECOR_STRIKETHROUGH+1))

#define _ui_BlendMode_MIN ui_BlendMode_BLEND_MODE_NORMAL
#define _ui_BlendMode_MAX ui_BlendMode_BLEND_MODE_MULTIPLY
#define _ui_BlendMode_ARRAYSIZE ((ui_BlendMode)(ui_BlendMode_BLEND_MODE_MULTIPLY+1))

#define _ui_BaseDir_MIN ui_BaseDir_BASE_DIR_LTR
#define _ui_BaseDir_MAX ui_BaseDir_BASE_DIR_AUTO
#define _ui_BaseDir_ARRAYSIZE ((ui_BaseDir)(ui_BaseDir_BASE_DIR_AUTO+1))

#define _ui_GradDir_MIN ui_GradDir_GRAD_DIR_NONE
#define _ui_GradDir_MAX ui_GradDir_GRAD_DIR_CONICAL
#define _ui_GradDir_ARRAYSIZE ((ui_GradDir)(ui_GradDir_GRAD_DIR_CONICAL+1))

#define _ui_Dir_MIN ui_Dir_DIR_NONE
#define _ui_Dir_MAX ui_Dir_DIR_ALL
#define _ui_Dir_ARRAYSIZE ((ui_Dir)(ui_Dir_DIR_ALL+1))

#define _ui_Align_MIN ui_Align_ALIGN_DEFAULT
#define _ui_Align_MAX ui_Align_ALIGN_OUT_RIGHT_BOTTOM
#define _ui_Align_ARRAYSIZE ((ui_Align)(ui_Align_ALIGN_OUT_RIGHT_BOTTOM+1))

#define _ui_BorderSide_MIN ui_BorderSide_BORDER_SIDE_NONE
#define _ui_BorderSide_MAX ui_BorderSide_BORDER_SIDE_INTERNAL
#define _ui_BorderSide_ARRAYSIZE ((ui_BorderSide)(ui_BorderSide_BORDER_SIDE_INTERNAL+1))

#define _ui_LabelLongMode_MIN ui_LabelLongMode_LABEL_LONG_WRAP
#define _ui_LabelLongMode_MAX ui_LabelLongMode_LABEL_LONG_CLIP
#define _ui_LabelLongMode_ARRAYSIZE ((ui_LabelLongMode)(ui_LabelLongMode_LABEL_LONG_CLIP+1))

#define _ui_BarMode_MIN ui_BarMode_BAR_MODE_NORMAL
#define _ui_BarMode_MAX ui_BarMode_BAR_MODE_RANGE
#define _ui_BarMode_ARRAYSIZE ((ui_BarMode)(ui_BarMode_BAR_MODE_RANGE+1))

#define _ui_ArcMode_MIN ui_ArcMode_ARC_MODE_NORMAL
#define _ui_ArcMode_MAX ui_ArcMode_ARC_MODE_REVERSE
#define _ui_ArcMode_ARRAYSIZE ((ui_ArcMode)(ui_ArcMode_ARC_MODE_REVERSE+1))

#define _ui_RollerMode_MIN ui_RollerMode_ROLLER_MODE_NORMAL
#define _ui_RollerMode_MAX ui_RollerMode_ROLLER_MODE_INFINITE
#define _ui_RollerMode_ARRAYSIZE ((ui_RollerMode)(ui_RollerMode_ROLLER_MODE_INFINITE+1))

#define _ui_ScaleMode_MIN ui_ScaleMode_SCALE_MODE_HORIZONTAL_TOP
#define _ui_ScaleMode_MAX ui_ScaleMode_SCALE_MODE_ROUND_OUTER
#define _ui_ScaleMode_ARRAYSIZE ((ui_ScaleMode)(ui_ScaleMode_SCALE_MODE_ROUND_OUTER+1))

#define _ui_StylePropertyType_MIN ui_StylePropertyType_PROP_BG_COLOR
#define _ui_StylePropertyType_MAX ui_StylePropertyType_PROP_GRID_CELL_ROW_SPAN
#define _ui_StylePropertyType_ARRAYSIZE ((ui_StylePropertyType)(ui_StylePropertyType_PROP_GRID_CELL_ROW_SPAN+1))

#define ui_SubjectDeclaration_type_ENUMTYPE ui_SubjectType




#define ui_WidgetNode_type_ENUMTYPE ui_WidgetType





#define ui_LabelProps_long_mode_ENUMTYPE ui_LabelLongMode

#define ui_SliderProps_mode_ENUMTYPE ui_BarMode


#define ui_ArcProps_mode_ENUMTYPE ui_ArcMode

#define ui_BarProps_mode_ENUMTYPE ui_BarMode



#define ui_DropdownProps_direction_ENUMTYPE ui_Dir

#define ui_RollerProps_mode_ENUMTYPE ui_RollerMode






#define ui_ScaleProps_mode_ENUMTYPE ui_ScaleMode




#define ui_EventBinding_trigger_ENUMTYPE ui_EventTrigger

#define ui_VisibilityBinding_compare_ENUMTYPE ui_CompareOp

#define ui_Layout_flow_ENUMTYPE ui_FlexFlow
#define ui_Layout_main_place_ENUMTYPE ui_FlexAlign
#define ui_Layout_cross_place_ENUMTYPE ui_FlexAlign
#define ui_Layout_track_place_ENUMTYPE ui_FlexAlign



#define ui_StyleProperty_type_ENUMTYPE ui_StylePropertyType




/* Initializer values for message structs */
#define ui_SubjectDeclaration_init_default       {{{NULL}, NULL}, _ui_SubjectType_MIN, 0, {0}}
#define ui_StateUpdate_init_default              {{{NULL}, NULL}}
#define ui_SubjectValue_init_default             {{{NULL}, NULL}, 0, {0}}
#define ui_Screen_init_default                   {false, ui_WidgetNode_init_default, {{NULL}, NULL}}
#define ui_WidgetNode_init_default               {_ui_WidgetType_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, ui_EventBinding_init_default, false, ui_Layout_init_default, {{NULL}, NULL}, {{NULL}, NULL}, 0, {ui_ObjProps_init_default}, false, ui_VisibilityBinding_init_default, {{NULL}, NULL}}
#define ui_WidgetNode_BindingsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define ui_WidgetNode_BindFormatsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define ui_ObjProps_init_default                 {0}
#define ui_ButtonProps_init_default              {0}
#define ui_LabelProps_init_default               {_ui_LabelLongMode_MIN}
#define ui_SliderProps_init_default              {0, 0, 0, _ui_BarMode_MIN}
#define ui_ImageProps_init_default               {{{NULL}, NULL}}
#define ui_ArcProps_init_default                 {0, 0, 0, 0, 0, _ui_ArcMode_MIN, 0, 0, 0}
#define ui_BarProps_init_default                 {0, 0, 0, 0, _ui_BarMode_MIN}
#define ui_SwitchProps_init_default              {0}
#define ui_CheckboxProps_init_default            {0}
#define ui_DropdownProps_init_default            {{{NULL}, NULL}, 0, _ui_Dir_MIN}
#define ui_RollerProps_init_default              {{{NULL}, NULL}, 0, 0, _ui_RollerMode_MIN}
#define ui_TextareaProps_init_default            {{{NULL}, NULL}, 0, 0, 0}
#define ui_SpinboxProps_init_default             {0, 0, 0, 0, 0, 0}
#define ui_SpinnerProps_init_default             {0, 0}
#define ui_LedProps_init_default                 {false, ui_Color_init_default, 0}
#define ui_LineProps_init_default                {{{NULL}, NULL}, 0}
#define ui_ScaleProps_init_default               {_ui_ScaleMode_MIN, 0, 0, 0, 0, 0, 0, 0}
#define ui_ButtonMatrixProps_init_default        {{{NULL}, NULL}, 0}
#define ui_TableProps_init_default               {0, 0}
#define ui_Point_init_default                    {0, 0}
#define ui_EventBinding_init_default             {{{NULL}, NULL}, _ui_EventTrigger_MIN, 0, 0, {{NULL}, NULL}, 0, 0, 0}
#define ui_VisibilityBinding_init_default        {{{NULL}, NULL}, 0, _ui_CompareOp_MIN}
#define ui_Layout_init_default                   {_ui_FlexFlow_MIN, _ui_FlexAlign_MIN, _ui_FlexAlign_MIN, _ui_FlexAlign_MIN}
#define ui_StyleGroup_init_default               {0, {{NULL}, NULL}}
#define ui_ResolvedStyle_init_default            {{{NULL}, NULL}}
#define ui_StyleProperty_init_default            {_ui_StylePropertyType_MIN, 0, {0}}
#define ui_Color_init_default                    {0, 0, 0}
#define ui_ShadowBundle_init_default             {0, 0, 0, 0, 0}
#define ui_SubjectDeclaration_init_zero          {{{NULL}, NULL}, _ui_SubjectType_MIN, 0, {0}}
#define ui_StateUpdate_init_zero                 {{{NULL}, NULL}}
#define ui_SubjectValue_init_zero                {{{NULL}, NULL}, 0, {0}}
#define ui_Screen_init_zero                      {false, ui_WidgetNode_init_zero, {{NULL}, NULL}}
#define ui_WidgetNode_init_zero                  {_ui_WidgetType_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, ui_EventBinding_init_zero, false, ui_Layout_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, 0, {ui_ObjProps_init_zero}, false, ui_VisibilityBinding_init_zero, {{NULL}, NULL}}
#define ui_WidgetNode_BindingsEntry_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}}
#define ui_WidgetNode_BindFormatsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define ui_ObjProps_init_zero                    {0}
#define ui_ButtonProps_init_zero                 {0}
#define ui_LabelProps_init_zero                  {_ui_LabelLongMode_MIN}
#define ui_SliderProps_init_zero                 {0, 0, 0, _ui_BarMode_MIN}
#define ui_ImageProps_init_zero                  {{{NULL}, NULL}}
#define ui_ArcProps_init_zero                    {0, 0, 0, 0, 0, _ui_ArcMode_MIN, 0, 0, 0}
#define ui_BarProps_init_zero                    {0, 0, 0, 0, _ui_BarMode_MIN}
#define ui_SwitchProps_init_zero                 {0}
#define ui_CheckboxProps_init_zero               {0}
#define ui_DropdownProps_init_zero               {{{NULL}, NULL}, 0, _ui_Dir_MIN}
#define ui_RollerProps_init_zero                 {{{NULL}, NULL}, 0, 0, _ui_RollerMode_MIN}
#define ui_TextareaProps_init_zero               {{{NULL}, NULL}, 0, 0, 0}
#define ui_SpinboxProps_init_zero                {0, 0, 0, 0, 0, 0}
#define ui_SpinnerProps_init_zero                {0, 0}
#define ui_LedProps_init_zero                    {false, ui_Color_init_zero, 0}
#define ui_LineProps_init_zero                   {{{NULL}, NULL}, 0}
#define ui_ScaleProps_init_zero                  {_ui_ScaleMode_MIN, 0, 0, 0, 0, 0, 0, 0}
#define ui_ButtonMatrixProps_init_zero           {{{NULL}, NULL}, 0}
#define ui_TableProps_init_zero                  {0, 0}
#define ui_Point_init_zero                       {0, 0}
#define ui_EventBinding_init_zero                {{{NULL}, NULL}, _ui_EventTrigger_MIN, 0, 0, {{NULL}, NULL}, 0, 0, 0}
#define ui_VisibilityBinding_init_zero           {{{NULL}, NULL}, 0, _ui_CompareOp_MIN}
#define ui_Layout_init_zero                      {_ui_FlexFlow_MIN, _ui_FlexAlign_MIN, _ui_FlexAlign_MIN, _ui_FlexAlign_MIN}
#define ui_StyleGroup_init_zero                  {0, {{NULL}, NULL}}
#define ui_ResolvedStyle_init_zero               {{{NULL}, NULL}}
#define ui_StyleProperty_init_zero               {_ui_StylePropertyType_MIN, 0, {0}}
#define ui_Color_init_zero                       {0, 0, 0}
#define ui_ShadowBundle_init_zero                {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ui_SubjectDeclaration_name_tag           1
#define ui_SubjectDeclaration_type_tag           2
#define ui_SubjectDeclaration_int_initial_tag    3
#define ui_SubjectDeclaration_string_initial_tag 4
#define ui_StateUpdate_values_tag                1
#define ui_SubjectValue_name_tag                 1
#define ui_SubjectValue_int_value_tag            2
#define ui_SubjectValue_string_value_tag         3
#define ui_WidgetNode_BindingsEntry_key_tag      1
#define ui_WidgetNode_BindingsEntry_value_tag    2
#define ui_WidgetNode_BindFormatsEntry_key_tag   1
#define ui_WidgetNode_BindFormatsEntry_value_tag 2
#define ui_LabelProps_long_mode_tag              1
#define ui_SliderProps_min_value_tag             1
#define ui_SliderProps_max_value_tag             2
#define ui_SliderProps_value_tag                 3
#define ui_SliderProps_mode_tag                  4
#define ui_ImageProps_src_tag                    1
#define ui_ArcProps_start_angle_tag              1
#define ui_ArcProps_end_angle_tag                2
#define ui_ArcProps_bg_start_angle_tag           3
#define ui_ArcProps_bg_end_angle_tag             4
#define ui_ArcProps_rotation_tag                 5
#define ui_ArcProps_mode_tag                     6
#define ui_ArcProps_min_value_tag                7
#define ui_ArcProps_max_value_tag                8
#define ui_ArcProps_value_tag                    9
#define ui_BarProps_min_value_tag                1
#define ui_BarProps_max_value_tag                2
#define ui_BarProps_value_tag                    3
#define ui_BarProps_start_value_tag              4
#define ui_BarProps_mode_tag                     5
#define ui_SwitchProps_checked_tag               1
#define ui_CheckboxProps_checked_tag             1
#define ui_DropdownProps_options_tag             1
#define ui_DropdownProps_selected_tag            2
#define ui_DropdownProps_direction_tag           3
#define ui_RollerProps_options_tag               1
#define ui_RollerProps_selected_tag              2
#define ui_RollerProps_visible_row_count_tag     3
#define ui_RollerProps_mode_tag                  4
#define ui_TextareaProps_placeholder_tag         1
#define ui_TextareaProps_max_length_tag          2
#define ui_TextareaProps_one_line_tag            3
#define ui_TextareaProps_password_mode_tag       4
#define ui_SpinboxProps_min_value_tag            1
#define ui_SpinboxProps_max_value_tag            2
#define ui_SpinboxProps_value_tag                3
#define ui_SpinboxProps_step_tag                 4
#define ui_SpinboxProps_digit_count_tag          5
#define ui_SpinboxProps_separator_position_tag   6
#define ui_SpinnerProps_spin_time_tag            1
#define ui_SpinnerProps_arc_length_tag           2
#define ui_LineProps_points_tag                  1
#define ui_LineProps_y_invert_tag                2
#define ui_ScaleProps_mode_tag                   1
#define ui_ScaleProps_total_tick_count_tag       2
#define ui_ScaleProps_major_tick_every_tag       3
#define ui_ScaleProps_label_show_tag             4
#define ui_ScaleProps_min_value_tag              5
#define ui_ScaleProps_max_value_tag              6
#define ui_ScaleProps_rotation_tag               7
#define ui_ScaleProps_angle_range_tag            8
#define ui_ButtonMatrixProps_map_str_tag         1
#define ui_ButtonMatrixProps_one_check_tag       2
#define ui_TableProps_row_count_tag              1
#define ui_TableProps_column_count_tag           2
#define ui_Point_x_tag                           1
#define ui_Point_y_tag                           2
#define ui_EventBinding_name_tag                 1
#define ui_EventBinding_trigger_tag              2
#define ui_EventBinding_int_value_tag            3
#define ui_EventBinding_include_widget_value_tag 4
#define ui_EventBinding_set_subject_tag          5
#define ui_EventBinding_set_value_tag            6
#define ui_EventBinding_toggle_tag               7
#define ui_EventBinding_notify_host_tag          8
#define ui_VisibilityBinding_subject_tag         1
#define ui_VisibilityBinding_ref_value_tag       2
#define ui_VisibilityBinding_compare_tag         3
#define ui_Layout_flow_tag                       1
#define ui_Layout_main_place_tag                 2
#define ui_Layout_cross_place_tag                3
#define ui_Layout_track_place_tag                4
#define ui_StyleGroup_state_selector_tag         1
#define ui_StyleGroup_variants_tag               2
#define ui_ResolvedStyle_properties_tag          1
#define ui_Color_r_tag                           1
#define ui_Color_g_tag                           2
#define ui_Color_b_tag                           3
#define ui_LedProps_color_tag                    1
#define ui_LedProps_brightness_tag               2
#define ui_WidgetNode_type_tag                   1
#define ui_WidgetNode_x_tag                      2
#define ui_WidgetNode_y_tag                      3
#define ui_WidgetNode_text_tag                   4
#define ui_WidgetNode_bindings_tag               5
#define ui_WidgetNode_event_tag                  6
#define ui_WidgetNode_layout_tag                 7
#define ui_WidgetNode_children_tag               8
#define ui_WidgetNode_style_groups_tag           9
#define ui_WidgetNode_obj_props_tag              10
#define ui_WidgetNode_button_props_tag           11
#define ui_WidgetNode_label_props_tag            12
#define ui_WidgetNode_slider_props_tag           13
#define ui_WidgetNode_image_props_tag            14
#define ui_WidgetNode_arc_props_tag              15
#define ui_WidgetNode_bar_props_tag              16
#define ui_WidgetNode_switch_props_tag           17
#define ui_WidgetNode_checkbox_props_tag         18
#define ui_WidgetNode_dropdown_props_tag         19
#define ui_WidgetNode_roller_props_tag           20
#define ui_WidgetNode_textarea_props_tag         21
#define ui_WidgetNode_spinbox_props_tag          22
#define ui_WidgetNode_spinner_props_tag          23
#define ui_WidgetNode_led_props_tag              24
#define ui_WidgetNode_line_props_tag             25
#define ui_WidgetNode_scale_props_tag            26
#define ui_WidgetNode_buttonmatrix_props_tag     27
#define ui_WidgetNode_table_props_tag            28
#define ui_WidgetNode_visibility_tag             29
#define ui_WidgetNode_bind_formats_tag           30
#define ui_Screen_root_tag                       1
#define ui_Screen_subjects_tag                   2
#define ui_ShadowBundle_width_tag                1
#define ui_ShadowBundle_offset_x_tag             2
#define ui_ShadowBundle_offset_y_tag             3
#define ui_ShadowBundle_spread_tag               4
#define ui_ShadowBundle_opa_tag                  5
#define ui_StyleProperty_type_tag                1
#define ui_StyleProperty_uint_value_tag          2
#define ui_StyleProperty_int_value_tag           3
#define ui_StyleProperty_color_value_tag         4
#define ui_StyleProperty_string_value_tag        5
#define ui_StyleProperty_shadow_value_tag        6

/* Struct field encoding specification for nanopb */
#define ui_SubjectDeclaration_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   ONEOF,    INT32,    (initial,int_initial,initial.int_initial),   3) \
X(a, CALLBACK, ONEOF,    STRING,   (initial,string_initial,initial.string_initial),   4)
#define ui_SubjectDeclaration_CALLBACK pb_default_field_callback
#define ui_SubjectDeclaration_DEFAULT NULL

#define ui_StateUpdate_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            1)
#define ui_StateUpdate_CALLBACK pb_default_field_callback
#define ui_StateUpdate_DEFAULT NULL
#define ui_StateUpdate_values_MSGTYPE ui_SubjectValue

#define ui_SubjectValue_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   2) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),   3)
#define ui_SubjectValue_CALLBACK pb_default_field_callback
#define ui_SubjectValue_DEFAULT NULL

#define ui_Screen_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  root,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  subjects,          2)
#define ui_Screen_CALLBACK pb_default_field_callback
#define ui_Screen_DEFAULT NULL
#define ui_Screen_root_MSGTYPE ui_WidgetNode
#define ui_Screen_subjects_MSGTYPE ui_SubjectDeclaration

#define ui_WidgetNode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    x,                 2) \
X(a, STATIC,   SINGULAR, INT32,    y,                 3) \
X(a, CALLBACK, SINGULAR, STRING,   text,              4) \
X(a, CALLBACK, REPEATED, MESSAGE,  bindings,          5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  event,             6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  layout,            7) \
X(a, CALLBACK, REPEATED, MESSAGE,  children,          8) \
X(a, CALLBACK, REPEATED, MESSAGE,  style_groups,      9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,obj_props,widget_props.obj_props),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,button_props,widget_props.button_props),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,label_props,widget_props.label_props),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,slider_props,widget_props.slider_props),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,image_props,widget_props.image_props),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,arc_props,widget_props.arc_props),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,bar_props,widget_props.bar_props),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,switch_props,widget_props.switch_props),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,checkbox_props,widget_props.checkbox_props),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,dropdown_props,widget_props.dropdown_props),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,roller_props,widget_props.roller_props),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,textarea_props,widget_props.textarea_props),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,spinbox_props,widget_props.spinbox_props),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,spinner_props,widget_props.spinner_props),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,led_props,widget_props.led_props),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,line_props,widget_props.line_props),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,scale_props,widget_props.scale_props),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,buttonmatrix_props,widget_props.buttonmatrix_props),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (widget_props,table_props,widget_props.table_props),  28) \
X(a, STATIC,   OPTIONAL, MESSAGE,  visibility,       29) \
X(a, CALLBACK, REPEATED, MESSAGE,  bind_formats,     30)
#define ui_WidgetNode_CALLBACK pb_default_field_callback
#define ui_WidgetNode_DEFAULT NULL
#define ui_WidgetNode_bindings_MSGTYPE ui_WidgetNode_BindingsEntry
#define ui_WidgetNode_event_MSGTYPE ui_EventBinding
#define ui_WidgetNode_layout_MSGTYPE ui_Layout
#define ui_WidgetNode_children_MSGTYPE ui_WidgetNode
#define ui_WidgetNode_style_groups_MSGTYPE ui_StyleGroup
#define ui_WidgetNode_widget_props_obj_props_MSGTYPE ui_ObjProps
#define ui_WidgetNode_widget_props_button_props_MSGTYPE ui_ButtonProps
#define ui_WidgetNode_widget_props_label_props_MSGTYPE ui_LabelProps
#define ui_WidgetNode_widget_props_slider_props_MSGTYPE ui_SliderProps
#define ui_WidgetNode_widget_props_image_props_MSGTYPE ui_ImageProps
#define ui_WidgetNode_widget_props_arc_props_MSGTYPE ui_ArcProps
#define ui_WidgetNode_widget_props_bar_props_MSGTYPE ui_BarProps
#define ui_WidgetNode_widget_props_switch_props_MSGTYPE ui_SwitchProps
#define ui_WidgetNode_widget_props_checkbox_props_MSGTYPE ui_CheckboxProps
#define ui_WidgetNode_widget_props_dropdown_props_MSGTYPE ui_DropdownProps
#define ui_WidgetNode_widget_props_roller_props_MSGTYPE ui_RollerProps
#define ui_WidgetNode_widget_props_textarea_props_MSGTYPE ui_TextareaProps
#define ui_WidgetNode_widget_props_spinbox_props_MSGTYPE ui_SpinboxProps
#define ui_WidgetNode_widget_props_spinner_props_MSGTYPE ui_SpinnerProps
#define ui_WidgetNode_widget_props_led_props_MSGTYPE ui_LedProps
#define ui_WidgetNode_widget_props_line_props_MSGTYPE ui_LineProps
#define ui_WidgetNode_widget_props_scale_props_MSGTYPE ui_ScaleProps
#define ui_WidgetNode_widget_props_buttonmatrix_props_MSGTYPE ui_ButtonMatrixProps
#define ui_WidgetNode_widget_props_table_props_MSGTYPE ui_TableProps
#define ui_WidgetNode_visibility_MSGTYPE ui_VisibilityBinding
#define ui_WidgetNode_bind_formats_MSGTYPE ui_WidgetNode_BindFormatsEntry

#define ui_WidgetNode_BindingsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define ui_WidgetNode_BindingsEntry_CALLBACK pb_default_field_callback
#define ui_WidgetNode_BindingsEntry_DEFAULT NULL

#define ui_WidgetNode_BindFormatsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define ui_WidgetNode_BindFormatsEntry_CALLBACK pb_default_field_callback
#define ui_WidgetNode_BindFormatsEntry_DEFAULT NULL

#define ui_ObjProps_FIELDLIST(X, a) \

#define ui_ObjProps_CALLBACK NULL
#define ui_ObjProps_DEFAULT NULL

#define ui_ButtonProps_FIELDLIST(X, a) \

#define ui_ButtonProps_CALLBACK NULL
#define ui_ButtonProps_DEFAULT NULL

#define ui_LabelProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    long_mode,         1)
#define ui_LabelProps_CALLBACK NULL
#define ui_LabelProps_DEFAULT NULL

#define ui_SliderProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    min_value,         1) \
X(a, STATIC,   SINGULAR, INT32,    max_value,         2) \
X(a, STATIC,   SINGULAR, INT32,    value,             3) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              4)
#define ui_SliderProps_CALLBACK NULL
#define ui_SliderProps_DEFAULT NULL

#define ui_ImageProps_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   src,               1)
#define ui_ImageProps_CALLBACK pb_default_field_callback
#define ui_ImageProps_DEFAULT NULL

#define ui_ArcProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_angle,       1) \
X(a, STATIC,   SINGULAR, UINT32,   end_angle,         2) \
X(a, STATIC,   SINGULAR, UINT32,   bg_start_angle,    3) \
X(a, STATIC,   SINGULAR, UINT32,   bg_end_angle,      4) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          5) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              6) \
X(a, STATIC,   SINGULAR, INT32,    min_value,         7) \
X(a, STATIC,   SINGULAR, INT32,    max_value,         8) \
X(a, STATIC,   SINGULAR, INT32,    value,             9)
#define ui_ArcProps_CALLBACK NULL
#define ui_ArcProps_DEFAULT NULL

#define ui_BarProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    min_value,         1) \
X(a, STATIC,   SINGULAR, INT32,    max_value,         2) \
X(a, STATIC,   SINGULAR, INT32,    value,             3) \
X(a, STATIC,   SINGULAR, INT32,    start_value,       4) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              5)
#define ui_BarProps_CALLBACK NULL
#define ui_BarProps_DEFAULT NULL

#define ui_SwitchProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     checked,           1)
#define ui_SwitchProps_CALLBACK NULL
#define ui_SwitchProps_DEFAULT NULL

#define ui_CheckboxProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     checked,           1)
#define ui_CheckboxProps_CALLBACK NULL
#define ui_CheckboxProps_DEFAULT NULL

#define ui_DropdownProps_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   options,           1) \
X(a, STATIC,   SINGULAR, UINT32,   selected,          2) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         3)
#define ui_DropdownProps_CALLBACK pb_default_field_callback
#define ui_DropdownProps_DEFAULT NULL

#define ui_RollerProps_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   options,           1) \
X(a, STATIC,   SINGULAR, UINT32,   selected,          2) \
X(a, STATIC,   SINGULAR, UINT32,   visible_row_count,   3) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              4)
#define ui_RollerProps_CALLBACK pb_default_field_callback
#define ui_RollerProps_DEFAULT NULL

#define ui_TextareaProps_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   placeholder,       1) \
X(a, STATIC,   SINGULAR, UINT32,   max_length,        2) \
X(a, STATIC,   SINGULAR, BOOL,     one_line,          3) \
X(a, STATIC,   SINGULAR, BOOL,     password_mode,     4)
#define ui_TextareaProps_CALLBACK pb_default_field_callback
#define ui_TextareaProps_DEFAULT NULL

#define ui_SpinboxProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    min_value,         1) \
X(a, STATIC,   SINGULAR, INT32,    max_value,         2) \
X(a, STATIC,   SINGULAR, INT32,    value,             3) \
X(a, STATIC,   SINGULAR, INT32,    step,              4) \
X(a, STATIC,   SINGULAR, UINT32,   digit_count,       5) \
X(a, STATIC,   SINGULAR, UINT32,   separator_position,   6)
#define ui_SpinboxProps_CALLBACK NULL
#define ui_SpinboxProps_DEFAULT NULL

#define ui_SpinnerProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   spin_time,         1) \
X(a, STATIC,   SINGULAR, UINT32,   arc_length,        2)
#define ui_SpinnerProps_CALLBACK NULL
#define ui_SpinnerProps_DEFAULT NULL

#define ui_LedProps_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2)
#define ui_LedProps_CALLBACK NULL
#define ui_LedProps_DEFAULT NULL
#define ui_LedProps_color_MSGTYPE ui_Color

#define ui_LineProps_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  points,            1) \
X(a, STATIC,   SINGULAR, BOOL,     y_invert,          2)
#define ui_LineProps_CALLBACK pb_default_field_callback
#define ui_LineProps_DEFAULT NULL
#define ui_LineProps_points_MSGTYPE ui_Point

#define ui_ScaleProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, UINT32,   total_tick_count,   2) \
X(a, STATIC,   SINGULAR, UINT32,   major_tick_every,   3) \
X(a, STATIC,   SINGULAR, BOOL,     label_show,        4) \
X(a, STATIC,   SINGULAR, INT32,    min_value,         5) \
X(a, STATIC,   SINGULAR, INT32,    max_value,         6) \
X(a, STATIC,   SINGULAR, INT32,    rotation,          7) \
X(a, STATIC,   SINGULAR, UINT32,   angle_range,       8)
#define ui_ScaleProps_CALLBACK NULL
#define ui_ScaleProps_DEFAULT NULL

#define ui_ButtonMatrixProps_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   map_str,           1) \
X(a, STATIC,   SINGULAR, BOOL,     one_check,         2)
#define ui_ButtonMatrixProps_CALLBACK pb_default_field_callback
#define ui_ButtonMatrixProps_DEFAULT NULL

#define ui_TableProps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   row_count,         1) \
X(a, STATIC,   SINGULAR, UINT32,   column_count,      2)
#define ui_TableProps_CALLBACK NULL
#define ui_TableProps_DEFAULT NULL

#define ui_Point_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x,                 1) \
X(a, STATIC,   SINGULAR, INT32,    y,                 2)
#define ui_Point_CALLBACK NULL
#define ui_Point_DEFAULT NULL

#define ui_EventBinding_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    trigger,           2) \
X(a, STATIC,   SINGULAR, INT32,    int_value,         3) \
X(a, STATIC,   SINGULAR, BOOL,     include_widget_value,   4) \
X(a, CALLBACK, SINGULAR, STRING,   set_subject,       5) \
X(a, STATIC,   SINGULAR, INT32,    set_value,         6) \
X(a, STATIC,   SINGULAR, BOOL,     toggle,            7) \
X(a, STATIC,   SINGULAR, BOOL,     notify_host,       8)
#define ui_EventBinding_CALLBACK pb_default_field_callback
#define ui_EventBinding_DEFAULT NULL

#define ui_VisibilityBinding_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   subject,           1) \
X(a, STATIC,   SINGULAR, INT32,    ref_value,         2) \
X(a, STATIC,   SINGULAR, UENUM,    compare,           3)
#define ui_VisibilityBinding_CALLBACK pb_default_field_callback
#define ui_VisibilityBinding_DEFAULT NULL

#define ui_Layout_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    flow,              1) \
X(a, STATIC,   SINGULAR, UENUM,    main_place,        2) \
X(a, STATIC,   SINGULAR, UENUM,    cross_place,       3) \
X(a, STATIC,   SINGULAR, UENUM,    track_place,       4)
#define ui_Layout_CALLBACK NULL
#define ui_Layout_DEFAULT NULL

#define ui_StyleGroup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state_selector,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  variants,          2)
#define ui_StyleGroup_CALLBACK pb_default_field_callback
#define ui_StyleGroup_DEFAULT NULL
#define ui_StyleGroup_variants_MSGTYPE ui_ResolvedStyle

#define ui_ResolvedStyle_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  properties,        1)
#define ui_ResolvedStyle_CALLBACK pb_default_field_callback
#define ui_ResolvedStyle_DEFAULT NULL
#define ui_ResolvedStyle_properties_MSGTYPE ui_StyleProperty

#define ui_StyleProperty_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    UINT32,   (value,uint_value,value.uint_value),   2) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,color_value,value.color_value),   4) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,shadow_value,value.shadow_value),   6)
#define ui_StyleProperty_CALLBACK pb_default_field_callback
#define ui_StyleProperty_DEFAULT NULL
#define ui_StyleProperty_value_color_value_MSGTYPE ui_Color
#define ui_StyleProperty_value_shadow_value_MSGTYPE ui_ShadowBundle

#define ui_Color_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3)
#define ui_Color_CALLBACK NULL
#define ui_Color_DEFAULT NULL

#define ui_ShadowBundle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   width,             1) \
X(a, STATIC,   SINGULAR, INT32,    offset_x,          2) \
X(a, STATIC,   SINGULAR, INT32,    offset_y,          3) \
X(a, STATIC,   SINGULAR, UINT32,   spread,            4) \
X(a, STATIC,   SINGULAR, UINT32,   opa,               5)
#define ui_ShadowBundle_CALLBACK NULL
#define ui_ShadowBundle_DEFAULT NULL

extern const pb_msgdesc_t ui_SubjectDeclaration_msg;
extern const pb_msgdesc_t ui_StateUpdate_msg;
extern const pb_msgdesc_t ui_SubjectValue_msg;
extern const pb_msgdesc_t ui_Screen_msg;
extern const pb_msgdesc_t ui_WidgetNode_msg;
extern const pb_msgdesc_t ui_WidgetNode_BindingsEntry_msg;
extern const pb_msgdesc_t ui_WidgetNode_BindFormatsEntry_msg;
extern const pb_msgdesc_t ui_ObjProps_msg;
extern const pb_msgdesc_t ui_ButtonProps_msg;
extern const pb_msgdesc_t ui_LabelProps_msg;
extern const pb_msgdesc_t ui_SliderProps_msg;
extern const pb_msgdesc_t ui_ImageProps_msg;
extern const pb_msgdesc_t ui_ArcProps_msg;
extern const pb_msgdesc_t ui_BarProps_msg;
extern const pb_msgdesc_t ui_SwitchProps_msg;
extern const pb_msgdesc_t ui_CheckboxProps_msg;
extern const pb_msgdesc_t ui_DropdownProps_msg;
extern const pb_msgdesc_t ui_RollerProps_msg;
extern const pb_msgdesc_t ui_TextareaProps_msg;
extern const pb_msgdesc_t ui_SpinboxProps_msg;
extern const pb_msgdesc_t ui_SpinnerProps_msg;
extern const pb_msgdesc_t ui_LedProps_msg;
extern const pb_msgdesc_t ui_LineProps_msg;
extern const pb_msgdesc_t ui_ScaleProps_msg;
extern const pb_msgdesc_t ui_ButtonMatrixProps_msg;
extern const pb_msgdesc_t ui_TableProps_msg;
extern const pb_msgdesc_t ui_Point_msg;
extern const pb_msgdesc_t ui_EventBinding_msg;
extern const pb_msgdesc_t ui_VisibilityBinding_msg;
extern const pb_msgdesc_t ui_Layout_msg;
extern const pb_msgdesc_t ui_StyleGroup_msg;
extern const pb_msgdesc_t ui_ResolvedStyle_msg;
extern const pb_msgdesc_t ui_StyleProperty_msg;
extern const pb_msgdesc_t ui_Color_msg;
extern const pb_msgdesc_t ui_ShadowBundle_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ui_SubjectDeclaration_fields &ui_SubjectDeclaration_msg
#define ui_StateUpdate_fields &ui_StateUpdate_msg
#define ui_SubjectValue_fields &ui_SubjectValue_msg
#define ui_Screen_fields &ui_Screen_msg
#define ui_WidgetNode_fields &ui_WidgetNode_msg
#define ui_WidgetNode_BindingsEntry_fields &ui_WidgetNode_BindingsEntry_msg
#define ui_WidgetNode_BindFormatsEntry_fields &ui_WidgetNode_BindFormatsEntry_msg
#define ui_ObjProps_fields &ui_ObjProps_msg
#define ui_ButtonProps_fields &ui_ButtonProps_msg
#define ui_LabelProps_fields &ui_LabelProps_msg
#define ui_SliderProps_fields &ui_SliderProps_msg
#define ui_ImageProps_fields &ui_ImageProps_msg
#define ui_ArcProps_fields &ui_ArcProps_msg
#define ui_BarProps_fields &ui_BarProps_msg
#define ui_SwitchProps_fields &ui_SwitchProps_msg
#define ui_CheckboxProps_fields &ui_CheckboxProps_msg
#define ui_DropdownProps_fields &ui_DropdownProps_msg
#define ui_RollerProps_fields &ui_RollerProps_msg
#define ui_TextareaProps_fields &ui_TextareaProps_msg
#define ui_SpinboxProps_fields &ui_SpinboxProps_msg
#define ui_SpinnerProps_fields &ui_SpinnerProps_msg
#define ui_LedProps_fields &ui_LedProps_msg
#define ui_LineProps_fields &ui_LineProps_msg
#define ui_ScaleProps_fields &ui_ScaleProps_msg
#define ui_ButtonMatrixProps_fields &ui_ButtonMatrixProps_msg
#define ui_TableProps_fields &ui_TableProps_msg
#define ui_Point_fields &ui_Point_msg
#define ui_EventBinding_fields &ui_EventBinding_msg
#define ui_VisibilityBinding_fields &ui_VisibilityBinding_msg
#define ui_Layout_fields &ui_Layout_msg
#define ui_StyleGroup_fields &ui_StyleGroup_msg
#define ui_ResolvedStyle_fields &ui_ResolvedStyle_msg
#define ui_StyleProperty_fields &ui_StyleProperty_msg
#define ui_Color_fields &ui_Color_msg
#define ui_ShadowBundle_fields &ui_ShadowBundle_msg

/* Maximum encoded size of messages (where known) */
/* ui_SubjectDeclaration_size depends on runtime parameters */
/* ui_StateUpdate_size depends on runtime parameters */
/* ui_SubjectValue_size depends on runtime parameters */
/* ui_Screen_size depends on runtime parameters */
/* ui_WidgetNode_size depends on runtime parameters */
/* ui_WidgetNode_BindingsEntry_size depends on runtime parameters */
/* ui_WidgetNode_BindFormatsEntry_size depends on runtime parameters */
/* ui_ImageProps_size depends on runtime parameters */
/* ui_DropdownProps_size depends on runtime parameters */
/* ui_RollerProps_size depends on runtime parameters */
/* ui_TextareaProps_size depends on runtime parameters */
/* ui_LineProps_size depends on runtime parameters */
/* ui_ButtonMatrixProps_size depends on runtime parameters */
/* ui_EventBinding_size depends on runtime parameters */
/* ui_VisibilityBinding_size depends on runtime parameters */
/* ui_StyleGroup_size depends on runtime parameters */
/* ui_ResolvedStyle_size depends on runtime parameters */
/* ui_StyleProperty_size depends on runtime parameters */
#define UI_UI_UI_AST_PB_H_MAX_SIZE               ui_ArcProps_size
#define ui_ArcProps_size                         70
#define ui_BarProps_size                         46
#define ui_ButtonProps_size                      0
#define ui_CheckboxProps_size                    2
#define ui_Color_size                            18
#define ui_LabelProps_size                       2
#define ui_Layout_size                           8
#define ui_LedProps_size                         26
#define ui_ObjProps_size                         0
#define ui_Point_size                            22
#define ui_ScaleProps_size                       55
#define ui_ShadowBundle_size                     40
#define ui_SliderProps_size                      35
#define ui_SpinboxProps_size                     56
#define ui_SpinnerProps_size                     12
#define ui_SwitchProps_size                      2
#define ui_TableProps_size                       12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
