// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_cmd_rotary.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cmd.RotaryPlatform;

@kotlin.jvm.JvmName("-initializeroot")
public inline fun root(block: com.cmd.RotaryPlatform.RootKt.Dsl.() -> kotlin.Unit): com.cmd.RotaryPlatform.Root =
  com.cmd.RotaryPlatform.RootKt.Dsl._create(com.cmd.RotaryPlatform.Root.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `cmd.RotaryPlatform.Root`
 */
public object RootKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cmd.RotaryPlatform.Root.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cmd.RotaryPlatform.Root.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cmd.RotaryPlatform.Root = _builder.build()

    /**
     * `.cmd.RotaryPlatform.Start start = 1 [json_name = "start"];`
     */
    public var start: com.cmd.RotaryPlatform.Start
      @kotlin.jvm.JvmName("getStart")
        get() = _builder.start
      @kotlin.jvm.JvmName("setStart")
        set(value) {
        _builder.start = value
      }
    /**
     * `.cmd.RotaryPlatform.Start start = 1 [json_name = "start"];`
     */
    public fun clearStart() {
      _builder.clearStart()
    }
    /**
     * `.cmd.RotaryPlatform.Start start = 1 [json_name = "start"];`
     * @return Whether the start field is set.
     */
    public fun hasStart(): kotlin.Boolean {
      return _builder.hasStart()
    }

    /**
     * `.cmd.RotaryPlatform.Stop stop = 2 [json_name = "stop"];`
     */
    public var stop: com.cmd.RotaryPlatform.Stop
      @kotlin.jvm.JvmName("getStop")
        get() = _builder.stop
      @kotlin.jvm.JvmName("setStop")
        set(value) {
        _builder.stop = value
      }
    /**
     * `.cmd.RotaryPlatform.Stop stop = 2 [json_name = "stop"];`
     */
    public fun clearStop() {
      _builder.clearStop()
    }
    /**
     * `.cmd.RotaryPlatform.Stop stop = 2 [json_name = "stop"];`
     * @return Whether the stop field is set.
     */
    public fun hasStop(): kotlin.Boolean {
      return _builder.hasStop()
    }

    /**
     * `.cmd.RotaryPlatform.Axis axis = 3 [json_name = "axis"];`
     */
    public var axis: com.cmd.RotaryPlatform.Axis
      @kotlin.jvm.JvmName("getAxis")
        get() = _builder.axis
      @kotlin.jvm.JvmName("setAxis")
        set(value) {
        _builder.axis = value
      }
    /**
     * `.cmd.RotaryPlatform.Axis axis = 3 [json_name = "axis"];`
     */
    public fun clearAxis() {
      _builder.clearAxis()
    }
    /**
     * `.cmd.RotaryPlatform.Axis axis = 3 [json_name = "axis"];`
     * @return Whether the axis field is set.
     */
    public fun hasAxis(): kotlin.Boolean {
      return _builder.hasAxis()
    }

    /**
     * `.cmd.RotaryPlatform.SetPlatformAzimuth set_platform_azimuth = 4 [json_name = "setPlatformAzimuth"];`
     */
    public var setPlatformAzimuth: com.cmd.RotaryPlatform.SetPlatformAzimuth
      @kotlin.jvm.JvmName("getSetPlatformAzimuth")
        get() = _builder.setPlatformAzimuth
      @kotlin.jvm.JvmName("setSetPlatformAzimuth")
        set(value) {
        _builder.setPlatformAzimuth = value
      }
    /**
     * `.cmd.RotaryPlatform.SetPlatformAzimuth set_platform_azimuth = 4 [json_name = "setPlatformAzimuth"];`
     */
    public fun clearSetPlatformAzimuth() {
      _builder.clearSetPlatformAzimuth()
    }
    /**
     * `.cmd.RotaryPlatform.SetPlatformAzimuth set_platform_azimuth = 4 [json_name = "setPlatformAzimuth"];`
     * @return Whether the setPlatformAzimuth field is set.
     */
    public fun hasSetPlatformAzimuth(): kotlin.Boolean {
      return _builder.hasSetPlatformAzimuth()
    }

    /**
     * `.cmd.RotaryPlatform.SetPlatformElevation set_platform_elevation = 5 [json_name = "setPlatformElevation"];`
     */
    public var setPlatformElevation: com.cmd.RotaryPlatform.SetPlatformElevation
      @kotlin.jvm.JvmName("getSetPlatformElevation")
        get() = _builder.setPlatformElevation
      @kotlin.jvm.JvmName("setSetPlatformElevation")
        set(value) {
        _builder.setPlatformElevation = value
      }
    /**
     * `.cmd.RotaryPlatform.SetPlatformElevation set_platform_elevation = 5 [json_name = "setPlatformElevation"];`
     */
    public fun clearSetPlatformElevation() {
      _builder.clearSetPlatformElevation()
    }
    /**
     * `.cmd.RotaryPlatform.SetPlatformElevation set_platform_elevation = 5 [json_name = "setPlatformElevation"];`
     * @return Whether the setPlatformElevation field is set.
     */
    public fun hasSetPlatformElevation(): kotlin.Boolean {
      return _builder.hasSetPlatformElevation()
    }

    /**
     * `.cmd.RotaryPlatform.SetPlatformBank set_platform_bank = 6 [json_name = "setPlatformBank"];`
     */
    public var setPlatformBank: com.cmd.RotaryPlatform.SetPlatformBank
      @kotlin.jvm.JvmName("getSetPlatformBank")
        get() = _builder.setPlatformBank
      @kotlin.jvm.JvmName("setSetPlatformBank")
        set(value) {
        _builder.setPlatformBank = value
      }
    /**
     * `.cmd.RotaryPlatform.SetPlatformBank set_platform_bank = 6 [json_name = "setPlatformBank"];`
     */
    public fun clearSetPlatformBank() {
      _builder.clearSetPlatformBank()
    }
    /**
     * `.cmd.RotaryPlatform.SetPlatformBank set_platform_bank = 6 [json_name = "setPlatformBank"];`
     * @return Whether the setPlatformBank field is set.
     */
    public fun hasSetPlatformBank(): kotlin.Boolean {
      return _builder.hasSetPlatformBank()
    }

    /**
     * `.cmd.RotaryPlatform.Halt halt = 7 [json_name = "halt"];`
     */
    public var halt: com.cmd.RotaryPlatform.Halt
      @kotlin.jvm.JvmName("getHalt")
        get() = _builder.halt
      @kotlin.jvm.JvmName("setHalt")
        set(value) {
        _builder.halt = value
      }
    /**
     * `.cmd.RotaryPlatform.Halt halt = 7 [json_name = "halt"];`
     */
    public fun clearHalt() {
      _builder.clearHalt()
    }
    /**
     * `.cmd.RotaryPlatform.Halt halt = 7 [json_name = "halt"];`
     * @return Whether the halt field is set.
     */
    public fun hasHalt(): kotlin.Boolean {
      return _builder.hasHalt()
    }

    /**
     * `.cmd.RotaryPlatform.setUseRotaryAsCompass set_use_rotary_as_compass = 8 [json_name = "setUseRotaryAsCompass"];`
     */
    public var setUseRotaryAsCompass: com.cmd.RotaryPlatform.setUseRotaryAsCompass
      @kotlin.jvm.JvmName("getSetUseRotaryAsCompass")
        get() = _builder.setUseRotaryAsCompass
      @kotlin.jvm.JvmName("setSetUseRotaryAsCompass")
        set(value) {
        _builder.setUseRotaryAsCompass = value
      }
    /**
     * `.cmd.RotaryPlatform.setUseRotaryAsCompass set_use_rotary_as_compass = 8 [json_name = "setUseRotaryAsCompass"];`
     */
    public fun clearSetUseRotaryAsCompass() {
      _builder.clearSetUseRotaryAsCompass()
    }
    /**
     * `.cmd.RotaryPlatform.setUseRotaryAsCompass set_use_rotary_as_compass = 8 [json_name = "setUseRotaryAsCompass"];`
     * @return Whether the setUseRotaryAsCompass field is set.
     */
    public fun hasSetUseRotaryAsCompass(): kotlin.Boolean {
      return _builder.hasSetUseRotaryAsCompass()
    }

    /**
     * `.cmd.RotaryPlatform.RotateToGPS rotate_to_gps = 9 [json_name = "rotateToGps"];`
     */
    public var rotateToGps: com.cmd.RotaryPlatform.RotateToGPS
      @kotlin.jvm.JvmName("getRotateToGps")
        get() = _builder.rotateToGps
      @kotlin.jvm.JvmName("setRotateToGps")
        set(value) {
        _builder.rotateToGps = value
      }
    /**
     * `.cmd.RotaryPlatform.RotateToGPS rotate_to_gps = 9 [json_name = "rotateToGps"];`
     */
    public fun clearRotateToGps() {
      _builder.clearRotateToGps()
    }
    /**
     * `.cmd.RotaryPlatform.RotateToGPS rotate_to_gps = 9 [json_name = "rotateToGps"];`
     * @return Whether the rotateToGps field is set.
     */
    public fun hasRotateToGps(): kotlin.Boolean {
      return _builder.hasRotateToGps()
    }

    /**
     * `.cmd.RotaryPlatform.SetOriginGPS set_origin_gps = 10 [json_name = "setOriginGps"];`
     */
    public var setOriginGps: com.cmd.RotaryPlatform.SetOriginGPS
      @kotlin.jvm.JvmName("getSetOriginGps")
        get() = _builder.setOriginGps
      @kotlin.jvm.JvmName("setSetOriginGps")
        set(value) {
        _builder.setOriginGps = value
      }
    /**
     * `.cmd.RotaryPlatform.SetOriginGPS set_origin_gps = 10 [json_name = "setOriginGps"];`
     */
    public fun clearSetOriginGps() {
      _builder.clearSetOriginGps()
    }
    /**
     * `.cmd.RotaryPlatform.SetOriginGPS set_origin_gps = 10 [json_name = "setOriginGps"];`
     * @return Whether the setOriginGps field is set.
     */
    public fun hasSetOriginGps(): kotlin.Boolean {
      return _builder.hasSetOriginGps()
    }

    /**
     * `.cmd.RotaryPlatform.SetMode set_mode = 11 [json_name = "setMode"];`
     */
    public var setMode: com.cmd.RotaryPlatform.SetMode
      @kotlin.jvm.JvmName("getSetMode")
        get() = _builder.setMode
      @kotlin.jvm.JvmName("setSetMode")
        set(value) {
        _builder.setMode = value
      }
    /**
     * `.cmd.RotaryPlatform.SetMode set_mode = 11 [json_name = "setMode"];`
     */
    public fun clearSetMode() {
      _builder.clearSetMode()
    }
    /**
     * `.cmd.RotaryPlatform.SetMode set_mode = 11 [json_name = "setMode"];`
     * @return Whether the setMode field is set.
     */
    public fun hasSetMode(): kotlin.Boolean {
      return _builder.hasSetMode()
    }

    /**
     * `.cmd.RotaryPlatform.RotateToNDC rotate_to_ndc = 12 [json_name = "rotateToNdc"];`
     */
    public var rotateToNdc: com.cmd.RotaryPlatform.RotateToNDC
      @kotlin.jvm.JvmName("getRotateToNdc")
        get() = _builder.rotateToNdc
      @kotlin.jvm.JvmName("setRotateToNdc")
        set(value) {
        _builder.rotateToNdc = value
      }
    /**
     * `.cmd.RotaryPlatform.RotateToNDC rotate_to_ndc = 12 [json_name = "rotateToNdc"];`
     */
    public fun clearRotateToNdc() {
      _builder.clearRotateToNdc()
    }
    /**
     * `.cmd.RotaryPlatform.RotateToNDC rotate_to_ndc = 12 [json_name = "rotateToNdc"];`
     * @return Whether the rotateToNdc field is set.
     */
    public fun hasRotateToNdc(): kotlin.Boolean {
      return _builder.hasRotateToNdc()
    }

    /**
     * `.cmd.RotaryPlatform.ScanStart scan_start = 13 [json_name = "scanStart"];`
     */
    public var scanStart: com.cmd.RotaryPlatform.ScanStart
      @kotlin.jvm.JvmName("getScanStart")
        get() = _builder.scanStart
      @kotlin.jvm.JvmName("setScanStart")
        set(value) {
        _builder.scanStart = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanStart scan_start = 13 [json_name = "scanStart"];`
     */
    public fun clearScanStart() {
      _builder.clearScanStart()
    }
    /**
     * `.cmd.RotaryPlatform.ScanStart scan_start = 13 [json_name = "scanStart"];`
     * @return Whether the scanStart field is set.
     */
    public fun hasScanStart(): kotlin.Boolean {
      return _builder.hasScanStart()
    }

    /**
     * `.cmd.RotaryPlatform.ScanStop scan_stop = 14 [json_name = "scanStop"];`
     */
    public var scanStop: com.cmd.RotaryPlatform.ScanStop
      @kotlin.jvm.JvmName("getScanStop")
        get() = _builder.scanStop
      @kotlin.jvm.JvmName("setScanStop")
        set(value) {
        _builder.scanStop = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanStop scan_stop = 14 [json_name = "scanStop"];`
     */
    public fun clearScanStop() {
      _builder.clearScanStop()
    }
    /**
     * `.cmd.RotaryPlatform.ScanStop scan_stop = 14 [json_name = "scanStop"];`
     * @return Whether the scanStop field is set.
     */
    public fun hasScanStop(): kotlin.Boolean {
      return _builder.hasScanStop()
    }

    /**
     * `.cmd.RotaryPlatform.ScanPause scan_pause = 15 [json_name = "scanPause"];`
     */
    public var scanPause: com.cmd.RotaryPlatform.ScanPause
      @kotlin.jvm.JvmName("getScanPause")
        get() = _builder.scanPause
      @kotlin.jvm.JvmName("setScanPause")
        set(value) {
        _builder.scanPause = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanPause scan_pause = 15 [json_name = "scanPause"];`
     */
    public fun clearScanPause() {
      _builder.clearScanPause()
    }
    /**
     * `.cmd.RotaryPlatform.ScanPause scan_pause = 15 [json_name = "scanPause"];`
     * @return Whether the scanPause field is set.
     */
    public fun hasScanPause(): kotlin.Boolean {
      return _builder.hasScanPause()
    }

    /**
     * `.cmd.RotaryPlatform.ScanUnpause scan_unpause = 16 [json_name = "scanUnpause"];`
     */
    public var scanUnpause: com.cmd.RotaryPlatform.ScanUnpause
      @kotlin.jvm.JvmName("getScanUnpause")
        get() = _builder.scanUnpause
      @kotlin.jvm.JvmName("setScanUnpause")
        set(value) {
        _builder.scanUnpause = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanUnpause scan_unpause = 16 [json_name = "scanUnpause"];`
     */
    public fun clearScanUnpause() {
      _builder.clearScanUnpause()
    }
    /**
     * `.cmd.RotaryPlatform.ScanUnpause scan_unpause = 16 [json_name = "scanUnpause"];`
     * @return Whether the scanUnpause field is set.
     */
    public fun hasScanUnpause(): kotlin.Boolean {
      return _builder.hasScanUnpause()
    }

    /**
     * `.cmd.RotaryPlatform.GetMeteo get_meteo = 17 [json_name = "getMeteo"];`
     */
    public var getMeteo: com.cmd.RotaryPlatform.GetMeteo
      @kotlin.jvm.JvmName("getGetMeteo")
        get() = _builder.getMeteo
      @kotlin.jvm.JvmName("setGetMeteo")
        set(value) {
        _builder.getMeteo = value
      }
    /**
     * `.cmd.RotaryPlatform.GetMeteo get_meteo = 17 [json_name = "getMeteo"];`
     */
    public fun clearGetMeteo() {
      _builder.clearGetMeteo()
    }
    /**
     * `.cmd.RotaryPlatform.GetMeteo get_meteo = 17 [json_name = "getMeteo"];`
     * @return Whether the getMeteo field is set.
     */
    public fun hasGetMeteo(): kotlin.Boolean {
      return _builder.hasGetMeteo()
    }

    /**
     * `.cmd.RotaryPlatform.ScanPrev scan_prev = 18 [json_name = "scanPrev"];`
     */
    public var scanPrev: com.cmd.RotaryPlatform.ScanPrev
      @kotlin.jvm.JvmName("getScanPrev")
        get() = _builder.scanPrev
      @kotlin.jvm.JvmName("setScanPrev")
        set(value) {
        _builder.scanPrev = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanPrev scan_prev = 18 [json_name = "scanPrev"];`
     */
    public fun clearScanPrev() {
      _builder.clearScanPrev()
    }
    /**
     * `.cmd.RotaryPlatform.ScanPrev scan_prev = 18 [json_name = "scanPrev"];`
     * @return Whether the scanPrev field is set.
     */
    public fun hasScanPrev(): kotlin.Boolean {
      return _builder.hasScanPrev()
    }

    /**
     * `.cmd.RotaryPlatform.ScanNext scan_next = 19 [json_name = "scanNext"];`
     */
    public var scanNext: com.cmd.RotaryPlatform.ScanNext
      @kotlin.jvm.JvmName("getScanNext")
        get() = _builder.scanNext
      @kotlin.jvm.JvmName("setScanNext")
        set(value) {
        _builder.scanNext = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanNext scan_next = 19 [json_name = "scanNext"];`
     */
    public fun clearScanNext() {
      _builder.clearScanNext()
    }
    /**
     * `.cmd.RotaryPlatform.ScanNext scan_next = 19 [json_name = "scanNext"];`
     * @return Whether the scanNext field is set.
     */
    public fun hasScanNext(): kotlin.Boolean {
      return _builder.hasScanNext()
    }

    /**
     * `.cmd.RotaryPlatform.ScanRefreshNodeList scan_refresh_node_list = 20 [json_name = "scanRefreshNodeList"];`
     */
    public var scanRefreshNodeList: com.cmd.RotaryPlatform.ScanRefreshNodeList
      @kotlin.jvm.JvmName("getScanRefreshNodeList")
        get() = _builder.scanRefreshNodeList
      @kotlin.jvm.JvmName("setScanRefreshNodeList")
        set(value) {
        _builder.scanRefreshNodeList = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanRefreshNodeList scan_refresh_node_list = 20 [json_name = "scanRefreshNodeList"];`
     */
    public fun clearScanRefreshNodeList() {
      _builder.clearScanRefreshNodeList()
    }
    /**
     * `.cmd.RotaryPlatform.ScanRefreshNodeList scan_refresh_node_list = 20 [json_name = "scanRefreshNodeList"];`
     * @return Whether the scanRefreshNodeList field is set.
     */
    public fun hasScanRefreshNodeList(): kotlin.Boolean {
      return _builder.hasScanRefreshNodeList()
    }

    /**
     * `.cmd.RotaryPlatform.ScanSelectNode scan_select_node = 21 [json_name = "scanSelectNode"];`
     */
    public var scanSelectNode: com.cmd.RotaryPlatform.ScanSelectNode
      @kotlin.jvm.JvmName("getScanSelectNode")
        get() = _builder.scanSelectNode
      @kotlin.jvm.JvmName("setScanSelectNode")
        set(value) {
        _builder.scanSelectNode = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanSelectNode scan_select_node = 21 [json_name = "scanSelectNode"];`
     */
    public fun clearScanSelectNode() {
      _builder.clearScanSelectNode()
    }
    /**
     * `.cmd.RotaryPlatform.ScanSelectNode scan_select_node = 21 [json_name = "scanSelectNode"];`
     * @return Whether the scanSelectNode field is set.
     */
    public fun hasScanSelectNode(): kotlin.Boolean {
      return _builder.hasScanSelectNode()
    }

    /**
     * `.cmd.RotaryPlatform.ScanDeleteNode scan_delete_node = 22 [json_name = "scanDeleteNode"];`
     */
    public var scanDeleteNode: com.cmd.RotaryPlatform.ScanDeleteNode
      @kotlin.jvm.JvmName("getScanDeleteNode")
        get() = _builder.scanDeleteNode
      @kotlin.jvm.JvmName("setScanDeleteNode")
        set(value) {
        _builder.scanDeleteNode = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanDeleteNode scan_delete_node = 22 [json_name = "scanDeleteNode"];`
     */
    public fun clearScanDeleteNode() {
      _builder.clearScanDeleteNode()
    }
    /**
     * `.cmd.RotaryPlatform.ScanDeleteNode scan_delete_node = 22 [json_name = "scanDeleteNode"];`
     * @return Whether the scanDeleteNode field is set.
     */
    public fun hasScanDeleteNode(): kotlin.Boolean {
      return _builder.hasScanDeleteNode()
    }

    /**
     * `.cmd.RotaryPlatform.ScanUpdateNode scan_update_node = 23 [json_name = "scanUpdateNode"];`
     */
    public var scanUpdateNode: com.cmd.RotaryPlatform.ScanUpdateNode
      @kotlin.jvm.JvmName("getScanUpdateNode")
        get() = _builder.scanUpdateNode
      @kotlin.jvm.JvmName("setScanUpdateNode")
        set(value) {
        _builder.scanUpdateNode = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanUpdateNode scan_update_node = 23 [json_name = "scanUpdateNode"];`
     */
    public fun clearScanUpdateNode() {
      _builder.clearScanUpdateNode()
    }
    /**
     * `.cmd.RotaryPlatform.ScanUpdateNode scan_update_node = 23 [json_name = "scanUpdateNode"];`
     * @return Whether the scanUpdateNode field is set.
     */
    public fun hasScanUpdateNode(): kotlin.Boolean {
      return _builder.hasScanUpdateNode()
    }

    /**
     * `.cmd.RotaryPlatform.ScanAddNode scan_add_node = 24 [json_name = "scanAddNode"];`
     */
    public var scanAddNode: com.cmd.RotaryPlatform.ScanAddNode
      @kotlin.jvm.JvmName("getScanAddNode")
        get() = _builder.scanAddNode
      @kotlin.jvm.JvmName("setScanAddNode")
        set(value) {
        _builder.scanAddNode = value
      }
    /**
     * `.cmd.RotaryPlatform.ScanAddNode scan_add_node = 24 [json_name = "scanAddNode"];`
     */
    public fun clearScanAddNode() {
      _builder.clearScanAddNode()
    }
    /**
     * `.cmd.RotaryPlatform.ScanAddNode scan_add_node = 24 [json_name = "scanAddNode"];`
     * @return Whether the scanAddNode field is set.
     */
    public fun hasScanAddNode(): kotlin.Boolean {
      return _builder.hasScanAddNode()
    }

    /**
     * `.cmd.RotaryPlatform.HaltWithNDC halt_with_ndc = 25 [json_name = "haltWithNdc"];`
     */
    public var haltWithNdc: com.cmd.RotaryPlatform.HaltWithNDC
      @kotlin.jvm.JvmName("getHaltWithNdc")
        get() = _builder.haltWithNdc
      @kotlin.jvm.JvmName("setHaltWithNdc")
        set(value) {
        _builder.haltWithNdc = value
      }
    /**
     * `.cmd.RotaryPlatform.HaltWithNDC halt_with_ndc = 25 [json_name = "haltWithNdc"];`
     */
    public fun clearHaltWithNdc() {
      _builder.clearHaltWithNdc()
    }
    /**
     * `.cmd.RotaryPlatform.HaltWithNDC halt_with_ndc = 25 [json_name = "haltWithNdc"];`
     * @return Whether the haltWithNdc field is set.
     */
    public fun hasHaltWithNdc(): kotlin.Boolean {
      return _builder.hasHaltWithNdc()
    }
    public val cmdCase: com.cmd.RotaryPlatform.Root.CmdCase
    @kotlin.jvm.JvmName("getCmdCase")
      get() = _builder.getCmdCase()

    public fun clearCmd() {
      _builder.clearCmd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cmd.RotaryPlatform.Root.copy(block: `com.cmd.RotaryPlatform`.RootKt.Dsl.() -> kotlin.Unit): com.cmd.RotaryPlatform.Root =
  `com.cmd.RotaryPlatform`.RootKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.cmd.RotaryPlatform.RootOrBuilder.startOrNull: com.cmd.RotaryPlatform.Start?
  get() = if (hasStart()) getStart() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.stopOrNull: com.cmd.RotaryPlatform.Stop?
  get() = if (hasStop()) getStop() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.axisOrNull: com.cmd.RotaryPlatform.Axis?
  get() = if (hasAxis()) getAxis() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.setPlatformAzimuthOrNull: com.cmd.RotaryPlatform.SetPlatformAzimuth?
  get() = if (hasSetPlatformAzimuth()) getSetPlatformAzimuth() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.setPlatformElevationOrNull: com.cmd.RotaryPlatform.SetPlatformElevation?
  get() = if (hasSetPlatformElevation()) getSetPlatformElevation() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.setPlatformBankOrNull: com.cmd.RotaryPlatform.SetPlatformBank?
  get() = if (hasSetPlatformBank()) getSetPlatformBank() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.haltOrNull: com.cmd.RotaryPlatform.Halt?
  get() = if (hasHalt()) getHalt() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.setUseRotaryAsCompassOrNull: com.cmd.RotaryPlatform.setUseRotaryAsCompass?
  get() = if (hasSetUseRotaryAsCompass()) getSetUseRotaryAsCompass() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.rotateToGpsOrNull: com.cmd.RotaryPlatform.RotateToGPS?
  get() = if (hasRotateToGps()) getRotateToGps() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.setOriginGpsOrNull: com.cmd.RotaryPlatform.SetOriginGPS?
  get() = if (hasSetOriginGps()) getSetOriginGps() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.setModeOrNull: com.cmd.RotaryPlatform.SetMode?
  get() = if (hasSetMode()) getSetMode() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.rotateToNdcOrNull: com.cmd.RotaryPlatform.RotateToNDC?
  get() = if (hasRotateToNdc()) getRotateToNdc() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanStartOrNull: com.cmd.RotaryPlatform.ScanStart?
  get() = if (hasScanStart()) getScanStart() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanStopOrNull: com.cmd.RotaryPlatform.ScanStop?
  get() = if (hasScanStop()) getScanStop() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanPauseOrNull: com.cmd.RotaryPlatform.ScanPause?
  get() = if (hasScanPause()) getScanPause() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanUnpauseOrNull: com.cmd.RotaryPlatform.ScanUnpause?
  get() = if (hasScanUnpause()) getScanUnpause() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.getMeteoOrNull: com.cmd.RotaryPlatform.GetMeteo?
  get() = if (hasGetMeteo()) getGetMeteo() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanPrevOrNull: com.cmd.RotaryPlatform.ScanPrev?
  get() = if (hasScanPrev()) getScanPrev() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanNextOrNull: com.cmd.RotaryPlatform.ScanNext?
  get() = if (hasScanNext()) getScanNext() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanRefreshNodeListOrNull: com.cmd.RotaryPlatform.ScanRefreshNodeList?
  get() = if (hasScanRefreshNodeList()) getScanRefreshNodeList() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanSelectNodeOrNull: com.cmd.RotaryPlatform.ScanSelectNode?
  get() = if (hasScanSelectNode()) getScanSelectNode() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanDeleteNodeOrNull: com.cmd.RotaryPlatform.ScanDeleteNode?
  get() = if (hasScanDeleteNode()) getScanDeleteNode() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanUpdateNodeOrNull: com.cmd.RotaryPlatform.ScanUpdateNode?
  get() = if (hasScanUpdateNode()) getScanUpdateNode() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.scanAddNodeOrNull: com.cmd.RotaryPlatform.ScanAddNode?
  get() = if (hasScanAddNode()) getScanAddNode() else null

public val com.cmd.RotaryPlatform.RootOrBuilder.haltWithNdcOrNull: com.cmd.RotaryPlatform.HaltWithNDC?
  get() = if (hasHaltWithNdc()) getHaltWithNdc() else null

