// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_cmd_rotary.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cmd.RotaryPlatform;

@kotlin.jvm.JvmName("-initializescanPrev")
public inline fun scanPrev(block: com.cmd.RotaryPlatform.ScanPrevKt.Dsl.() -> kotlin.Unit): com.cmd.RotaryPlatform.ScanPrev =
  com.cmd.RotaryPlatform.ScanPrevKt.Dsl._create(com.cmd.RotaryPlatform.ScanPrev.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `cmd.RotaryPlatform.ScanPrev`
 */
public object ScanPrevKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cmd.RotaryPlatform.ScanPrev.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cmd.RotaryPlatform.ScanPrev.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cmd.RotaryPlatform.ScanPrev = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cmd.RotaryPlatform.ScanPrev.copy(block: `com.cmd.RotaryPlatform`.ScanPrevKt.Dsl.() -> kotlin.Unit): com.cmd.RotaryPlatform.ScanPrev =
  `com.cmd.RotaryPlatform`.ScanPrevKt.Dsl._create(this.toBuilder()).apply { block() }._build()

