// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_cmd_rotary.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cmd.RotaryPlatform;

@kotlin.jvm.JvmName("-initializegetMeteo")
public inline fun getMeteo(block: cmd.RotaryPlatform.GetMeteoKt.Dsl.() -> kotlin.Unit): cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo =
  cmd.RotaryPlatform.GetMeteoKt.Dsl._create(cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `cmd.RotaryPlatform.GetMeteo`
 */
public object GetMeteoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo.copy(block: `cmd.RotaryPlatform`.GetMeteoKt.Dsl.() -> kotlin.Unit): cmd.RotaryPlatform.JonSharedCmdRotary.GetMeteo =
  `cmd.RotaryPlatform`.GetMeteoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

