// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_sych_archive.proto
// Protobuf C++ Version: 5.29.2

#ifndef jon_5fsych_5farchive_2eproto_2epb_2eh
#define jon_5fsych_5farchive_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "buf/validate/validate.pb.h"
#include "jon_video_meta.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_jon_5fsych_5farchive_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_jon_5fsych_5farchive_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_jon_5fsych_5farchive_2eproto;
namespace jon {
namespace archive {
class ArchiveEntry;
struct ArchiveEntryDefaultTypeInternal;
extern ArchiveEntryDefaultTypeInternal _ArchiveEntry_default_instance_;
class OSDReference;
struct OSDReferenceDefaultTypeInternal;
extern OSDReferenceDefaultTypeInternal _OSDReference_default_instance_;
class SychArchiveIndex;
struct SychArchiveIndexDefaultTypeInternal;
extern SychArchiveIndexDefaultTypeInternal _SychArchiveIndex_default_instance_;
class TimelineIndex;
struct TimelineIndexDefaultTypeInternal;
extern TimelineIndexDefaultTypeInternal _TimelineIndex_default_instance_;
class VideoEntry;
struct VideoEntryDefaultTypeInternal;
extern VideoEntryDefaultTypeInternal _VideoEntry_default_instance_;
}  // namespace archive
}  // namespace jon
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace jon {
namespace archive {

// ===================================================================


// -------------------------------------------------------------------

class OSDReference final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:jon.archive.OSDReference) */ {
 public:
  inline OSDReference() : OSDReference(nullptr) {}
  ~OSDReference() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OSDReference* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OSDReference));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OSDReference(
      ::google::protobuf::internal::ConstantInitialized);

  inline OSDReference(const OSDReference& from) : OSDReference(nullptr, from) {}
  inline OSDReference(OSDReference&& from) noexcept
      : OSDReference(nullptr, std::move(from)) {}
  inline OSDReference& operator=(const OSDReference& from) {
    CopyFrom(from);
    return *this;
  }
  inline OSDReference& operator=(OSDReference&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OSDReference& default_instance() {
    return *internal_default_instance();
  }
  static inline const OSDReference* internal_default_instance() {
    return reinterpret_cast<const OSDReference*>(
        &_OSDReference_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(OSDReference& a, OSDReference& b) { a.Swap(&b); }
  inline void Swap(OSDReference* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OSDReference* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OSDReference* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OSDReference>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OSDReference& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OSDReference& from) { OSDReference::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OSDReference* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "jon.archive.OSDReference"; }

 protected:
  explicit OSDReference(::google::protobuf::Arena* arena);
  OSDReference(::google::protobuf::Arena* arena, const OSDReference& from);
  OSDReference(::google::protobuf::Arena* arena, OSDReference&& from) noexcept
      : OSDReference(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPackagePathFieldNumber = 1,
    kConfigPathFieldNumber = 2,
    kPackageNameFieldNumber = 3,
    kPackageVersionFieldNumber = 4,
    kPackageVariantFieldNumber = 5,
  };
  // string package_path = 1 [(.buf.validate.field) = {
  void clear_package_path() ;
  const std::string& package_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_package_path(Arg_&& arg, Args_... args);
  std::string* mutable_package_path();
  PROTOBUF_NODISCARD std::string* release_package_path();
  void set_allocated_package_path(std::string* value);

  private:
  const std::string& _internal_package_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_package_path(
      const std::string& value);
  std::string* _internal_mutable_package_path();

  public:
  // string config_path = 2 [(.buf.validate.field) = {
  void clear_config_path() ;
  const std::string& config_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_config_path(Arg_&& arg, Args_... args);
  std::string* mutable_config_path();
  PROTOBUF_NODISCARD std::string* release_config_path();
  void set_allocated_config_path(std::string* value);

  private:
  const std::string& _internal_config_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_config_path(
      const std::string& value);
  std::string* _internal_mutable_config_path();

  public:
  // string package_name = 3 [(.buf.validate.field) = {
  void clear_package_name() ;
  const std::string& package_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_package_name(Arg_&& arg, Args_... args);
  std::string* mutable_package_name();
  PROTOBUF_NODISCARD std::string* release_package_name();
  void set_allocated_package_name(std::string* value);

  private:
  const std::string& _internal_package_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_package_name(
      const std::string& value);
  std::string* _internal_mutable_package_name();

  public:
  // string package_version = 4 [(.buf.validate.field) = {
  void clear_package_version() ;
  const std::string& package_version() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_package_version(Arg_&& arg, Args_... args);
  std::string* mutable_package_version();
  PROTOBUF_NODISCARD std::string* release_package_version();
  void set_allocated_package_version(std::string* value);

  private:
  const std::string& _internal_package_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_package_version(
      const std::string& value);
  std::string* _internal_mutable_package_version();

  public:
  // string package_variant = 5 [(.buf.validate.field) = {
  void clear_package_variant() ;
  const std::string& package_variant() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_package_variant(Arg_&& arg, Args_... args);
  std::string* mutable_package_variant();
  PROTOBUF_NODISCARD std::string* release_package_variant();
  void set_allocated_package_variant(std::string* value);

  private:
  const std::string& _internal_package_variant() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_package_variant(
      const std::string& value);
  std::string* _internal_mutable_package_variant();

  public:
  // @@protoc_insertion_point(class_scope:jon.archive.OSDReference)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      98, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const OSDReference& from_msg);
    ::google::protobuf::internal::ArenaStringPtr package_path_;
    ::google::protobuf::internal::ArenaStringPtr config_path_;
    ::google::protobuf::internal::ArenaStringPtr package_name_;
    ::google::protobuf::internal::ArenaStringPtr package_version_;
    ::google::protobuf::internal::ArenaStringPtr package_variant_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jon_5fsych_5farchive_2eproto;
};
// -------------------------------------------------------------------

class ArchiveEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:jon.archive.ArchiveEntry) */ {
 public:
  inline ArchiveEntry() : ArchiveEntry(nullptr) {}
  ~ArchiveEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ArchiveEntry* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ArchiveEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ArchiveEntry(
      ::google::protobuf::internal::ConstantInitialized);

  inline ArchiveEntry(const ArchiveEntry& from) : ArchiveEntry(nullptr, from) {}
  inline ArchiveEntry(ArchiveEntry&& from) noexcept
      : ArchiveEntry(nullptr, std::move(from)) {}
  inline ArchiveEntry& operator=(const ArchiveEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArchiveEntry& operator=(ArchiveEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArchiveEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArchiveEntry* internal_default_instance() {
    return reinterpret_cast<const ArchiveEntry*>(
        &_ArchiveEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ArchiveEntry& a, ArchiveEntry& b) { a.Swap(&b); }
  inline void Swap(ArchiveEntry* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArchiveEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArchiveEntry* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ArchiveEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ArchiveEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ArchiveEntry& from) { ArchiveEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ArchiveEntry* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "jon.archive.ArchiveEntry"; }

 protected:
  explicit ArchiveEntry(::google::protobuf::Arena* arena);
  ArchiveEntry(::google::protobuf::Arena* arena, const ArchiveEntry& from);
  ArchiveEntry(::google::protobuf::Arena* arena, ArchiveEntry&& from) noexcept
      : ArchiveEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPathFieldNumber = 1,
    kHeaderOffsetFieldNumber = 2,
    kDataOffsetFieldNumber = 3,
    kSizeFieldNumber = 4,
  };
  // string path = 1 [(.buf.validate.field) = {
  void clear_path() ;
  const std::string& path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* value);

  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(
      const std::string& value);
  std::string* _internal_mutable_path();

  public:
  // uint64 header_offset = 2;
  void clear_header_offset() ;
  ::uint64_t header_offset() const;
  void set_header_offset(::uint64_t value);

  private:
  ::uint64_t _internal_header_offset() const;
  void _internal_set_header_offset(::uint64_t value);

  public:
  // uint64 data_offset = 3;
  void clear_data_offset() ;
  ::uint64_t data_offset() const;
  void set_data_offset(::uint64_t value);

  private:
  ::uint64_t _internal_data_offset() const;
  void _internal_set_data_offset(::uint64_t value);

  public:
  // uint64 size = 4 [(.buf.validate.field) = {
  void clear_size() ;
  ::uint64_t size() const;
  void set_size(::uint64_t value);

  private:
  ::uint64_t _internal_size() const;
  void _internal_set_size(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:jon.archive.ArchiveEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      37, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ArchiveEntry& from_msg);
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::uint64_t header_offset_;
    ::uint64_t data_offset_;
    ::uint64_t size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jon_5fsych_5farchive_2eproto;
};
// -------------------------------------------------------------------

class VideoEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:jon.archive.VideoEntry) */ {
 public:
  inline VideoEntry() : VideoEntry(nullptr) {}
  ~VideoEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VideoEntry* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VideoEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VideoEntry(
      ::google::protobuf::internal::ConstantInitialized);

  inline VideoEntry(const VideoEntry& from) : VideoEntry(nullptr, from) {}
  inline VideoEntry(VideoEntry&& from) noexcept
      : VideoEntry(nullptr, std::move(from)) {}
  inline VideoEntry& operator=(const VideoEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoEntry& operator=(VideoEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VideoEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const VideoEntry* internal_default_instance() {
    return reinterpret_cast<const VideoEntry*>(
        &_VideoEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(VideoEntry& a, VideoEntry& b) { a.Swap(&b); }
  inline void Swap(VideoEntry* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VideoEntry* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VideoEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VideoEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VideoEntry& from) { VideoEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VideoEntry* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "jon.archive.VideoEntry"; }

 protected:
  explicit VideoEntry(::google::protobuf::Arena* arena);
  VideoEntry(::google::protobuf::Arena* arena, const VideoEntry& from);
  VideoEntry(::google::protobuf::Arena* arena, VideoEntry&& from) noexcept
      : VideoEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kArchivePathFieldNumber = 2,
    kThumbnailPathFieldNumber = 3,
    kMetaFieldNumber = 5,
    kGlobalFrameStartFieldNumber = 4,
  };
  // string id = 1 [(.buf.validate.field) = {
  void clear_id() ;
  const std::string& id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* value);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // string archive_path = 2 [(.buf.validate.field) = {
  void clear_archive_path() ;
  const std::string& archive_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_archive_path(Arg_&& arg, Args_... args);
  std::string* mutable_archive_path();
  PROTOBUF_NODISCARD std::string* release_archive_path();
  void set_allocated_archive_path(std::string* value);

  private:
  const std::string& _internal_archive_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_archive_path(
      const std::string& value);
  std::string* _internal_mutable_archive_path();

  public:
  // optional string thumbnail_path = 3;
  bool has_thumbnail_path() const;
  void clear_thumbnail_path() ;
  const std::string& thumbnail_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_thumbnail_path(Arg_&& arg, Args_... args);
  std::string* mutable_thumbnail_path();
  PROTOBUF_NODISCARD std::string* release_thumbnail_path();
  void set_allocated_thumbnail_path(std::string* value);

  private:
  const std::string& _internal_thumbnail_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_thumbnail_path(
      const std::string& value);
  std::string* _internal_mutable_thumbnail_path();

  public:
  // .jon.video.VideoMeta meta = 5 [(.buf.validate.field) = {
  bool has_meta() const;
  void clear_meta() ;
  const ::jon::video::VideoMeta& meta() const;
  PROTOBUF_NODISCARD ::jon::video::VideoMeta* release_meta();
  ::jon::video::VideoMeta* mutable_meta();
  void set_allocated_meta(::jon::video::VideoMeta* value);
  void unsafe_arena_set_allocated_meta(::jon::video::VideoMeta* value);
  ::jon::video::VideoMeta* unsafe_arena_release_meta();

  private:
  const ::jon::video::VideoMeta& _internal_meta() const;
  ::jon::video::VideoMeta* _internal_mutable_meta();

  public:
  // uint32 global_frame_start = 4;
  void clear_global_frame_start() ;
  ::uint32_t global_frame_start() const;
  void set_global_frame_start(::uint32_t value);

  private:
  ::uint32_t _internal_global_frame_start() const;
  void _internal_set_global_frame_start(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:jon.archive.VideoEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 1,
      59, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VideoEntry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr archive_path_;
    ::google::protobuf::internal::ArenaStringPtr thumbnail_path_;
    ::jon::video::VideoMeta* meta_;
    ::uint32_t global_frame_start_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jon_5fsych_5farchive_2eproto;
};
// -------------------------------------------------------------------

class TimelineIndex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:jon.archive.TimelineIndex) */ {
 public:
  inline TimelineIndex() : TimelineIndex(nullptr) {}
  ~TimelineIndex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TimelineIndex* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TimelineIndex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TimelineIndex(
      ::google::protobuf::internal::ConstantInitialized);

  inline TimelineIndex(const TimelineIndex& from) : TimelineIndex(nullptr, from) {}
  inline TimelineIndex(TimelineIndex&& from) noexcept
      : TimelineIndex(nullptr, std::move(from)) {}
  inline TimelineIndex& operator=(const TimelineIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimelineIndex& operator=(TimelineIndex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TimelineIndex& default_instance() {
    return *internal_default_instance();
  }
  static inline const TimelineIndex* internal_default_instance() {
    return reinterpret_cast<const TimelineIndex*>(
        &_TimelineIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TimelineIndex& a, TimelineIndex& b) { a.Swap(&b); }
  inline void Swap(TimelineIndex* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TimelineIndex* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TimelineIndex* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TimelineIndex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TimelineIndex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TimelineIndex& from) { TimelineIndex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TimelineIndex* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "jon.archive.TimelineIndex"; }

 protected:
  explicit TimelineIndex(::google::protobuf::Arena* arena);
  TimelineIndex(::google::protobuf::Arena* arena, const TimelineIndex& from);
  TimelineIndex(::google::protobuf::Arena* arena, TimelineIndex&& from) noexcept
      : TimelineIndex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVideosFieldNumber = 3,
    kTotalFramesFieldNumber = 1,
    kTotalDurationMsFieldNumber = 2,
  };
  // repeated .jon.archive.VideoEntry videos = 3 [(.buf.validate.field) = {
  int videos_size() const;
  private:
  int _internal_videos_size() const;

  public:
  void clear_videos() ;
  ::jon::archive::VideoEntry* mutable_videos(int index);
  ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>* mutable_videos();

  private:
  const ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>& _internal_videos() const;
  ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>* _internal_mutable_videos();
  public:
  const ::jon::archive::VideoEntry& videos(int index) const;
  ::jon::archive::VideoEntry* add_videos();
  const ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>& videos() const;
  // uint32 total_frames = 1 [(.buf.validate.field) = {
  void clear_total_frames() ;
  ::uint32_t total_frames() const;
  void set_total_frames(::uint32_t value);

  private:
  ::uint32_t _internal_total_frames() const;
  void _internal_set_total_frames(::uint32_t value);

  public:
  // uint32 total_duration_ms = 2 [(.buf.validate.field) = {
  void clear_total_duration_ms() ;
  ::uint32_t total_duration_ms() const;
  void set_total_duration_ms(::uint32_t value);

  private:
  ::uint32_t _internal_total_duration_ms() const;
  void _internal_set_total_duration_ms(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:jon.archive.TimelineIndex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TimelineIndex& from_msg);
    ::google::protobuf::RepeatedPtrField< ::jon::archive::VideoEntry > videos_;
    ::uint32_t total_frames_;
    ::uint32_t total_duration_ms_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jon_5fsych_5farchive_2eproto;
};
// -------------------------------------------------------------------

class SychArchiveIndex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:jon.archive.SychArchiveIndex) */ {
 public:
  inline SychArchiveIndex() : SychArchiveIndex(nullptr) {}
  ~SychArchiveIndex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SychArchiveIndex* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SychArchiveIndex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SychArchiveIndex(
      ::google::protobuf::internal::ConstantInitialized);

  inline SychArchiveIndex(const SychArchiveIndex& from) : SychArchiveIndex(nullptr, from) {}
  inline SychArchiveIndex(SychArchiveIndex&& from) noexcept
      : SychArchiveIndex(nullptr, std::move(from)) {}
  inline SychArchiveIndex& operator=(const SychArchiveIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline SychArchiveIndex& operator=(SychArchiveIndex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SychArchiveIndex& default_instance() {
    return *internal_default_instance();
  }
  static inline const SychArchiveIndex* internal_default_instance() {
    return reinterpret_cast<const SychArchiveIndex*>(
        &_SychArchiveIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SychArchiveIndex& a, SychArchiveIndex& b) { a.Swap(&b); }
  inline void Swap(SychArchiveIndex* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SychArchiveIndex* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SychArchiveIndex* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SychArchiveIndex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SychArchiveIndex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SychArchiveIndex& from) { SychArchiveIndex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SychArchiveIndex* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "jon.archive.SychArchiveIndex"; }

 protected:
  explicit SychArchiveIndex(::google::protobuf::Arena* arena);
  SychArchiveIndex(::google::protobuf::Arena* arena, const SychArchiveIndex& from);
  SychArchiveIndex(::google::protobuf::Arena* arena, SychArchiveIndex&& from) noexcept
      : SychArchiveIndex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilesFieldNumber = 4,
    kExportedFromFieldNumber = 3,
    kTimelineFieldNumber = 5,
    kOsdFieldNumber = 6,
    kCreatedAtFieldNumber = 2,
    kVersionFieldNumber = 1,
  };
  // repeated .jon.archive.ArchiveEntry files = 4 [(.buf.validate.field) = {
  int files_size() const;
  private:
  int _internal_files_size() const;

  public:
  void clear_files() ;
  ::jon::archive::ArchiveEntry* mutable_files(int index);
  ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>* mutable_files();

  private:
  const ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>& _internal_files() const;
  ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>* _internal_mutable_files();
  public:
  const ::jon::archive::ArchiveEntry& files(int index) const;
  ::jon::archive::ArchiveEntry* add_files();
  const ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>& files() const;
  // string exported_from = 3 [(.buf.validate.field) = {
  void clear_exported_from() ;
  const std::string& exported_from() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exported_from(Arg_&& arg, Args_... args);
  std::string* mutable_exported_from();
  PROTOBUF_NODISCARD std::string* release_exported_from();
  void set_allocated_exported_from(std::string* value);

  private:
  const std::string& _internal_exported_from() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exported_from(
      const std::string& value);
  std::string* _internal_mutable_exported_from();

  public:
  // .jon.archive.TimelineIndex timeline = 5 [(.buf.validate.field) = {
  bool has_timeline() const;
  void clear_timeline() ;
  const ::jon::archive::TimelineIndex& timeline() const;
  PROTOBUF_NODISCARD ::jon::archive::TimelineIndex* release_timeline();
  ::jon::archive::TimelineIndex* mutable_timeline();
  void set_allocated_timeline(::jon::archive::TimelineIndex* value);
  void unsafe_arena_set_allocated_timeline(::jon::archive::TimelineIndex* value);
  ::jon::archive::TimelineIndex* unsafe_arena_release_timeline();

  private:
  const ::jon::archive::TimelineIndex& _internal_timeline() const;
  ::jon::archive::TimelineIndex* _internal_mutable_timeline();

  public:
  // optional .jon.archive.OSDReference osd = 6;
  bool has_osd() const;
  void clear_osd() ;
  const ::jon::archive::OSDReference& osd() const;
  PROTOBUF_NODISCARD ::jon::archive::OSDReference* release_osd();
  ::jon::archive::OSDReference* mutable_osd();
  void set_allocated_osd(::jon::archive::OSDReference* value);
  void unsafe_arena_set_allocated_osd(::jon::archive::OSDReference* value);
  ::jon::archive::OSDReference* unsafe_arena_release_osd();

  private:
  const ::jon::archive::OSDReference& _internal_osd() const;
  ::jon::archive::OSDReference* _internal_mutable_osd();

  public:
  // uint64 created_at = 2 [(.buf.validate.field) = {
  void clear_created_at() ;
  ::uint64_t created_at() const;
  void set_created_at(::uint64_t value);

  private:
  ::uint64_t _internal_created_at() const;
  void _internal_set_created_at(::uint64_t value);

  public:
  // uint32 version = 1 [(.buf.validate.field) = {
  void clear_version() ;
  ::uint32_t version() const;
  void set_version(::uint32_t value);

  private:
  ::uint32_t _internal_version() const;
  void _internal_set_version(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:jon.archive.SychArchiveIndex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 3,
      50, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SychArchiveIndex& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::jon::archive::ArchiveEntry > files_;
    ::google::protobuf::internal::ArenaStringPtr exported_from_;
    ::jon::archive::TimelineIndex* timeline_;
    ::jon::archive::OSDReference* osd_;
    ::uint64_t created_at_;
    ::uint32_t version_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_jon_5fsych_5farchive_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SychArchiveIndex

// uint32 version = 1 [(.buf.validate.field) = {
inline void SychArchiveIndex::clear_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_ = 0u;
}
inline ::uint32_t SychArchiveIndex::version() const {
  // @@protoc_insertion_point(field_get:jon.archive.SychArchiveIndex.version)
  return _internal_version();
}
inline void SychArchiveIndex::set_version(::uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:jon.archive.SychArchiveIndex.version)
}
inline ::uint32_t SychArchiveIndex::_internal_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.version_;
}
inline void SychArchiveIndex::_internal_set_version(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_ = value;
}

// uint64 created_at = 2 [(.buf.validate.field) = {
inline void SychArchiveIndex::clear_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.created_at_ = ::uint64_t{0u};
}
inline ::uint64_t SychArchiveIndex::created_at() const {
  // @@protoc_insertion_point(field_get:jon.archive.SychArchiveIndex.created_at)
  return _internal_created_at();
}
inline void SychArchiveIndex::set_created_at(::uint64_t value) {
  _internal_set_created_at(value);
  // @@protoc_insertion_point(field_set:jon.archive.SychArchiveIndex.created_at)
}
inline ::uint64_t SychArchiveIndex::_internal_created_at() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.created_at_;
}
inline void SychArchiveIndex::_internal_set_created_at(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.created_at_ = value;
}

// string exported_from = 3 [(.buf.validate.field) = {
inline void SychArchiveIndex::clear_exported_from() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exported_from_.ClearToEmpty();
}
inline const std::string& SychArchiveIndex::exported_from() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.SychArchiveIndex.exported_from)
  return _internal_exported_from();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SychArchiveIndex::set_exported_from(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exported_from_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.SychArchiveIndex.exported_from)
}
inline std::string* SychArchiveIndex::mutable_exported_from() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_exported_from();
  // @@protoc_insertion_point(field_mutable:jon.archive.SychArchiveIndex.exported_from)
  return _s;
}
inline const std::string& SychArchiveIndex::_internal_exported_from() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exported_from_.Get();
}
inline void SychArchiveIndex::_internal_set_exported_from(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exported_from_.Set(value, GetArena());
}
inline std::string* SychArchiveIndex::_internal_mutable_exported_from() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.exported_from_.Mutable( GetArena());
}
inline std::string* SychArchiveIndex::release_exported_from() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.SychArchiveIndex.exported_from)
  return _impl_.exported_from_.Release();
}
inline void SychArchiveIndex::set_allocated_exported_from(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exported_from_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.exported_from_.IsDefault()) {
    _impl_.exported_from_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.SychArchiveIndex.exported_from)
}

// repeated .jon.archive.ArchiveEntry files = 4 [(.buf.validate.field) = {
inline int SychArchiveIndex::_internal_files_size() const {
  return _internal_files().size();
}
inline int SychArchiveIndex::files_size() const {
  return _internal_files_size();
}
inline void SychArchiveIndex::clear_files() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.files_.Clear();
}
inline ::jon::archive::ArchiveEntry* SychArchiveIndex::mutable_files(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:jon.archive.SychArchiveIndex.files)
  return _internal_mutable_files()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>* SychArchiveIndex::mutable_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:jon.archive.SychArchiveIndex.files)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_files();
}
inline const ::jon::archive::ArchiveEntry& SychArchiveIndex::files(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.SychArchiveIndex.files)
  return _internal_files().Get(index);
}
inline ::jon::archive::ArchiveEntry* SychArchiveIndex::add_files() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::jon::archive::ArchiveEntry* _add = _internal_mutable_files()->Add();
  // @@protoc_insertion_point(field_add:jon.archive.SychArchiveIndex.files)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>& SychArchiveIndex::files() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:jon.archive.SychArchiveIndex.files)
  return _internal_files();
}
inline const ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>&
SychArchiveIndex::_internal_files() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.files_;
}
inline ::google::protobuf::RepeatedPtrField<::jon::archive::ArchiveEntry>*
SychArchiveIndex::_internal_mutable_files() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.files_;
}

// .jon.archive.TimelineIndex timeline = 5 [(.buf.validate.field) = {
inline bool SychArchiveIndex::has_timeline() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timeline_ != nullptr);
  return value;
}
inline void SychArchiveIndex::clear_timeline() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timeline_ != nullptr) _impl_.timeline_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::jon::archive::TimelineIndex& SychArchiveIndex::_internal_timeline() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::jon::archive::TimelineIndex* p = _impl_.timeline_;
  return p != nullptr ? *p : reinterpret_cast<const ::jon::archive::TimelineIndex&>(::jon::archive::_TimelineIndex_default_instance_);
}
inline const ::jon::archive::TimelineIndex& SychArchiveIndex::timeline() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.SychArchiveIndex.timeline)
  return _internal_timeline();
}
inline void SychArchiveIndex::unsafe_arena_set_allocated_timeline(::jon::archive::TimelineIndex* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timeline_);
  }
  _impl_.timeline_ = reinterpret_cast<::jon::archive::TimelineIndex*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:jon.archive.SychArchiveIndex.timeline)
}
inline ::jon::archive::TimelineIndex* SychArchiveIndex::release_timeline() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::jon::archive::TimelineIndex* released = _impl_.timeline_;
  _impl_.timeline_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::jon::archive::TimelineIndex* SychArchiveIndex::unsafe_arena_release_timeline() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.SychArchiveIndex.timeline)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::jon::archive::TimelineIndex* temp = _impl_.timeline_;
  _impl_.timeline_ = nullptr;
  return temp;
}
inline ::jon::archive::TimelineIndex* SychArchiveIndex::_internal_mutable_timeline() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timeline_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::jon::archive::TimelineIndex>(GetArena());
    _impl_.timeline_ = reinterpret_cast<::jon::archive::TimelineIndex*>(p);
  }
  return _impl_.timeline_;
}
inline ::jon::archive::TimelineIndex* SychArchiveIndex::mutable_timeline() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::jon::archive::TimelineIndex* _msg = _internal_mutable_timeline();
  // @@protoc_insertion_point(field_mutable:jon.archive.SychArchiveIndex.timeline)
  return _msg;
}
inline void SychArchiveIndex::set_allocated_timeline(::jon::archive::TimelineIndex* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.timeline_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.timeline_ = reinterpret_cast<::jon::archive::TimelineIndex*>(value);
  // @@protoc_insertion_point(field_set_allocated:jon.archive.SychArchiveIndex.timeline)
}

// optional .jon.archive.OSDReference osd = 6;
inline bool SychArchiveIndex::has_osd() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.osd_ != nullptr);
  return value;
}
inline void SychArchiveIndex::clear_osd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.osd_ != nullptr) _impl_.osd_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::jon::archive::OSDReference& SychArchiveIndex::_internal_osd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::jon::archive::OSDReference* p = _impl_.osd_;
  return p != nullptr ? *p : reinterpret_cast<const ::jon::archive::OSDReference&>(::jon::archive::_OSDReference_default_instance_);
}
inline const ::jon::archive::OSDReference& SychArchiveIndex::osd() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.SychArchiveIndex.osd)
  return _internal_osd();
}
inline void SychArchiveIndex::unsafe_arena_set_allocated_osd(::jon::archive::OSDReference* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.osd_);
  }
  _impl_.osd_ = reinterpret_cast<::jon::archive::OSDReference*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:jon.archive.SychArchiveIndex.osd)
}
inline ::jon::archive::OSDReference* SychArchiveIndex::release_osd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::jon::archive::OSDReference* released = _impl_.osd_;
  _impl_.osd_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::jon::archive::OSDReference* SychArchiveIndex::unsafe_arena_release_osd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.SychArchiveIndex.osd)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::jon::archive::OSDReference* temp = _impl_.osd_;
  _impl_.osd_ = nullptr;
  return temp;
}
inline ::jon::archive::OSDReference* SychArchiveIndex::_internal_mutable_osd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.osd_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::jon::archive::OSDReference>(GetArena());
    _impl_.osd_ = reinterpret_cast<::jon::archive::OSDReference*>(p);
  }
  return _impl_.osd_;
}
inline ::jon::archive::OSDReference* SychArchiveIndex::mutable_osd() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::jon::archive::OSDReference* _msg = _internal_mutable_osd();
  // @@protoc_insertion_point(field_mutable:jon.archive.SychArchiveIndex.osd)
  return _msg;
}
inline void SychArchiveIndex::set_allocated_osd(::jon::archive::OSDReference* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.osd_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.osd_ = reinterpret_cast<::jon::archive::OSDReference*>(value);
  // @@protoc_insertion_point(field_set_allocated:jon.archive.SychArchiveIndex.osd)
}

// -------------------------------------------------------------------

// ArchiveEntry

// string path = 1 [(.buf.validate.field) = {
inline void ArchiveEntry::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
}
inline const std::string& ArchiveEntry::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.ArchiveEntry.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ArchiveEntry::set_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.ArchiveEntry.path)
}
inline std::string* ArchiveEntry::mutable_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:jon.archive.ArchiveEntry.path)
  return _s;
}
inline const std::string& ArchiveEntry::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void ArchiveEntry::_internal_set_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(value, GetArena());
}
inline std::string* ArchiveEntry::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.path_.Mutable( GetArena());
}
inline std::string* ArchiveEntry::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.ArchiveEntry.path)
  return _impl_.path_.Release();
}
inline void ArchiveEntry::set_allocated_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.ArchiveEntry.path)
}

// uint64 header_offset = 2;
inline void ArchiveEntry::clear_header_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_offset_ = ::uint64_t{0u};
}
inline ::uint64_t ArchiveEntry::header_offset() const {
  // @@protoc_insertion_point(field_get:jon.archive.ArchiveEntry.header_offset)
  return _internal_header_offset();
}
inline void ArchiveEntry::set_header_offset(::uint64_t value) {
  _internal_set_header_offset(value);
  // @@protoc_insertion_point(field_set:jon.archive.ArchiveEntry.header_offset)
}
inline ::uint64_t ArchiveEntry::_internal_header_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.header_offset_;
}
inline void ArchiveEntry::_internal_set_header_offset(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_offset_ = value;
}

// uint64 data_offset = 3;
inline void ArchiveEntry::clear_data_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_offset_ = ::uint64_t{0u};
}
inline ::uint64_t ArchiveEntry::data_offset() const {
  // @@protoc_insertion_point(field_get:jon.archive.ArchiveEntry.data_offset)
  return _internal_data_offset();
}
inline void ArchiveEntry::set_data_offset(::uint64_t value) {
  _internal_set_data_offset(value);
  // @@protoc_insertion_point(field_set:jon.archive.ArchiveEntry.data_offset)
}
inline ::uint64_t ArchiveEntry::_internal_data_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_offset_;
}
inline void ArchiveEntry::_internal_set_data_offset(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_offset_ = value;
}

// uint64 size = 4 [(.buf.validate.field) = {
inline void ArchiveEntry::clear_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = ::uint64_t{0u};
}
inline ::uint64_t ArchiveEntry::size() const {
  // @@protoc_insertion_point(field_get:jon.archive.ArchiveEntry.size)
  return _internal_size();
}
inline void ArchiveEntry::set_size(::uint64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:jon.archive.ArchiveEntry.size)
}
inline ::uint64_t ArchiveEntry::_internal_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_;
}
inline void ArchiveEntry::_internal_set_size(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = value;
}

// -------------------------------------------------------------------

// TimelineIndex

// uint32 total_frames = 1 [(.buf.validate.field) = {
inline void TimelineIndex::clear_total_frames() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_frames_ = 0u;
}
inline ::uint32_t TimelineIndex::total_frames() const {
  // @@protoc_insertion_point(field_get:jon.archive.TimelineIndex.total_frames)
  return _internal_total_frames();
}
inline void TimelineIndex::set_total_frames(::uint32_t value) {
  _internal_set_total_frames(value);
  // @@protoc_insertion_point(field_set:jon.archive.TimelineIndex.total_frames)
}
inline ::uint32_t TimelineIndex::_internal_total_frames() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_frames_;
}
inline void TimelineIndex::_internal_set_total_frames(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_frames_ = value;
}

// uint32 total_duration_ms = 2 [(.buf.validate.field) = {
inline void TimelineIndex::clear_total_duration_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_duration_ms_ = 0u;
}
inline ::uint32_t TimelineIndex::total_duration_ms() const {
  // @@protoc_insertion_point(field_get:jon.archive.TimelineIndex.total_duration_ms)
  return _internal_total_duration_ms();
}
inline void TimelineIndex::set_total_duration_ms(::uint32_t value) {
  _internal_set_total_duration_ms(value);
  // @@protoc_insertion_point(field_set:jon.archive.TimelineIndex.total_duration_ms)
}
inline ::uint32_t TimelineIndex::_internal_total_duration_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_duration_ms_;
}
inline void TimelineIndex::_internal_set_total_duration_ms(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_duration_ms_ = value;
}

// repeated .jon.archive.VideoEntry videos = 3 [(.buf.validate.field) = {
inline int TimelineIndex::_internal_videos_size() const {
  return _internal_videos().size();
}
inline int TimelineIndex::videos_size() const {
  return _internal_videos_size();
}
inline void TimelineIndex::clear_videos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.videos_.Clear();
}
inline ::jon::archive::VideoEntry* TimelineIndex::mutable_videos(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:jon.archive.TimelineIndex.videos)
  return _internal_mutable_videos()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>* TimelineIndex::mutable_videos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:jon.archive.TimelineIndex.videos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_videos();
}
inline const ::jon::archive::VideoEntry& TimelineIndex::videos(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.TimelineIndex.videos)
  return _internal_videos().Get(index);
}
inline ::jon::archive::VideoEntry* TimelineIndex::add_videos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::jon::archive::VideoEntry* _add = _internal_mutable_videos()->Add();
  // @@protoc_insertion_point(field_add:jon.archive.TimelineIndex.videos)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>& TimelineIndex::videos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:jon.archive.TimelineIndex.videos)
  return _internal_videos();
}
inline const ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>&
TimelineIndex::_internal_videos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.videos_;
}
inline ::google::protobuf::RepeatedPtrField<::jon::archive::VideoEntry>*
TimelineIndex::_internal_mutable_videos() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.videos_;
}

// -------------------------------------------------------------------

// VideoEntry

// string id = 1 [(.buf.validate.field) = {
inline void VideoEntry::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
}
inline const std::string& VideoEntry::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.VideoEntry.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoEntry::set_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.VideoEntry.id)
}
inline std::string* VideoEntry::mutable_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:jon.archive.VideoEntry.id)
  return _s;
}
inline const std::string& VideoEntry::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void VideoEntry::_internal_set_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline std::string* VideoEntry::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline std::string* VideoEntry::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.VideoEntry.id)
  return _impl_.id_.Release();
}
inline void VideoEntry::set_allocated_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.VideoEntry.id)
}

// string archive_path = 2 [(.buf.validate.field) = {
inline void VideoEntry::clear_archive_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.archive_path_.ClearToEmpty();
}
inline const std::string& VideoEntry::archive_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.VideoEntry.archive_path)
  return _internal_archive_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoEntry::set_archive_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.archive_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.VideoEntry.archive_path)
}
inline std::string* VideoEntry::mutable_archive_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_archive_path();
  // @@protoc_insertion_point(field_mutable:jon.archive.VideoEntry.archive_path)
  return _s;
}
inline const std::string& VideoEntry::_internal_archive_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.archive_path_.Get();
}
inline void VideoEntry::_internal_set_archive_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.archive_path_.Set(value, GetArena());
}
inline std::string* VideoEntry::_internal_mutable_archive_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.archive_path_.Mutable( GetArena());
}
inline std::string* VideoEntry::release_archive_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.VideoEntry.archive_path)
  return _impl_.archive_path_.Release();
}
inline void VideoEntry::set_allocated_archive_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.archive_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.archive_path_.IsDefault()) {
    _impl_.archive_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.VideoEntry.archive_path)
}

// optional string thumbnail_path = 3;
inline bool VideoEntry::has_thumbnail_path() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void VideoEntry::clear_thumbnail_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thumbnail_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& VideoEntry::thumbnail_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.VideoEntry.thumbnail_path)
  return _internal_thumbnail_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoEntry::set_thumbnail_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.thumbnail_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.VideoEntry.thumbnail_path)
}
inline std::string* VideoEntry::mutable_thumbnail_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_thumbnail_path();
  // @@protoc_insertion_point(field_mutable:jon.archive.VideoEntry.thumbnail_path)
  return _s;
}
inline const std::string& VideoEntry::_internal_thumbnail_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.thumbnail_path_.Get();
}
inline void VideoEntry::_internal_set_thumbnail_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.thumbnail_path_.Set(value, GetArena());
}
inline std::string* VideoEntry::_internal_mutable_thumbnail_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.thumbnail_path_.Mutable( GetArena());
}
inline std::string* VideoEntry::release_thumbnail_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.VideoEntry.thumbnail_path)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.thumbnail_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.thumbnail_path_.Set("", GetArena());
  }
  return released;
}
inline void VideoEntry::set_allocated_thumbnail_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.thumbnail_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.thumbnail_path_.IsDefault()) {
    _impl_.thumbnail_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.VideoEntry.thumbnail_path)
}

// uint32 global_frame_start = 4;
inline void VideoEntry::clear_global_frame_start() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.global_frame_start_ = 0u;
}
inline ::uint32_t VideoEntry::global_frame_start() const {
  // @@protoc_insertion_point(field_get:jon.archive.VideoEntry.global_frame_start)
  return _internal_global_frame_start();
}
inline void VideoEntry::set_global_frame_start(::uint32_t value) {
  _internal_set_global_frame_start(value);
  // @@protoc_insertion_point(field_set:jon.archive.VideoEntry.global_frame_start)
}
inline ::uint32_t VideoEntry::_internal_global_frame_start() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.global_frame_start_;
}
inline void VideoEntry::_internal_set_global_frame_start(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.global_frame_start_ = value;
}

// .jon.video.VideoMeta meta = 5 [(.buf.validate.field) = {
inline bool VideoEntry::has_meta() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.meta_ != nullptr);
  return value;
}
inline const ::jon::video::VideoMeta& VideoEntry::_internal_meta() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::jon::video::VideoMeta* p = _impl_.meta_;
  return p != nullptr ? *p : reinterpret_cast<const ::jon::video::VideoMeta&>(::jon::video::_VideoMeta_default_instance_);
}
inline const ::jon::video::VideoMeta& VideoEntry::meta() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.VideoEntry.meta)
  return _internal_meta();
}
inline void VideoEntry::unsafe_arena_set_allocated_meta(::jon::video::VideoMeta* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.meta_);
  }
  _impl_.meta_ = reinterpret_cast<::jon::video::VideoMeta*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:jon.archive.VideoEntry.meta)
}
inline ::jon::video::VideoMeta* VideoEntry::release_meta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::jon::video::VideoMeta* released = _impl_.meta_;
  _impl_.meta_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::jon::video::VideoMeta* VideoEntry::unsafe_arena_release_meta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.VideoEntry.meta)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::jon::video::VideoMeta* temp = _impl_.meta_;
  _impl_.meta_ = nullptr;
  return temp;
}
inline ::jon::video::VideoMeta* VideoEntry::_internal_mutable_meta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.meta_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::jon::video::VideoMeta>(GetArena());
    _impl_.meta_ = reinterpret_cast<::jon::video::VideoMeta*>(p);
  }
  return _impl_.meta_;
}
inline ::jon::video::VideoMeta* VideoEntry::mutable_meta() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::jon::video::VideoMeta* _msg = _internal_mutable_meta();
  // @@protoc_insertion_point(field_mutable:jon.archive.VideoEntry.meta)
  return _msg;
}
inline void VideoEntry::set_allocated_meta(::jon::video::VideoMeta* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.meta_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.meta_ = reinterpret_cast<::jon::video::VideoMeta*>(value);
  // @@protoc_insertion_point(field_set_allocated:jon.archive.VideoEntry.meta)
}

// -------------------------------------------------------------------

// OSDReference

// string package_path = 1 [(.buf.validate.field) = {
inline void OSDReference::clear_package_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_path_.ClearToEmpty();
}
inline const std::string& OSDReference::package_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.OSDReference.package_path)
  return _internal_package_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OSDReference::set_package_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.OSDReference.package_path)
}
inline std::string* OSDReference::mutable_package_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_package_path();
  // @@protoc_insertion_point(field_mutable:jon.archive.OSDReference.package_path)
  return _s;
}
inline const std::string& OSDReference::_internal_package_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_path_.Get();
}
inline void OSDReference::_internal_set_package_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_path_.Set(value, GetArena());
}
inline std::string* OSDReference::_internal_mutable_package_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.package_path_.Mutable( GetArena());
}
inline std::string* OSDReference::release_package_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.OSDReference.package_path)
  return _impl_.package_path_.Release();
}
inline void OSDReference::set_allocated_package_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.package_path_.IsDefault()) {
    _impl_.package_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.OSDReference.package_path)
}

// string config_path = 2 [(.buf.validate.field) = {
inline void OSDReference::clear_config_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.config_path_.ClearToEmpty();
}
inline const std::string& OSDReference::config_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.OSDReference.config_path)
  return _internal_config_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OSDReference::set_config_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.config_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.OSDReference.config_path)
}
inline std::string* OSDReference::mutable_config_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_config_path();
  // @@protoc_insertion_point(field_mutable:jon.archive.OSDReference.config_path)
  return _s;
}
inline const std::string& OSDReference::_internal_config_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.config_path_.Get();
}
inline void OSDReference::_internal_set_config_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.config_path_.Set(value, GetArena());
}
inline std::string* OSDReference::_internal_mutable_config_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.config_path_.Mutable( GetArena());
}
inline std::string* OSDReference::release_config_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.OSDReference.config_path)
  return _impl_.config_path_.Release();
}
inline void OSDReference::set_allocated_config_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.config_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.config_path_.IsDefault()) {
    _impl_.config_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.OSDReference.config_path)
}

// string package_name = 3 [(.buf.validate.field) = {
inline void OSDReference::clear_package_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_name_.ClearToEmpty();
}
inline const std::string& OSDReference::package_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.OSDReference.package_name)
  return _internal_package_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OSDReference::set_package_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.OSDReference.package_name)
}
inline std::string* OSDReference::mutable_package_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_package_name();
  // @@protoc_insertion_point(field_mutable:jon.archive.OSDReference.package_name)
  return _s;
}
inline const std::string& OSDReference::_internal_package_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_name_.Get();
}
inline void OSDReference::_internal_set_package_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_name_.Set(value, GetArena());
}
inline std::string* OSDReference::_internal_mutable_package_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.package_name_.Mutable( GetArena());
}
inline std::string* OSDReference::release_package_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.OSDReference.package_name)
  return _impl_.package_name_.Release();
}
inline void OSDReference::set_allocated_package_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.package_name_.IsDefault()) {
    _impl_.package_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.OSDReference.package_name)
}

// string package_version = 4 [(.buf.validate.field) = {
inline void OSDReference::clear_package_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_version_.ClearToEmpty();
}
inline const std::string& OSDReference::package_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.OSDReference.package_version)
  return _internal_package_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OSDReference::set_package_version(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.OSDReference.package_version)
}
inline std::string* OSDReference::mutable_package_version() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_package_version();
  // @@protoc_insertion_point(field_mutable:jon.archive.OSDReference.package_version)
  return _s;
}
inline const std::string& OSDReference::_internal_package_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_version_.Get();
}
inline void OSDReference::_internal_set_package_version(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_version_.Set(value, GetArena());
}
inline std::string* OSDReference::_internal_mutable_package_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.package_version_.Mutable( GetArena());
}
inline std::string* OSDReference::release_package_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.OSDReference.package_version)
  return _impl_.package_version_.Release();
}
inline void OSDReference::set_allocated_package_version(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.package_version_.IsDefault()) {
    _impl_.package_version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.OSDReference.package_version)
}

// string package_variant = 5 [(.buf.validate.field) = {
inline void OSDReference::clear_package_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_variant_.ClearToEmpty();
}
inline const std::string& OSDReference::package_variant() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:jon.archive.OSDReference.package_variant)
  return _internal_package_variant();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OSDReference::set_package_variant(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_variant_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:jon.archive.OSDReference.package_variant)
}
inline std::string* OSDReference::mutable_package_variant() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_package_variant();
  // @@protoc_insertion_point(field_mutable:jon.archive.OSDReference.package_variant)
  return _s;
}
inline const std::string& OSDReference::_internal_package_variant() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.package_variant_.Get();
}
inline void OSDReference::_internal_set_package_variant(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_variant_.Set(value, GetArena());
}
inline std::string* OSDReference::_internal_mutable_package_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.package_variant_.Mutable( GetArena());
}
inline std::string* OSDReference::release_package_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:jon.archive.OSDReference.package_variant)
  return _impl_.package_variant_.Release();
}
inline void OSDReference::set_allocated_package_variant(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.package_variant_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.package_variant_.IsDefault()) {
    _impl_.package_variant_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:jon.archive.OSDReference.package_variant)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace archive
}  // namespace jon


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // jon_5fsych_5farchive_2eproto_2epb_2eh
