syntax = "proto3";

option go_package = "git-codecommit.eu-central-1.amazonaws.com/v1/repos/jettison/jonp/data/pmu";

package ser;

import "jon_shared_data_types.proto";

message JonGuiDataPMU {
  double temperature = 1 [(buf.validate.field).double = {
    gte: -273.15,  // Absolute zero in Celsius
    lte: 660.32,   // Melting point of aluminum in Celsius
    example: [-20, 0, 25, 100]
  }];
  reserved 2;  // was: status
  bool is_started = 3;
  JonGuiDataMeteo meteo = 4;
  double voltage = 5 [(buf.validate.field).double = {
    gte: 2.0,
    lte: 60.0
  }];
  bool heater_power_state = 6;
}
