// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_data_heater.proto
// Protobuf Java Version: 4.29.2

package ser;

public final class JonSharedDataHeater {
  private JonSharedDataHeater() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      JonSharedDataHeater.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JonGuiDataHeaterChannelStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.JonGuiDataHeaterChannelStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float temperature = 1;</code>
     * @return The temperature.
     */
    float getTemperature();

    /**
     * <code>float applied_voltage_V = 2 [(.buf.validate.field) = { ... }</code>
     * @return The appliedVoltageV.
     */
    float getAppliedVoltageV();

    /**
     * <code>float target_voltage_V = 3 [(.buf.validate.field) = { ... }</code>
     * @return The targetVoltageV.
     */
    float getTargetVoltageV();

    /**
     * <code>bool enabled = 4;</code>
     * @return The enabled.
     */
    boolean getEnabled();
  }
  /**
   * <pre>
   * HeaterChannelStatus represents the state of a single heating channel
   * </pre>
   *
   * Protobuf type {@code ser.JonGuiDataHeaterChannelStatus}
   */
  public static final class JonGuiDataHeaterChannelStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ser.JonGuiDataHeaterChannelStatus)
      JonGuiDataHeaterChannelStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        JonGuiDataHeaterChannelStatus.class.getName());
    }
    // Use JonGuiDataHeaterChannelStatus.newBuilder() to construct.
    private JonGuiDataHeaterChannelStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataHeaterChannelStatus() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeaterChannelStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeaterChannelStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.class, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder.class);
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 1;
    private float temperature_ = 0F;
    /**
     * <code>float temperature = 1;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }

    public static final int APPLIED_VOLTAGE_V_FIELD_NUMBER = 2;
    private float appliedVoltageV_ = 0F;
    /**
     * <code>float applied_voltage_V = 2 [(.buf.validate.field) = { ... }</code>
     * @return The appliedVoltageV.
     */
    @java.lang.Override
    public float getAppliedVoltageV() {
      return appliedVoltageV_;
    }

    public static final int TARGET_VOLTAGE_V_FIELD_NUMBER = 3;
    private float targetVoltageV_ = 0F;
    /**
     * <code>float target_voltage_V = 3 [(.buf.validate.field) = { ... }</code>
     * @return The targetVoltageV.
     */
    @java.lang.Override
    public float getTargetVoltageV() {
      return targetVoltageV_;
    }

    public static final int ENABLED_FIELD_NUMBER = 4;
    private boolean enabled_ = false;
    /**
     * <code>bool enabled = 4;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
        output.writeFloat(1, temperature_);
      }
      if (java.lang.Float.floatToRawIntBits(appliedVoltageV_) != 0) {
        output.writeFloat(2, appliedVoltageV_);
      }
      if (java.lang.Float.floatToRawIntBits(targetVoltageV_) != 0) {
        output.writeFloat(3, targetVoltageV_);
      }
      if (enabled_ != false) {
        output.writeBool(4, enabled_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, temperature_);
      }
      if (java.lang.Float.floatToRawIntBits(appliedVoltageV_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, appliedVoltageV_);
      }
      if (java.lang.Float.floatToRawIntBits(targetVoltageV_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, targetVoltageV_);
      }
      if (enabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, enabled_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus)) {
        return super.equals(obj);
      }
      ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus other = (ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus) obj;

      if (java.lang.Float.floatToIntBits(getTemperature())
          != java.lang.Float.floatToIntBits(
              other.getTemperature())) return false;
      if (java.lang.Float.floatToIntBits(getAppliedVoltageV())
          != java.lang.Float.floatToIntBits(
              other.getAppliedVoltageV())) return false;
      if (java.lang.Float.floatToIntBits(getTargetVoltageV())
          != java.lang.Float.floatToIntBits(
              other.getTargetVoltageV())) return false;
      if (getEnabled()
          != other.getEnabled()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
      hash = (37 * hash) + APPLIED_VOLTAGE_V_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAppliedVoltageV());
      hash = (37 * hash) + TARGET_VOLTAGE_V_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTargetVoltageV());
      hash = (37 * hash) + ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnabled());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * HeaterChannelStatus represents the state of a single heating channel
     * </pre>
     *
     * Protobuf type {@code ser.JonGuiDataHeaterChannelStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.JonGuiDataHeaterChannelStatus)
        ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeaterChannelStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeaterChannelStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.class, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder.class);
      }

      // Construct using ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        temperature_ = 0F;
        appliedVoltageV_ = 0F;
        targetVoltageV_ = 0F;
        enabled_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeaterChannelStatus_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getDefaultInstanceForType() {
        return ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus build() {
        ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus buildPartial() {
        ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus result = new ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.temperature_ = temperature_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.appliedVoltageV_ = appliedVoltageV_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.targetVoltageV_ = targetVoltageV_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.enabled_ = enabled_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus) {
          return mergeFrom((ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus other) {
        if (other == ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance()) return this;
        if (other.getTemperature() != 0F) {
          setTemperature(other.getTemperature());
        }
        if (other.getAppliedVoltageV() != 0F) {
          setAppliedVoltageV(other.getAppliedVoltageV());
        }
        if (other.getTargetVoltageV() != 0F) {
          setTargetVoltageV(other.getTargetVoltageV());
        }
        if (other.getEnabled() != false) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                temperature_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                appliedVoltageV_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                targetVoltageV_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 32: {
                enabled_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float temperature_ ;
      /**
       * <code>float temperature = 1;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>float temperature = 1;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(float value) {

        temperature_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000001);
        temperature_ = 0F;
        onChanged();
        return this;
      }

      private float appliedVoltageV_ ;
      /**
       * <code>float applied_voltage_V = 2 [(.buf.validate.field) = { ... }</code>
       * @return The appliedVoltageV.
       */
      @java.lang.Override
      public float getAppliedVoltageV() {
        return appliedVoltageV_;
      }
      /**
       * <code>float applied_voltage_V = 2 [(.buf.validate.field) = { ... }</code>
       * @param value The appliedVoltageV to set.
       * @return This builder for chaining.
       */
      public Builder setAppliedVoltageV(float value) {

        appliedVoltageV_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float applied_voltage_V = 2 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearAppliedVoltageV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appliedVoltageV_ = 0F;
        onChanged();
        return this;
      }

      private float targetVoltageV_ ;
      /**
       * <code>float target_voltage_V = 3 [(.buf.validate.field) = { ... }</code>
       * @return The targetVoltageV.
       */
      @java.lang.Override
      public float getTargetVoltageV() {
        return targetVoltageV_;
      }
      /**
       * <code>float target_voltage_V = 3 [(.buf.validate.field) = { ... }</code>
       * @param value The targetVoltageV to set.
       * @return This builder for chaining.
       */
      public Builder setTargetVoltageV(float value) {

        targetVoltageV_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float target_voltage_V = 3 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetVoltageV() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetVoltageV_ = 0F;
        onChanged();
        return this;
      }

      private boolean enabled_ ;
      /**
       * <code>bool enabled = 4;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>bool enabled = 4;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {

        enabled_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool enabled = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000008);
        enabled_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ser.JonGuiDataHeaterChannelStatus)
    }

    // @@protoc_insertion_point(class_scope:ser.JonGuiDataHeaterChannelStatus)
    private static final ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus();
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataHeaterChannelStatus>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataHeaterChannelStatus>() {
      @java.lang.Override
      public JonGuiDataHeaterChannelStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataHeaterChannelStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataHeaterChannelStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JonGuiDataHeaterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.JonGuiDataHeater)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float bus_voltage_V = 1 [(.buf.validate.field) = { ... }</code>
     * @return The busVoltageV.
     */
    float getBusVoltageV();

    /**
     * <code>float current_A = 2 [(.buf.validate.field) = { ... }</code>
     * @return The currentA.
     */
    float getCurrentA();

    /**
     * <code>float power_W = 3 [(.buf.validate.field) = { ... }</code>
     * @return The powerW.
     */
    float getPowerW();

    /**
     * <pre>
     * Day camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
     * @return Whether the channel0 field is set.
     */
    boolean hasChannel0();
    /**
     * <pre>
     * Day camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
     * @return The channel0.
     */
    ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel0();
    /**
     * <pre>
     * Day camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
     */
    ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel0OrBuilder();

    /**
     * <pre>
     * LRF glass (15W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
     * @return Whether the channel1 field is set.
     */
    boolean hasChannel1();
    /**
     * <pre>
     * LRF glass (15W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
     * @return The channel1.
     */
    ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel1();
    /**
     * <pre>
     * LRF glass (15W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
     */
    ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel1OrBuilder();

    /**
     * <pre>
     * Heat camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
     * @return Whether the channel2 field is set.
     */
    boolean hasChannel2();
    /**
     * <pre>
     * Heat camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
     * @return The channel2.
     */
    ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel2();
    /**
     * <pre>
     * Heat camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
     */
    ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel2OrBuilder();

    /**
     * <code>bool automatic_control_enabled = 7;</code>
     * @return The automaticControlEnabled.
     */
    boolean getAutomaticControlEnabled();

    /**
     * <pre>
     * Target temperatures for PID control (persisted via state storage)
     * </pre>
     *
     * <code>float target_temp_channel_0 = 8 [(.buf.validate.field) = { ... }</code>
     * @return The targetTempChannel0.
     */
    float getTargetTempChannel0();

    /**
     * <code>float target_temp_channel_1 = 9 [(.buf.validate.field) = { ... }</code>
     * @return The targetTempChannel1.
     */
    float getTargetTempChannel1();

    /**
     * <code>float target_temp_channel_2 = 10 [(.buf.validate.field) = { ... }</code>
     * @return The targetTempChannel2.
     */
    float getTargetTempChannel2();
  }
  /**
   * <pre>
   * JonGuiDataHeater contains the complete heater subsystem status
   * </pre>
   *
   * Protobuf type {@code ser.JonGuiDataHeater}
   */
  public static final class JonGuiDataHeater extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ser.JonGuiDataHeater)
      JonGuiDataHeaterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        JonGuiDataHeater.class.getName());
    }
    // Use JonGuiDataHeater.newBuilder() to construct.
    private JonGuiDataHeater(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataHeater() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeater_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeater_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataHeater.JonGuiDataHeater.class, ser.JonSharedDataHeater.JonGuiDataHeater.Builder.class);
    }

    private int bitField0_;
    public static final int BUS_VOLTAGE_V_FIELD_NUMBER = 1;
    private float busVoltageV_ = 0F;
    /**
     * <code>float bus_voltage_V = 1 [(.buf.validate.field) = { ... }</code>
     * @return The busVoltageV.
     */
    @java.lang.Override
    public float getBusVoltageV() {
      return busVoltageV_;
    }

    public static final int CURRENT_A_FIELD_NUMBER = 2;
    private float currentA_ = 0F;
    /**
     * <code>float current_A = 2 [(.buf.validate.field) = { ... }</code>
     * @return The currentA.
     */
    @java.lang.Override
    public float getCurrentA() {
      return currentA_;
    }

    public static final int POWER_W_FIELD_NUMBER = 3;
    private float powerW_ = 0F;
    /**
     * <code>float power_W = 3 [(.buf.validate.field) = { ... }</code>
     * @return The powerW.
     */
    @java.lang.Override
    public float getPowerW() {
      return powerW_;
    }

    public static final int CHANNEL_0_FIELD_NUMBER = 4;
    private ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus channel0_;
    /**
     * <pre>
     * Day camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
     * @return Whether the channel0 field is set.
     */
    @java.lang.Override
    public boolean hasChannel0() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Day camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
     * @return The channel0.
     */
    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel0() {
      return channel0_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel0_;
    }
    /**
     * <pre>
     * Day camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
     */
    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel0OrBuilder() {
      return channel0_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel0_;
    }

    public static final int CHANNEL_1_FIELD_NUMBER = 5;
    private ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus channel1_;
    /**
     * <pre>
     * LRF glass (15W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
     * @return Whether the channel1 field is set.
     */
    @java.lang.Override
    public boolean hasChannel1() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * LRF glass (15W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
     * @return The channel1.
     */
    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel1() {
      return channel1_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel1_;
    }
    /**
     * <pre>
     * LRF glass (15W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
     */
    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel1OrBuilder() {
      return channel1_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel1_;
    }

    public static final int CHANNEL_2_FIELD_NUMBER = 6;
    private ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus channel2_;
    /**
     * <pre>
     * Heat camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
     * @return Whether the channel2 field is set.
     */
    @java.lang.Override
    public boolean hasChannel2() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Heat camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
     * @return The channel2.
     */
    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel2() {
      return channel2_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel2_;
    }
    /**
     * <pre>
     * Heat camera glass (60W)
     * </pre>
     *
     * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
     */
    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel2OrBuilder() {
      return channel2_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel2_;
    }

    public static final int AUTOMATIC_CONTROL_ENABLED_FIELD_NUMBER = 7;
    private boolean automaticControlEnabled_ = false;
    /**
     * <code>bool automatic_control_enabled = 7;</code>
     * @return The automaticControlEnabled.
     */
    @java.lang.Override
    public boolean getAutomaticControlEnabled() {
      return automaticControlEnabled_;
    }

    public static final int TARGET_TEMP_CHANNEL_0_FIELD_NUMBER = 8;
    private float targetTempChannel0_ = 0F;
    /**
     * <pre>
     * Target temperatures for PID control (persisted via state storage)
     * </pre>
     *
     * <code>float target_temp_channel_0 = 8 [(.buf.validate.field) = { ... }</code>
     * @return The targetTempChannel0.
     */
    @java.lang.Override
    public float getTargetTempChannel0() {
      return targetTempChannel0_;
    }

    public static final int TARGET_TEMP_CHANNEL_1_FIELD_NUMBER = 9;
    private float targetTempChannel1_ = 0F;
    /**
     * <code>float target_temp_channel_1 = 9 [(.buf.validate.field) = { ... }</code>
     * @return The targetTempChannel1.
     */
    @java.lang.Override
    public float getTargetTempChannel1() {
      return targetTempChannel1_;
    }

    public static final int TARGET_TEMP_CHANNEL_2_FIELD_NUMBER = 10;
    private float targetTempChannel2_ = 0F;
    /**
     * <code>float target_temp_channel_2 = 10 [(.buf.validate.field) = { ... }</code>
     * @return The targetTempChannel2.
     */
    @java.lang.Override
    public float getTargetTempChannel2() {
      return targetTempChannel2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(busVoltageV_) != 0) {
        output.writeFloat(1, busVoltageV_);
      }
      if (java.lang.Float.floatToRawIntBits(currentA_) != 0) {
        output.writeFloat(2, currentA_);
      }
      if (java.lang.Float.floatToRawIntBits(powerW_) != 0) {
        output.writeFloat(3, powerW_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getChannel0());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(5, getChannel1());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(6, getChannel2());
      }
      if (automaticControlEnabled_ != false) {
        output.writeBool(7, automaticControlEnabled_);
      }
      if (java.lang.Float.floatToRawIntBits(targetTempChannel0_) != 0) {
        output.writeFloat(8, targetTempChannel0_);
      }
      if (java.lang.Float.floatToRawIntBits(targetTempChannel1_) != 0) {
        output.writeFloat(9, targetTempChannel1_);
      }
      if (java.lang.Float.floatToRawIntBits(targetTempChannel2_) != 0) {
        output.writeFloat(10, targetTempChannel2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(busVoltageV_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, busVoltageV_);
      }
      if (java.lang.Float.floatToRawIntBits(currentA_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, currentA_);
      }
      if (java.lang.Float.floatToRawIntBits(powerW_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, powerW_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getChannel0());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getChannel1());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getChannel2());
      }
      if (automaticControlEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, automaticControlEnabled_);
      }
      if (java.lang.Float.floatToRawIntBits(targetTempChannel0_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, targetTempChannel0_);
      }
      if (java.lang.Float.floatToRawIntBits(targetTempChannel1_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, targetTempChannel1_);
      }
      if (java.lang.Float.floatToRawIntBits(targetTempChannel2_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, targetTempChannel2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataHeater.JonGuiDataHeater)) {
        return super.equals(obj);
      }
      ser.JonSharedDataHeater.JonGuiDataHeater other = (ser.JonSharedDataHeater.JonGuiDataHeater) obj;

      if (java.lang.Float.floatToIntBits(getBusVoltageV())
          != java.lang.Float.floatToIntBits(
              other.getBusVoltageV())) return false;
      if (java.lang.Float.floatToIntBits(getCurrentA())
          != java.lang.Float.floatToIntBits(
              other.getCurrentA())) return false;
      if (java.lang.Float.floatToIntBits(getPowerW())
          != java.lang.Float.floatToIntBits(
              other.getPowerW())) return false;
      if (hasChannel0() != other.hasChannel0()) return false;
      if (hasChannel0()) {
        if (!getChannel0()
            .equals(other.getChannel0())) return false;
      }
      if (hasChannel1() != other.hasChannel1()) return false;
      if (hasChannel1()) {
        if (!getChannel1()
            .equals(other.getChannel1())) return false;
      }
      if (hasChannel2() != other.hasChannel2()) return false;
      if (hasChannel2()) {
        if (!getChannel2()
            .equals(other.getChannel2())) return false;
      }
      if (getAutomaticControlEnabled()
          != other.getAutomaticControlEnabled()) return false;
      if (java.lang.Float.floatToIntBits(getTargetTempChannel0())
          != java.lang.Float.floatToIntBits(
              other.getTargetTempChannel0())) return false;
      if (java.lang.Float.floatToIntBits(getTargetTempChannel1())
          != java.lang.Float.floatToIntBits(
              other.getTargetTempChannel1())) return false;
      if (java.lang.Float.floatToIntBits(getTargetTempChannel2())
          != java.lang.Float.floatToIntBits(
              other.getTargetTempChannel2())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUS_VOLTAGE_V_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBusVoltageV());
      hash = (37 * hash) + CURRENT_A_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCurrentA());
      hash = (37 * hash) + POWER_W_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPowerW());
      if (hasChannel0()) {
        hash = (37 * hash) + CHANNEL_0_FIELD_NUMBER;
        hash = (53 * hash) + getChannel0().hashCode();
      }
      if (hasChannel1()) {
        hash = (37 * hash) + CHANNEL_1_FIELD_NUMBER;
        hash = (53 * hash) + getChannel1().hashCode();
      }
      if (hasChannel2()) {
        hash = (37 * hash) + CHANNEL_2_FIELD_NUMBER;
        hash = (53 * hash) + getChannel2().hashCode();
      }
      hash = (37 * hash) + AUTOMATIC_CONTROL_ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutomaticControlEnabled());
      hash = (37 * hash) + TARGET_TEMP_CHANNEL_0_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTargetTempChannel0());
      hash = (37 * hash) + TARGET_TEMP_CHANNEL_1_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTargetTempChannel1());
      hash = (37 * hash) + TARGET_TEMP_CHANNEL_2_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTargetTempChannel2());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeater parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeater parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataHeater.JonGuiDataHeater parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataHeater.JonGuiDataHeater prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * JonGuiDataHeater contains the complete heater subsystem status
     * </pre>
     *
     * Protobuf type {@code ser.JonGuiDataHeater}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.JonGuiDataHeater)
        ser.JonSharedDataHeater.JonGuiDataHeaterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeater_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeater_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataHeater.JonGuiDataHeater.class, ser.JonSharedDataHeater.JonGuiDataHeater.Builder.class);
      }

      // Construct using ser.JonSharedDataHeater.JonGuiDataHeater.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getChannel0FieldBuilder();
          getChannel1FieldBuilder();
          getChannel2FieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        busVoltageV_ = 0F;
        currentA_ = 0F;
        powerW_ = 0F;
        channel0_ = null;
        if (channel0Builder_ != null) {
          channel0Builder_.dispose();
          channel0Builder_ = null;
        }
        channel1_ = null;
        if (channel1Builder_ != null) {
          channel1Builder_.dispose();
          channel1Builder_ = null;
        }
        channel2_ = null;
        if (channel2Builder_ != null) {
          channel2Builder_.dispose();
          channel2Builder_ = null;
        }
        automaticControlEnabled_ = false;
        targetTempChannel0_ = 0F;
        targetTempChannel1_ = 0F;
        targetTempChannel2_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataHeater.internal_static_ser_JonGuiDataHeater_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataHeater.JonGuiDataHeater getDefaultInstanceForType() {
        return ser.JonSharedDataHeater.JonGuiDataHeater.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataHeater.JonGuiDataHeater build() {
        ser.JonSharedDataHeater.JonGuiDataHeater result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataHeater.JonGuiDataHeater buildPartial() {
        ser.JonSharedDataHeater.JonGuiDataHeater result = new ser.JonSharedDataHeater.JonGuiDataHeater(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ser.JonSharedDataHeater.JonGuiDataHeater result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.busVoltageV_ = busVoltageV_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.currentA_ = currentA_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.powerW_ = powerW_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.channel0_ = channel0Builder_ == null
              ? channel0_
              : channel0Builder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.channel1_ = channel1Builder_ == null
              ? channel1_
              : channel1Builder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.channel2_ = channel2Builder_ == null
              ? channel2_
              : channel2Builder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.automaticControlEnabled_ = automaticControlEnabled_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.targetTempChannel0_ = targetTempChannel0_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.targetTempChannel1_ = targetTempChannel1_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.targetTempChannel2_ = targetTempChannel2_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataHeater.JonGuiDataHeater) {
          return mergeFrom((ser.JonSharedDataHeater.JonGuiDataHeater)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataHeater.JonGuiDataHeater other) {
        if (other == ser.JonSharedDataHeater.JonGuiDataHeater.getDefaultInstance()) return this;
        if (other.getBusVoltageV() != 0F) {
          setBusVoltageV(other.getBusVoltageV());
        }
        if (other.getCurrentA() != 0F) {
          setCurrentA(other.getCurrentA());
        }
        if (other.getPowerW() != 0F) {
          setPowerW(other.getPowerW());
        }
        if (other.hasChannel0()) {
          mergeChannel0(other.getChannel0());
        }
        if (other.hasChannel1()) {
          mergeChannel1(other.getChannel1());
        }
        if (other.hasChannel2()) {
          mergeChannel2(other.getChannel2());
        }
        if (other.getAutomaticControlEnabled() != false) {
          setAutomaticControlEnabled(other.getAutomaticControlEnabled());
        }
        if (other.getTargetTempChannel0() != 0F) {
          setTargetTempChannel0(other.getTargetTempChannel0());
        }
        if (other.getTargetTempChannel1() != 0F) {
          setTargetTempChannel1(other.getTargetTempChannel1());
        }
        if (other.getTargetTempChannel2() != 0F) {
          setTargetTempChannel2(other.getTargetTempChannel2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                busVoltageV_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                currentA_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                powerW_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 34: {
                input.readMessage(
                    getChannel0FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getChannel1FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getChannel2FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                automaticControlEnabled_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 69: {
                targetTempChannel0_ = input.readFloat();
                bitField0_ |= 0x00000080;
                break;
              } // case 69
              case 77: {
                targetTempChannel1_ = input.readFloat();
                bitField0_ |= 0x00000100;
                break;
              } // case 77
              case 85: {
                targetTempChannel2_ = input.readFloat();
                bitField0_ |= 0x00000200;
                break;
              } // case 85
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float busVoltageV_ ;
      /**
       * <code>float bus_voltage_V = 1 [(.buf.validate.field) = { ... }</code>
       * @return The busVoltageV.
       */
      @java.lang.Override
      public float getBusVoltageV() {
        return busVoltageV_;
      }
      /**
       * <code>float bus_voltage_V = 1 [(.buf.validate.field) = { ... }</code>
       * @param value The busVoltageV to set.
       * @return This builder for chaining.
       */
      public Builder setBusVoltageV(float value) {

        busVoltageV_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float bus_voltage_V = 1 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearBusVoltageV() {
        bitField0_ = (bitField0_ & ~0x00000001);
        busVoltageV_ = 0F;
        onChanged();
        return this;
      }

      private float currentA_ ;
      /**
       * <code>float current_A = 2 [(.buf.validate.field) = { ... }</code>
       * @return The currentA.
       */
      @java.lang.Override
      public float getCurrentA() {
        return currentA_;
      }
      /**
       * <code>float current_A = 2 [(.buf.validate.field) = { ... }</code>
       * @param value The currentA to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentA(float value) {

        currentA_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float current_A = 2 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentA() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentA_ = 0F;
        onChanged();
        return this;
      }

      private float powerW_ ;
      /**
       * <code>float power_W = 3 [(.buf.validate.field) = { ... }</code>
       * @return The powerW.
       */
      @java.lang.Override
      public float getPowerW() {
        return powerW_;
      }
      /**
       * <code>float power_W = 3 [(.buf.validate.field) = { ... }</code>
       * @param value The powerW to set.
       * @return This builder for chaining.
       */
      public Builder setPowerW(float value) {

        powerW_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float power_W = 3 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearPowerW() {
        bitField0_ = (bitField0_ & ~0x00000004);
        powerW_ = 0F;
        onChanged();
        return this;
      }

      private ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus channel0_;
      private com.google.protobuf.SingleFieldBuilder<
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder> channel0Builder_;
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       * @return Whether the channel0 field is set.
       */
      public boolean hasChannel0() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       * @return The channel0.
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel0() {
        if (channel0Builder_ == null) {
          return channel0_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel0_;
        } else {
          return channel0Builder_.getMessage();
        }
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      public Builder setChannel0(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus value) {
        if (channel0Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channel0_ = value;
        } else {
          channel0Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      public Builder setChannel0(
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder builderForValue) {
        if (channel0Builder_ == null) {
          channel0_ = builderForValue.build();
        } else {
          channel0Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      public Builder mergeChannel0(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus value) {
        if (channel0Builder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            channel0_ != null &&
            channel0_ != ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance()) {
            getChannel0Builder().mergeFrom(value);
          } else {
            channel0_ = value;
          }
        } else {
          channel0Builder_.mergeFrom(value);
        }
        if (channel0_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      public Builder clearChannel0() {
        bitField0_ = (bitField0_ & ~0x00000008);
        channel0_ = null;
        if (channel0Builder_ != null) {
          channel0Builder_.dispose();
          channel0Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder getChannel0Builder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getChannel0FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel0OrBuilder() {
        if (channel0Builder_ != null) {
          return channel0Builder_.getMessageOrBuilder();
        } else {
          return channel0_ == null ?
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel0_;
        }
      }
      /**
       * <pre>
       * Day camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_0 = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder> 
          getChannel0FieldBuilder() {
        if (channel0Builder_ == null) {
          channel0Builder_ = new com.google.protobuf.SingleFieldBuilder<
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder>(
                  getChannel0(),
                  getParentForChildren(),
                  isClean());
          channel0_ = null;
        }
        return channel0Builder_;
      }

      private ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus channel1_;
      private com.google.protobuf.SingleFieldBuilder<
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder> channel1Builder_;
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       * @return Whether the channel1 field is set.
       */
      public boolean hasChannel1() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       * @return The channel1.
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel1() {
        if (channel1Builder_ == null) {
          return channel1_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel1_;
        } else {
          return channel1Builder_.getMessage();
        }
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      public Builder setChannel1(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus value) {
        if (channel1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channel1_ = value;
        } else {
          channel1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      public Builder setChannel1(
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder builderForValue) {
        if (channel1Builder_ == null) {
          channel1_ = builderForValue.build();
        } else {
          channel1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      public Builder mergeChannel1(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus value) {
        if (channel1Builder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            channel1_ != null &&
            channel1_ != ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance()) {
            getChannel1Builder().mergeFrom(value);
          } else {
            channel1_ = value;
          }
        } else {
          channel1Builder_.mergeFrom(value);
        }
        if (channel1_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      public Builder clearChannel1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        channel1_ = null;
        if (channel1Builder_ != null) {
          channel1Builder_.dispose();
          channel1Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder getChannel1Builder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getChannel1FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel1OrBuilder() {
        if (channel1Builder_ != null) {
          return channel1Builder_.getMessageOrBuilder();
        } else {
          return channel1_ == null ?
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel1_;
        }
      }
      /**
       * <pre>
       * LRF glass (15W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_1 = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder> 
          getChannel1FieldBuilder() {
        if (channel1Builder_ == null) {
          channel1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder>(
                  getChannel1(),
                  getParentForChildren(),
                  isClean());
          channel1_ = null;
        }
        return channel1Builder_;
      }

      private ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus channel2_;
      private com.google.protobuf.SingleFieldBuilder<
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder> channel2Builder_;
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       * @return Whether the channel2 field is set.
       */
      public boolean hasChannel2() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       * @return The channel2.
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus getChannel2() {
        if (channel2Builder_ == null) {
          return channel2_ == null ? ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel2_;
        } else {
          return channel2Builder_.getMessage();
        }
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      public Builder setChannel2(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus value) {
        if (channel2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channel2_ = value;
        } else {
          channel2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      public Builder setChannel2(
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder builderForValue) {
        if (channel2Builder_ == null) {
          channel2_ = builderForValue.build();
        } else {
          channel2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      public Builder mergeChannel2(ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus value) {
        if (channel2Builder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            channel2_ != null &&
            channel2_ != ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance()) {
            getChannel2Builder().mergeFrom(value);
          } else {
            channel2_ = value;
          }
        } else {
          channel2Builder_.mergeFrom(value);
        }
        if (channel2_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      public Builder clearChannel2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        channel2_ = null;
        if (channel2Builder_ != null) {
          channel2Builder_.dispose();
          channel2Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder getChannel2Builder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getChannel2FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      public ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder getChannel2OrBuilder() {
        if (channel2Builder_ != null) {
          return channel2Builder_.getMessageOrBuilder();
        } else {
          return channel2_ == null ?
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.getDefaultInstance() : channel2_;
        }
      }
      /**
       * <pre>
       * Heat camera glass (60W)
       * </pre>
       *
       * <code>.ser.JonGuiDataHeaterChannelStatus channel_2 = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder> 
          getChannel2FieldBuilder() {
        if (channel2Builder_ == null) {
          channel2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatus.Builder, ser.JonSharedDataHeater.JonGuiDataHeaterChannelStatusOrBuilder>(
                  getChannel2(),
                  getParentForChildren(),
                  isClean());
          channel2_ = null;
        }
        return channel2Builder_;
      }

      private boolean automaticControlEnabled_ ;
      /**
       * <code>bool automatic_control_enabled = 7;</code>
       * @return The automaticControlEnabled.
       */
      @java.lang.Override
      public boolean getAutomaticControlEnabled() {
        return automaticControlEnabled_;
      }
      /**
       * <code>bool automatic_control_enabled = 7;</code>
       * @param value The automaticControlEnabled to set.
       * @return This builder for chaining.
       */
      public Builder setAutomaticControlEnabled(boolean value) {

        automaticControlEnabled_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool automatic_control_enabled = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAutomaticControlEnabled() {
        bitField0_ = (bitField0_ & ~0x00000040);
        automaticControlEnabled_ = false;
        onChanged();
        return this;
      }

      private float targetTempChannel0_ ;
      /**
       * <pre>
       * Target temperatures for PID control (persisted via state storage)
       * </pre>
       *
       * <code>float target_temp_channel_0 = 8 [(.buf.validate.field) = { ... }</code>
       * @return The targetTempChannel0.
       */
      @java.lang.Override
      public float getTargetTempChannel0() {
        return targetTempChannel0_;
      }
      /**
       * <pre>
       * Target temperatures for PID control (persisted via state storage)
       * </pre>
       *
       * <code>float target_temp_channel_0 = 8 [(.buf.validate.field) = { ... }</code>
       * @param value The targetTempChannel0 to set.
       * @return This builder for chaining.
       */
      public Builder setTargetTempChannel0(float value) {

        targetTempChannel0_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Target temperatures for PID control (persisted via state storage)
       * </pre>
       *
       * <code>float target_temp_channel_0 = 8 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetTempChannel0() {
        bitField0_ = (bitField0_ & ~0x00000080);
        targetTempChannel0_ = 0F;
        onChanged();
        return this;
      }

      private float targetTempChannel1_ ;
      /**
       * <code>float target_temp_channel_1 = 9 [(.buf.validate.field) = { ... }</code>
       * @return The targetTempChannel1.
       */
      @java.lang.Override
      public float getTargetTempChannel1() {
        return targetTempChannel1_;
      }
      /**
       * <code>float target_temp_channel_1 = 9 [(.buf.validate.field) = { ... }</code>
       * @param value The targetTempChannel1 to set.
       * @return This builder for chaining.
       */
      public Builder setTargetTempChannel1(float value) {

        targetTempChannel1_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>float target_temp_channel_1 = 9 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetTempChannel1() {
        bitField0_ = (bitField0_ & ~0x00000100);
        targetTempChannel1_ = 0F;
        onChanged();
        return this;
      }

      private float targetTempChannel2_ ;
      /**
       * <code>float target_temp_channel_2 = 10 [(.buf.validate.field) = { ... }</code>
       * @return The targetTempChannel2.
       */
      @java.lang.Override
      public float getTargetTempChannel2() {
        return targetTempChannel2_;
      }
      /**
       * <code>float target_temp_channel_2 = 10 [(.buf.validate.field) = { ... }</code>
       * @param value The targetTempChannel2 to set.
       * @return This builder for chaining.
       */
      public Builder setTargetTempChannel2(float value) {

        targetTempChannel2_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>float target_temp_channel_2 = 10 [(.buf.validate.field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetTempChannel2() {
        bitField0_ = (bitField0_ & ~0x00000200);
        targetTempChannel2_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ser.JonGuiDataHeater)
    }

    // @@protoc_insertion_point(class_scope:ser.JonGuiDataHeater)
    private static final ser.JonSharedDataHeater.JonGuiDataHeater DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataHeater.JonGuiDataHeater();
    }

    public static ser.JonSharedDataHeater.JonGuiDataHeater getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataHeater>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataHeater>() {
      @java.lang.Override
      public JonGuiDataHeater parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataHeater> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataHeater> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataHeater.JonGuiDataHeater getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_JonGuiDataHeaterChannelStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ser_JonGuiDataHeaterChannelStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_JonGuiDataHeater_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ser_JonGuiDataHeater_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034jon_shared_data_heater.proto\022\003ser\032\033buf" +
      "/validate/validate.proto\"\222\001\n\035JonGuiDataH" +
      "eaterChannelStatus\022\023\n\013temperature\030\001 \001(\002\022" +
      "%\n\021applied_voltage_V\030\002 \001(\002B\n\272H\007\n\005-\000\000\000\000\022$" +
      "\n\020target_voltage_V\030\003 \001(\002B\n\272H\007\n\005-\000\000\000\000\022\017\n\007" +
      "enabled\030\004 \001(\010\"\311\003\n\020JonGuiDataHeater\022!\n\rbu" +
      "s_voltage_V\030\001 \001(\002B\n\272H\007\n\005-\000\000\000\000\022\035\n\tcurrent" +
      "_A\030\002 \001(\002B\n\272H\007\n\005-\000\000\000\000\022\033\n\007power_W\030\003 \001(\002B\n\272" +
      "H\007\n\005-\000\000\000\000\0225\n\tchannel_0\030\004 \001(\0132\".ser.JonGu" +
      "iDataHeaterChannelStatus\0225\n\tchannel_1\030\005 " +
      "\001(\0132\".ser.JonGuiDataHeaterChannelStatus\022" +
      "5\n\tchannel_2\030\006 \001(\0132\".ser.JonGuiDataHeate" +
      "rChannelStatus\022!\n\031automatic_control_enab" +
      "led\030\007 \001(\010\022.\n\025target_temp_channel_0\030\010 \001(\002" +
      "B\017\272H\014\n\n\035\000\000pB-\000\000\000\000\022.\n\025target_temp_channel" +
      "_1\030\t \001(\002B\017\272H\014\n\n\035\000\000pB-\000\000\000\000\022.\n\025target_temp" +
      "_channel_2\030\n \001(\002B\017\272H\014\n\n\035\000\000pB-\000\000\000\000BNZLgit" +
      "-codecommit.eu-central-1.amazonaws.com/v" +
      "1/repos/jettison/jonp/data/heaterb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_ser_JonGuiDataHeaterChannelStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ser_JonGuiDataHeaterChannelStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ser_JonGuiDataHeaterChannelStatus_descriptor,
        new java.lang.String[] { "Temperature", "AppliedVoltageV", "TargetVoltageV", "Enabled", });
    internal_static_ser_JonGuiDataHeater_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ser_JonGuiDataHeater_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ser_JonGuiDataHeater_descriptor,
        new java.lang.String[] { "BusVoltageV", "CurrentA", "PowerW", "Channel0", "Channel1", "Channel2", "AutomaticControlEnabled", "TargetTempChannel0", "TargetTempChannel1", "TargetTempChannel2", });
    descriptor.resolveAllFeaturesImmutable();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
