// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_cmd_day_camera.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cmd.DayCamera;

@kotlin.jvm.JvmName("-initializehalt")
public inline fun halt(block: com.cmd.DayCamera.HaltKt.Dsl.() -> kotlin.Unit): com.cmd.DayCamera.Halt =
  com.cmd.DayCamera.HaltKt.Dsl._create(com.cmd.DayCamera.Halt.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `cmd.DayCamera.Halt`
 */
public object HaltKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cmd.DayCamera.Halt.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cmd.DayCamera.Halt.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cmd.DayCamera.Halt = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cmd.DayCamera.Halt.copy(block: `com.cmd.DayCamera`.HaltKt.Dsl.() -> kotlin.Unit): com.cmd.DayCamera.Halt =
  `com.cmd.DayCamera`.HaltKt.Dsl._create(this.toBuilder()).apply { block() }._build()

