// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_cv_dump_archive.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package jon.cvdump;

@kotlin.jvm.JvmName("-initializecaptureWindow")
public inline fun captureWindow(block: jon.cvdump.CaptureWindowKt.Dsl.() -> kotlin.Unit): jon.cvdump.JonCvDumpArchive.CaptureWindow =
  jon.cvdump.CaptureWindowKt.Dsl._create(jon.cvdump.JonCvDumpArchive.CaptureWindow.newBuilder()).apply { block() }._build()
/**
 * ```
 * The capture window in both clock domains.
 *
 * The wall stamps index the redis io-record streams (redis auto-ids are
 * wall-clock ms) and the cv_dump_sessions t0/t1 columns. The boot stamps are
 * the segment-timeline join key. They are only comparable ACROSS bundles when
 * MachineIdentity.boot_id matches, because boot_id is the namespace of every
 * CLOCK_BOOTTIME value here.
 * ```
 *
 * Protobuf type `jon.cvdump.CaptureWindow`
 */
public object CaptureWindowKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: jon.cvdump.JonCvDumpArchive.CaptureWindow.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: jon.cvdump.JonCvDumpArchive.CaptureWindow.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): jon.cvdump.JonCvDumpArchive.CaptureWindow = _builder.build()

    /**
     * ```
     * ISO-8601, RFC3339 with nanoseconds, UTC
     * ```
     *
     * `string t0_wall = 1;`
     */
    public var t0Wall: kotlin.String
      @JvmName("getT0Wall")
      get() = _builder.t0Wall
      @JvmName("setT0Wall")
      set(value) {
        _builder.t0Wall = value
      }
    /**
     * ```
     * ISO-8601, RFC3339 with nanoseconds, UTC
     * ```
     *
     * `string t0_wall = 1;`
     */
    public fun clearT0Wall() {
      _builder.clearT0Wall()
    }

    /**
     * `string t1_wall = 2;`
     */
    public var t1Wall: kotlin.String
      @JvmName("getT1Wall")
      get() = _builder.t1Wall
      @JvmName("setT1Wall")
      set(value) {
        _builder.t1Wall = value
      }
    /**
     * `string t1_wall = 2;`
     */
    public fun clearT1Wall() {
      _builder.clearT1Wall()
    }

    /**
     * ```
     * CLOCK_BOOTTIME at the dump-start edge
     * ```
     *
     * `int64 t0_boot_ns = 3;`
     */
    public var t0BootNs: kotlin.Long
      @JvmName("getT0BootNs")
      get() = _builder.t0BootNs
      @JvmName("setT0BootNs")
      set(value) {
        _builder.t0BootNs = value
      }
    /**
     * ```
     * CLOCK_BOOTTIME at the dump-start edge
     * ```
     *
     * `int64 t0_boot_ns = 3;`
     */
    public fun clearT0BootNs() {
      _builder.clearT0BootNs()
    }

    /**
     * ```
     * CLOCK_BOOTTIME at the dump-stop edge
     * ```
     *
     * `int64 t1_boot_ns = 4;`
     */
    public var t1BootNs: kotlin.Long
      @JvmName("getT1BootNs")
      get() = _builder.t1BootNs
      @JvmName("setT1BootNs")
      set(value) {
        _builder.t1BootNs = value
      }
    /**
     * ```
     * CLOCK_BOOTTIME at the dump-stop edge
     * ```
     *
     * `int64 t1_boot_ns = 4;`
     */
    public fun clearT1BootNs() {
      _builder.clearT1BootNs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun jon.cvdump.JonCvDumpArchive.CaptureWindow.copy(block: `jon.cvdump`.CaptureWindowKt.Dsl.() -> kotlin.Unit): jon.cvdump.JonCvDumpArchive.CaptureWindow =
  `jon.cvdump`.CaptureWindowKt.Dsl._create(this.toBuilder()).apply { block() }._build()

