/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_OPAQUE_OSD_CLIENT_METADATA_PB_H_INCLUDED
#define PB_SER_OPAQUE_OSD_CLIENT_METADATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Client-side canvas metadata for OSD resolution-aware rendering.
 Injected by frontend into JonGUIState.opaque_payloads.

 UUID: 01941b00-0000-7000-8000-000000000001 */
typedef struct _ser_OsdClientMetadata {
    /* Physical canvas width in pixels (CSS width × devicePixelRatio)
 Valid range: 1-40960 (supports up to 8K × 5) */
    uint32_t canvas_width_px;
    /* Physical canvas height in pixels (CSS height × devicePixelRatio) */
    uint32_t canvas_height_px;
    /* Device pixel ratio (window.devicePixelRatio)
 Typical values: 1.0 (standard), 1.5, 2.0 (Retina), 3.0 (mobile) */
    float device_pixel_ratio;
    /* OSD framebuffer width (1920 for day, 900 for heat) */
    uint32_t osd_buffer_width;
    /* OSD framebuffer height (1080 for day, 720 for heat) */
    uint32_t osd_buffer_height;
} ser_OsdClientMetadata;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ser_OsdClientMetadata_init_default       {0, 0, 0, 0, 0}
#define ser_OsdClientMetadata_init_zero          {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ser_OsdClientMetadata_canvas_width_px_tag 1
#define ser_OsdClientMetadata_canvas_height_px_tag 2
#define ser_OsdClientMetadata_device_pixel_ratio_tag 3
#define ser_OsdClientMetadata_osd_buffer_width_tag 4
#define ser_OsdClientMetadata_osd_buffer_height_tag 5

/* Struct field encoding specification for nanopb */
#define ser_OsdClientMetadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   canvas_width_px,   1) \
X(a, STATIC,   SINGULAR, UINT32,   canvas_height_px,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    device_pixel_ratio,   3) \
X(a, STATIC,   SINGULAR, UINT32,   osd_buffer_width,   4) \
X(a, STATIC,   SINGULAR, UINT32,   osd_buffer_height,   5)
#define ser_OsdClientMetadata_CALLBACK NULL
#define ser_OsdClientMetadata_DEFAULT NULL

extern const pb_msgdesc_t ser_OsdClientMetadata_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_OsdClientMetadata_fields &ser_OsdClientMetadata_msg

/* Maximum encoded size of messages (where known) */
#define SER_OPAQUE_OSD_CLIENT_METADATA_PB_H_MAX_SIZE ser_OsdClientMetadata_size
#define ser_OsdClientMetadata_size               29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
