// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ui/ui_nodes.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ui;

@kotlin.jvm.JvmName("-initializeboolToggle")
public inline fun boolToggle(block: ui.BoolToggleKt.Dsl.() -> kotlin.Unit): ui.UiNodes.BoolToggle =
  ui.BoolToggleKt.Dsl._create(ui.UiNodes.BoolToggle.newBuilder()).apply { block() }._build()
/**
 * ```
 * L3 BoolToggle kind — a switch that SETS a single-`bool`-field command to its
 * on/off value (e.g. SetX{value: bool}). The generator derives one per
 * single-bool-field `:ui-pattern :toggle` command; the lowering emits a
 * WIDGET_SWITCH whose value-changed event carries the switch bool, and the
 * builder fills the bool field via `build_set_bool_command`. (Distinct from
 * `ToggleControl`, which fires two PARAMETERLESS enable/disable commands.)
 * ```
 *
 * Protobuf type `ui.BoolToggle`
 */
public object BoolToggleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ui.UiNodes.BoolToggle.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ui.UiNodes.BoolToggle.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ui.UiNodes.BoolToggle = _builder.build()

    /**
     * ```
     * Schema version — checked FIRST by the lowering (fail-fast guard).
     * ```
     *
     * `uint32 version = 1 [(.buf.validate.field) = { ... }`
     */
    public var version: kotlin.Int
      @JvmName("getVersion")
      get() = _builder.version
      @JvmName("setVersion")
      set(value) {
        _builder.version = value
      }
    /**
     * ```
     * Schema version — checked FIRST by the lowering (fail-fast guard).
     * ```
     *
     * `uint32 version = 1 [(.buf.validate.field) = { ... }`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * ```
     * Switch label.
     * ```
     *
     * `string title = 2 [(.buf.validate.field) = { ... }`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.title
      @JvmName("setTitle")
      set(value) {
        _builder.title = value
      }
    /**
     * ```
     * Switch label.
     * ```
     *
     * `string title = 2 [(.buf.validate.field) = { ... }`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * The single-bool-field command the switch sets (true on, false off).
     * ```
     *
     * `.ui.CommandBinding command = 3;`
     */
    public var command: ui.UiNodes.CommandBinding
      @JvmName("getCommand")
      get() = _builder.command
      @JvmName("setCommand")
      set(value) {
        _builder.command = value
      }
    /**
     * ```
     * The single-bool-field command the switch sets (true on, false off).
     * ```
     *
     * `.ui.CommandBinding command = 3;`
     */
    public fun clearCommand() {
      _builder.clearCommand()
    }
    /**
     * ```
     * The single-bool-field command the switch sets (true on, false off).
     * ```
     *
     * `.ui.CommandBinding command = 3;`
     * @return Whether the command field is set.
     */
    public fun hasCommand(): kotlin.Boolean {
      return _builder.hasCommand()
    }

    public val BoolToggleKt.Dsl.commandOrNull: ui.UiNodes.CommandBinding?
      get() = _builder.commandOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ui.UiNodes.BoolToggle.copy(block: `ui`.BoolToggleKt.Dsl.() -> kotlin.Unit): ui.UiNodes.BoolToggle =
  `ui`.BoolToggleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ui.UiNodes.BoolToggleOrBuilder.commandOrNull: ui.UiNodes.CommandBinding?
  get() = if (hasCommand()) getCommand() else null

