// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ui/ui_nodes.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ui;

@kotlin.jvm.JvmName("-initializecommandBinding")
public inline fun commandBinding(block: ui.CommandBindingKt.Dsl.() -> kotlin.Unit): ui.UiNodes.CommandBinding =
  ui.CommandBindingKt.Dsl._create(ui.UiNodes.CommandBinding.newBuilder()).apply { block() }._build()
/**
 * ```
 * The proto COMMAND this node sends. `command_id` IS the EventBinding.name
 * the lowered Screen emits and the command-builder maps to a cmd.Root oneof
 * leaf (verified against the `cmd::` tree, Class-c2 / R4 oracle).
 * ```
 *
 * Protobuf type `ui.CommandBinding`
 */
public object CommandBindingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ui.UiNodes.CommandBinding.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ui.UiNodes.CommandBinding.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ui.UiNodes.CommandBinding = _builder.build()

    /**
     * ```
     * Command identifier = EventBinding.name, e.g. "day.clahe.set". Resolves
     * to a concrete cmd.Root variant (command-builder input).
     * ```
     *
     * `string command_id = 1 [(.buf.validate.field) = { ... }`
     */
    public var commandId: kotlin.String
      @JvmName("getCommandId")
      get() = _builder.commandId
      @JvmName("setCommandId")
      set(value) {
        _builder.commandId = value
      }
    /**
     * ```
     * Command identifier = EventBinding.name, e.g. "day.clahe.set". Resolves
     * to a concrete cmd.Root variant (command-builder input).
     * ```
     *
     * `string command_id = 1 [(.buf.validate.field) = { ... }`
     */
    public fun clearCommandId() {
      _builder.clearCommandId()
    }

    /**
     * ```
     * Fixed-point convention for event→command projection (absent ⇒ scale 1).
     * ```
     *
     * `.ui.FixedPointScale scale = 2;`
     */
    public var scale: ui.UiNodes.FixedPointScale
      @JvmName("getScale")
      get() = _builder.scale
      @JvmName("setScale")
      set(value) {
        _builder.scale = value
      }
    /**
     * ```
     * Fixed-point convention for event→command projection (absent ⇒ scale 1).
     * ```
     *
     * `.ui.FixedPointScale scale = 2;`
     */
    public fun clearScale() {
      _builder.clearScale()
    }
    /**
     * ```
     * Fixed-point convention for event→command projection (absent ⇒ scale 1).
     * ```
     *
     * `.ui.FixedPointScale scale = 2;`
     * @return Whether the scale field is set.
     */
    public fun hasScale(): kotlin.Boolean {
      return _builder.hasScale()
    }

    public val CommandBindingKt.Dsl.scaleOrNull: ui.UiNodes.FixedPointScale?
      get() = _builder.scaleOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ui.UiNodes.CommandBinding.copy(block: `ui`.CommandBindingKt.Dsl.() -> kotlin.Unit): ui.UiNodes.CommandBinding =
  `ui`.CommandBindingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ui.UiNodes.CommandBindingOrBuilder.scaleOrNull: ui.UiNodes.FixedPointScale?
  get() = if (hasScale()) getScale() else null

