// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ui/ui_ast.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ui;

@kotlin.jvm.JvmName("-initializefieldPatch")
public inline fun fieldPatch(block: ui.FieldPatchKt.Dsl.() -> kotlin.Unit): ui.UiAst.FieldPatch =
  ui.FieldPatchKt.Dsl._create(ui.UiAst.FieldPatch.newBuilder()).apply { block() }._build()
/**
 * ```
 * One fixed-width slot in a CmdSpec.root_template the renderer overwrites.
 * ```
 *
 * Protobuf type `ui.FieldPatch`
 */
public object FieldPatchKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ui.UiAst.FieldPatch.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ui.UiAst.FieldPatch.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ui.UiAst.FieldPatch = _builder.build()

    /**
     * ```
     * start of the slot in root_template
     * ```
     *
     * `uint32 byte_offset = 1;`
     */
    public var byteOffset: kotlin.Int
      @JvmName("getByteOffset")
      get() = _builder.byteOffset
      @JvmName("setByteOffset")
      set(value) {
        _builder.byteOffset = value
      }
    /**
     * ```
     * start of the slot in root_template
     * ```
     *
     * `uint32 byte_offset = 1;`
     */
    public fun clearByteOffset() {
      _builder.clearByteOffset()
    }

    /**
     * ```
     * slot width (8 for a double, 5/10 for a padded varint)
     * ```
     *
     * `uint32 byte_width = 2;`
     */
    public var byteWidth: kotlin.Int
      @JvmName("getByteWidth")
      get() = _builder.byteWidth
      @JvmName("setByteWidth")
      set(value) {
        _builder.byteWidth = value
      }
    /**
     * ```
     * slot width (8 for a double, 5/10 for a padded varint)
     * ```
     *
     * `uint32 byte_width = 2;`
     */
    public fun clearByteWidth() {
      _builder.clearByteWidth()
    }

    /**
     * `.ui.PatchKind kind = 3 [(.buf.validate.field) = { ... }`
     */
    public var kind: ui.UiAst.PatchKind
      @JvmName("getKind")
      get() = _builder.kind
      @JvmName("setKind")
      set(value) {
        _builder.kind = value
      }
    public var kindValue: kotlin.Int
      @JvmName("getKindValue")
      get() = _builder.kindValue
      @JvmName("setKindValue")
      set(value) {
        _builder.kindValue = value
      }
    /**
     * `.ui.PatchKind kind = 3 [(.buf.validate.field) = { ... }`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * ```
     * gen-time wire-scale (uigen.scales): the runtime value × scale is the
     * wire int for a varint leaf; 1 for a verbatim double (NDC).
     * ```
     *
     * `sint32 wire_scale = 4;`
     */
    public var wireScale: kotlin.Int
      @JvmName("getWireScale")
      get() = _builder.wireScale
      @JvmName("setWireScale")
      set(value) {
        _builder.wireScale = value
      }
    /**
     * ```
     * gen-time wire-scale (uigen.scales): the runtime value × scale is the
     * wire int for a varint leaf; 1 for a verbatim double (NDC).
     * ```
     *
     * `sint32 wire_scale = 4;`
     */
    public fun clearWireScale() {
      _builder.clearWireScale()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ui.UiAst.FieldPatch.copy(block: `ui`.FieldPatchKt.Dsl.() -> kotlin.Unit): ui.UiAst.FieldPatch =
  `ui`.FieldPatchKt.Dsl._create(this.toBuilder()).apply { block() }._build()

