// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ui/ui_ast.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ui;

@kotlin.jvm.JvmName("-initializetableProps")
public inline fun tableProps(block: ui.TablePropsKt.Dsl.() -> kotlin.Unit): ui.UiAst.TableProps =
  ui.TablePropsKt.Dsl._create(ui.UiAst.TableProps.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ui.TableProps`
 */
public object TablePropsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ui.UiAst.TableProps.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ui.UiAst.TableProps.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ui.UiAst.TableProps = _builder.build()

    /**
     * `uint32 row_count = 1;`
     */
    public var rowCount: kotlin.Int
      @JvmName("getRowCount")
      get() = _builder.rowCount
      @JvmName("setRowCount")
      set(value) {
        _builder.rowCount = value
      }
    /**
     * `uint32 row_count = 1;`
     */
    public fun clearRowCount() {
      _builder.clearRowCount()
    }

    /**
     * `uint32 column_count = 2;`
     */
    public var columnCount: kotlin.Int
      @JvmName("getColumnCount")
      get() = _builder.columnCount
      @JvmName("setColumnCount")
      set(value) {
        _builder.columnCount = value
      }
    /**
     * `uint32 column_count = 2;`
     */
    public fun clearColumnCount() {
      _builder.clearColumnCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ui.UiAst.TableProps.copy(block: `ui`.TablePropsKt.Dsl.() -> kotlin.Unit): ui.UiAst.TableProps =
  `ui`.TablePropsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

